#!/usr/bin/env python3
"""Generate exact runtime-governance provider tables for every SDK facade."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "sdk/conformance/runtime_governance_abilities.json"


def routes() -> list[tuple[str, str]]:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    return [
        (ability, provider)
        for provider in ("ability_descriptor", "receipt_history")
        for ability in document[provider]
    ]


def rust(items: list[tuple[str, str]]) -> str:
    descriptor = [ability for ability, provider in items if provider == "ability_descriptor"]
    receipt = [ability for ability, provider in items if provider == "receipt_history"]
    descriptor_rows = ", ".join(f'"{ability}"' for ability in descriptor)
    receipt_rows = "\n".join(f'    "{ability}",' for ability in receipt)
    return f'''// @generated by tools/scripts/generate-runtime-governance-routes.py

pub(crate) const ABILITY_DESCRIPTOR_PROVIDER: &str = "ability_descriptor";
pub(crate) const RECEIPT_HISTORY_PROVIDER: &str = "receipt_history";

pub(crate) const ABILITY_DESCRIPTOR_ABILITIES: &[&str] =
    &[{descriptor_rows}];

pub(crate) const RECEIPT_HISTORY_ABILITIES: &[&str] = &[
{receipt_rows}
];

pub(crate) fn canonical_governance_ability(value: &str) -> Option<&'static str> {{
    let value = value.trim();
    ABILITY_DESCRIPTOR_ABILITIES
        .iter()
        .chain(RECEIPT_HISTORY_ABILITIES)
        .copied()
        .find(|ability| value == *ability || value.ends_with(&format!(".{{ability}}")))
}}

pub(crate) fn descriptor_provider(value: &str) -> Option<&'static str> {{
    let ability = canonical_governance_ability(value)?;
    if ABILITY_DESCRIPTOR_ABILITIES.contains(&ability) {{
        Some(ABILITY_DESCRIPTOR_PROVIDER)
    }} else {{
        Some(RECEIPT_HISTORY_PROVIDER)
    }}
}}
'''


def go(items: list[tuple[str, str]]) -> str:
    rows = "\n".join(
        f'\t{{ability: "{ability}", provider: runtime'
        f'{"AbilityDescriptor" if provider == "ability_descriptor" else "ReceiptHistory"}Provider}},'
        for ability, provider in items
    )
    return f'''// Code generated by tools/scripts/generate-runtime-governance-routes.py. DO NOT EDIT.

package easynet

import "strings"

const (
\truntimeAbilityDescriptorProvider = "ability_descriptor"
\truntimeReceiptHistoryProvider    = "receipt_history"
)

type runtimeGovernanceRoute struct {{
\tability  string
\tprovider string
}}

var runtimeGovernanceRoutes = [...]runtimeGovernanceRoute{{
{rows}
}}

func runtimeGovernanceDescriptorProviderForAbility(abilityName string) string {{
\tabilityName = strings.TrimSpace(abilityName)
\tfor _, route := range runtimeGovernanceRoutes {{
\t\tif abilityName == route.ability || strings.HasSuffix(abilityName, "."+route.ability) {{
\t\t\treturn route.provider
\t\t}}
\t}}
\treturn ""
}}

func isRuntimeGovernanceReadAbility(abilityName string) bool {{
\treturn runtimeGovernanceDescriptorProviderForAbility(abilityName) != ""
}}
'''


def python(items: list[tuple[str, str]]) -> str:
    rows = "\n".join(
        f'    ("{ability}", {"ABILITY_DESCRIPTOR_PROVIDER" if provider == "ability_descriptor" else "RECEIPT_HISTORY_PROVIDER"}),'
        for ability, provider in items
    )
    return f'''"""Generated runtime governance ability classification shared by SDK facades."""

from __future__ import annotations

ABILITY_DESCRIPTOR_PROVIDER = "ability_descriptor"
RECEIPT_HISTORY_PROVIDER = "receipt_history"

_RUNTIME_GOVERNANCE_ROUTES = (
{rows}
)


def governance_descriptor_provider_for_ability(
    ability_name: str = "", *, ability_ura: str = ""
) -> str:
    for candidate in _ability_candidates(ability_name, ability_ura):
        for route, provider in _RUNTIME_GOVERNANCE_ROUTES:
            if candidate == route or candidate.endswith(f".{{route}}"):
                return provider
    return ""


def is_runtime_governance_read_ability(
    ability_name: str = "", *, ability_ura: str = ""
) -> bool:
    return bool(governance_descriptor_provider_for_ability(ability_name, ability_ura=ability_ura))


def _ability_candidates(ability_name: str, ability_ura: str) -> tuple[str, ...]:
    values: list[str] = []
    for value in (ability_name, ability_ura):
        if not isinstance(value, str):
            continue
        trimmed = value.strip()
        if trimmed and trimmed not in values:
            values.append(trimmed)
    return tuple(values)
'''


def node(items: list[tuple[str, str]]) -> str:
    rows = "\n".join(
        f'  ["{ability}", {"RUNTIME_ABILITY_DESCRIPTOR_PROVIDER" if provider == "ability_descriptor" else "RUNTIME_RECEIPT_HISTORY_PROVIDER"}],'
        for ability, provider in items
    )
    return f'''// Code generated by tools/scripts/generate-runtime-governance-routes.py. DO NOT EDIT.

export const RUNTIME_ABILITY_DESCRIPTOR_PROVIDER = "ability_descriptor";
export const RUNTIME_RECEIPT_HISTORY_PROVIDER = "receipt_history";

const RUNTIME_GOVERNANCE_ROUTES = Object.freeze([
{rows}
]);

export function canonicalRuntimeGovernanceAbility(value) {{
  const clean = String(value ?? "").trim();
  const match = RUNTIME_GOVERNANCE_ROUTES.find(
    ([ability]) => clean === ability || clean.endsWith(`.${{ability}}`),
  );
  return match?.[0] ?? "";
}}

export function generatedRuntimeGovernanceDescriptorProvider(value) {{
  const clean = String(value ?? "").trim();
  const match = RUNTIME_GOVERNANCE_ROUTES.find(
    ([ability]) => clean === ability || clean.endsWith(`.${{ability}}`),
  );
  return match?.[1] ?? "";
}}
'''


def java(items: list[tuple[str, str]]) -> str:
    rows = ",\n".join(
        f'    new Route("{ability}", RuntimeDescriptorRefRequest.'
        f'{"ABILITY_DESCRIPTOR_PROVIDER" if provider == "ability_descriptor" else "RECEIPT_HISTORY_PROVIDER"})'
        for ability, provider in items
    )
    return f'''// Code generated by tools/scripts/generate-runtime-governance-routes.py. DO NOT EDIT.
package run.runtime.sdk;

final class RuntimeGovernanceRoutesGen {{
  private record Route(String ability, String provider) {{}}

  private static final Route[] ROUTES = {{
{rows}
  }};

  private RuntimeGovernanceRoutesGen() {{}}

  static String canonicalAbility(String value) {{
    String clean = value == null ? "" : value.trim();
    for (Route route : ROUTES) {{
      if (clean.equals(route.ability()) || clean.endsWith("." + route.ability())) {{
        return route.ability();
      }}
    }}
    return "";
  }}

  static String descriptorProvider(String value) {{
    String clean = value == null ? "" : value.trim();
    for (Route route : ROUTES) {{
      if (clean.equals(route.ability()) || clean.endsWith("." + route.ability())) {{
        return route.provider();
      }}
    }}
    return "";
  }}
}}
'''


def swift(items: list[tuple[str, str]]) -> str:
    rows = "\n".join(
        f'        ("{ability}", RuntimeDescriptorRefRequest.'
        f'{"abilityDescriptorProvider" if provider == "ability_descriptor" else "receiptHistoryProvider"}),'
        for ability, provider in items
    )
    return f'''// Code generated by tools/scripts/generate-runtime-governance-routes.py. DO NOT EDIT.

import Foundation

enum RuntimeGovernanceRoutesGen {{
    private static let routes: [(ability: String, provider: String)] = [
{rows}
    ]

    static func canonicalAbility(_ value: String) -> String? {{
        let clean = value.trimmingCharacters(in: .whitespacesAndNewlines)
        return routes.first {{ route in
            clean == route.ability || clean.hasSuffix(".\\(route.ability)")
        }}?.ability
    }}

    static func descriptorProvider(_ value: String) -> String {{
        let clean = value.trimmingCharacters(in: .whitespacesAndNewlines)
        return routes.first {{ route in
            clean == route.ability || clean.hasSuffix(".\\(route.ability)")
        }}?.provider ?? ""
    }}
}}
'''


def outputs(items: list[tuple[str, str]]) -> dict[Path, str]:
    return {
        ROOT / "src/daemon/ability/runtime_governance_routes_gen.rs": rust(items),
        ROOT / "sdk/go/runtime_governance.go": go(items),
        ROOT / "sdk/python/easynet_sdk/_runtime_governance.py": python(items),
        ROOT / "sdk/node/runtime-governance-routes.js": node(items),
        ROOT / "sdk/java/src/main/java/run/runtime/sdk/RuntimeGovernanceRoutesGen.java": java(items),
        ROOT / "sdk/swift/Sources/RuntimeSDK/RuntimeGovernanceRoutesGen.swift": swift(items),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift: list[str] = []
    for path, content in outputs(routes()).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if drift:
        raise SystemExit("generated runtime governance route drift: " + ", ".join(drift))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
