// EasyNet CLI — plugin descriptor projection
// ==========================================
//
// File: src/runtime/plugin_host/descriptor.rs
// Description: Project package-index metadata into ability descriptors.

use serde_json::Value;

use crate::runtime::plugin_host::errors::Result;
use crate::runtime::plugin_host::index::PluginPackageIndex;

/// Descriptor-generation metadata for one plugin-owned ability.
#[derive(Debug, Clone)]
pub struct PluginAbilityMetadata {
    pub name: String,
    pub description: String,
    pub input_schema: Value,
}

/// Descriptor projector over package index state.
pub struct PluginDescriptorProjector;

impl PluginDescriptorProjector {
    /// Project every plugin ability descriptor that can be generated by this
    /// binary. This ignores env, platform, and runtime load status.
    pub fn project(index: &PluginPackageIndex) -> Result<Vec<PluginAbilityMetadata>> {
        let mut out = Vec::new();
        for package in index.packages() {
            for descriptor in package.ability_descriptors() {
                out.push(PluginAbilityMetadata {
                    name: descriptor.name().to_string(),
                    description: descriptor.description().to_string(),
                    input_schema: descriptor.input_schema().clone(),
                });
            }
        }
        out.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::*;
    use crate::runtime::plugin_host::package::tests::write_test_package;
    use crate::runtime::plugin_host::package::PluginPackage;

    #[test]
    fn plugin_host_descriptor_projector_uses_installed_ability_toml() {
        let root = tempfile::tempdir().expect("root");
        write_test_package(root.path(), "0.1.0");
        let package = Arc::new(PluginPackage::from_installed(root.path(), None).expect("package"));
        let index = PluginPackageIndex::from_packages(vec![package]).expect("index");

        let descriptors = PluginDescriptorProjector::project(&index).expect("descriptors");
        let descriptor = descriptors
            .iter()
            .find(|descriptor| descriptor.name == "device.test.echo")
            .expect("installed plugin descriptor");

        assert_eq!(
            descriptor.description,
            "test descriptor for device.test.echo"
        );
        assert_eq!(descriptor.input_schema["type"], "object");
    }
}
