// EasyNet CLI — Services Layer
// =============================
//
// File: src/services/mod.rs
// Description: Long-running, non-CLI surfaces hosted by the daemon
//              process. Today that means one thing — the local
//              `control` plane that Client FFI libraries dial into —
//              but the layer exists as a place for future sibling
//              services (IPC-over-vsock for a future hypervisor mode,
//              a planner service, etc.) to sit without polluting
//              `facade/` or `runtime/`.
//
// Layering rule
// -------------
// `services/` sits at the same layer as `facade/` and imports from
// the runtime layer only through the two hard trait boundaries:
//
//   * KernelApi  (runtime/kernel_api.rs)  — for invoking abilities,
//                                          listing sessions, etc.
//   * GatewayApi (runtime/gateway_api.rs) — NOT used here; only the
//                                          runtime itself speaks to
//                                          the gateway.
//
// `scripts/check-kernel-boundary.sh` greps `src/services/` for any
// `use crate::runtime::...` import that is not `kernel_api`,
// `invocation`, `domain`, or `receipt_subscriber`. Anything else is
// a boundary violation and fails CI.
//
// Why a separate top-level layer instead of a sibling under facade/
// -----------------------------------------------------------------
// `facade/cli` and `facade/mcp` are user-or-agent surfaces hit from
// *outside* the daemon process: the CLI user's terminal, a remote
// MCP client. `services/control` is an *intra-machine* surface
// hit by a Client FFI library loaded into another process on the
// same host. The trust model, transport, and lifetime are all
// different enough that keeping them in peer namespaces prevents
// accidental conflation (e.g. a CLI subcommand reaching into the
// IPC server's state, or vice versa).
//
// Author: Silan Hu <silan.hu@u.nus.edu>
// Copyright (c) 2026 EasyNet. All rights reserved.

pub mod control;

/// Axon `Invocation` gRPC server hosted by `easynet-daemon`. Module is
/// gated on the `axon-pb` Cargo feature because the trait it
/// implements is generated by tonic at build time. RFC-003 PR-1 is
/// the first PR to populate this module; see
/// `pr-drafts/PR-0-spec-daemon-invocation-server.md §2`.
#[cfg(feature = "axon-pb")]
pub mod axon_serve;

/// In-memory registry of live `<self>.session` reverse-channel
/// senders keyed by caller URI. RFC-003 PR-1 spec §3 — hub-side
/// liveness model that replaces unary heartbeats. Gated on `axon-pb`
/// because the dispatch sender type holds the proto-generated
/// `InvokeBidiDown` frame and the rejection path uses `tonic::Status`;
/// neither is available off-feature.
#[cfg(feature = "axon-pb")]
pub mod presence_registry;

/// On-disk trust set (`/etc/easynet/realm-trust.toml`) the daemon
/// admission gate consults to answer "is this caller permitted to
/// join this realm". RFC-003 PR-1 spec §5.2 — PR-1 reads, PR-7
/// authors via the device-pairing flow. Always built into the
/// library since the data structure is pure data + std crates;
/// only consumers in `axon_serve` need the proto plumbing the
/// `axon-pb` feature gates.
pub mod realm_trust_anchor;
