// EasyNet CLI — Services Layer
// =============================
//
// File: src/services/mod.rs
// Description: Long-running, non-CLI surfaces hosted by the daemon
//              process. Today that means one thing — the local
//              `control` plane that Client FFI libraries dial into —
//              but the layer exists as a place for future sibling
//              services (IPC-over-vsock for a future hypervisor mode,
//              a planner service, etc.) to sit without polluting
//              `facade/` or `runtime/`.
//
// Layering rule
// -------------
// `services/` sits at the same layer as `facade/` and imports from
// the runtime layer only through the two hard trait boundaries:
//
//   * KernelApi  (runtime/kernel_api.rs)  — for invoking abilities,
//                                          listing sessions, etc.
//   * GatewayApi (runtime/gateway_api.rs) — NOT used here; only the
//                                          runtime itself speaks to
//                                          the gateway.
//
// `scripts/check-kernel-boundary.sh` greps `src/services/` for any
// `use crate::runtime::...` import that is not `kernel_api`,
// `invocation`, `domain`, or `receipt_subscriber`. Anything else is
// a boundary violation and fails CI.
//
// Why a separate top-level layer instead of a sibling under facade/
// -----------------------------------------------------------------
// `facade/cli` and `facade/mcp` are user-or-agent surfaces hit from
// *outside* the daemon process: the CLI user's terminal, a remote
// MCP client. `services/control` is an *intra-machine* surface
// hit by a Client FFI library loaded into another process on the
// same host. The trust model, transport, and lifetime are all
// different enough that keeping them in peer namespaces prevents
// accidental conflation (e.g. a CLI subcommand reaching into the
// IPC server's state, or vice versa).
//
// Author: Silan Hu <silan.hu@u.nus.edu>
// Copyright (c) 2026 EasyNet. All rights reserved.

pub mod control;

/// Axon `Invocation` gRPC server hosted by `easynet-daemon`. Module is
/// gated on the `axon-pb` Cargo feature because the trait it
/// implements is generated by tonic at build time. RFC-003 PR-1 is
/// the first PR to populate this module; see
/// `pr-drafts/PR-0-spec-daemon-invocation-server.md §2`.
#[cfg(feature = "axon-pb")]
pub mod axon_serve;

/// In-memory registry of live `<self>.session` reverse-channel
/// senders keyed by caller URI. RFC-003 PR-1 spec §3 — hub-side
/// liveness model that replaces unary heartbeats. Gated on `axon-pb`
/// because the dispatch sender type holds the proto-generated
/// `InvokeBidiDown` frame and the rejection path uses `tonic::Status`;
/// neither is available off-feature.
#[cfg(feature = "axon-pb")]
pub mod presence_registry;

/// On-disk trust set (`/etc/easynet/realm-trust.toml`) the daemon
/// admission gate consults to answer "is this caller permitted to
/// join this realm". RFC-003 PR-1 spec §5.2 — PR-1 reads, PR-7
/// authors via the device-pairing flow. Always built into the
/// library since the data structure is pure data + std crates;
/// only consumers in `axon_serve` need the proto plumbing the
/// `axon-pb` feature gates.
pub mod realm_trust_anchor;

/// Cross-call correlation table for `<self>.invoke_remote` (PR-3
/// writer) and `<self>.session` (PR-2 completer). Outside
/// `presence_registry` because the concerns differ: presence is
/// "who is online right now"; pending_dispatch is "outstanding
/// cross-device calls awaiting reply". Pure data — no feature gate.
pub mod pending_dispatch;

/// Reload-friendly cell holding the daemon's current
/// operator-curated `tenant → hub_uri` map (PR-N1 commit 10/N —
/// closes the LB-37 §2.3 fallback Scope A defer note). Mirrors
/// `trust_anchor_cell` so SIGHUP-triggered `daemon-config.toml`
/// reloads republish the federated_peers map without daemon
/// restart. Pure data; no feature gate.
pub mod federated_peers_cell;

/// Per-daemon nonce replay store (RFC 001 §5.2 step 4). Wraps the
/// axon SDK's time-wheel store in `Arc<Mutex<…>>` so a single
/// instance is shared across every concurrent invoke through the
/// admission gate. PR-7 commit 4/N introduces the wrapper alongside
/// the admission upgrade. DEC-011 confirms RFC-003 ships in-memory
/// only; persistence is a Week-5+ topic.
pub mod nonce_replay_store;

/// Reload-friendly wrapper around the daemon's `RealmTrustAnchor`.
/// `<self>.register_device_pubkey` (PR-7 commit 5/N) appends an
/// entry, persists via atomic rename, then `replace`s the cell so
/// the admission gate's next read reflects the new entry. Built
/// once at boot and shared by clone between the admission facade
/// and the register-pubkey handler. DEC-010 mechanism layer.
pub mod trust_anchor_cell;

/// Bounded in-memory store the admission gate records signed
/// `InvocationReceipt`s into. PR-10 commit 2/N introduces the
/// surface; commit 3/N hooks `run_strict_admission` to emit a
/// receipt per accepted call. RFC 001 §5.3 best-effort semantics —
/// receipt write failure does not fail admission (PR-10 spec
/// INV-5). Persistence is a future RFC concern; v1 is in-memory
/// FIFO at `DEFAULT_RECEIPT_CAPACITY`.
pub mod receipt_store;

/// Cross-hub federation transport (RFC-N PR-N1 onwards). The
/// outbound dial counterpart to PR-10 commit 1/N's inbound
/// TCP+TLS listener — when a `federation.forward_invoke`
/// targets a peer realm, this module's `FederationClient` carries
/// the call across the hub-to-hub TLS channel. PR-N1 commit 1/N
/// lands the skeleton (trait + types + channel cache);
/// commits 2-5/N wire real I/O, `handle_forward_invoke`
/// integration, and the timeout / circuit-breaker / e2e suite
/// per `pr-drafts/PR-N1-spec-hub-to-hub-grpc-outbound.md`.
#[cfg(feature = "axon-pb")]
pub mod federation_client;
