// Code generated by provider_routes/generate_access_control_routes.py; DO NOT EDIT.
package easynet

const (
	accessControlProfile                     = "access_control"
	accessControlRouteManifestSHA256         = "677ac1516587c846cbdc12e74b1d35b880e260e291fcf7570859f4b220922e1a"
	accessControlAbilityGrant                = "authority.binding.grant"
	accessControlAbilityRevoke               = "authority.binding.revoke"
	accessControlAbilityList                 = "authority.binding.list"
	accessControlAbilityCheck                = "authority.binding.check"
	accessControlAbilityPolicyRequestCreate  = "policy.request.create"
	accessControlAbilityPolicyRequestResolve = "policy.request.resolve"
	accessControlAbilityPolicyRequestList    = "policy.request.list"
	accessControlAbilityAdmissionExplain     = "admission.explain"
)
