// Code generated by provider_routes/generate_principal_routes.py; DO NOT EDIT.
package easynet

const (
	principalLifecycleProfile             = "principal_lifecycle"
	principalLifecycleRouteManifestSHA256 = "268a2e372ca9fa106c868a0b4c2561d334fd72dc62f8844b5a8add627de52038"
	principalAbilityCreate                = "principal.lifecycle.create"
	principalAbilityBindFirstKey          = "principal.lifecycle.bind_first_key"
	principalAbilityAddKey                = "principal.lifecycle.add_key"
	principalAbilityRotateKey             = "principal.lifecycle.rotate_key"
	principalAbilityRevokeKey             = "principal.lifecycle.revoke_key"
	principalAbilityConfigureRecovery     = "principal.lifecycle.configure_recovery"
	principalAbilityRecover               = "principal.lifecycle.recover"
	principalAbilitySuspend               = "principal.lifecycle.suspend"
	principalAbilityReactivate            = "principal.lifecycle.reactivate"
	principalAbilityDelete                = "principal.lifecycle.delete"
	principalAbilityIssueEnrollment       = "principal.lifecycle.issue_enrollment"
	principalAbilityRevokeEnrollment      = "principal.lifecycle.revoke_enrollment"
	principalAbilityIssueGrant            = "principal.lifecycle.issue_grant"
	principalAbilityRevokeGrant           = "principal.lifecycle.revoke_grant"
	principalAbilityGet                   = "principal.lifecycle.get"
)
