// Code generated by provider_routes/generate_receipt_routes.py; DO NOT EDIT.
package easynet

const (
	receiptProfile             = "receipt"
	receiptRouteManifestSHA256 = "186d834b426d4e84d3584904ed434eb19cf38bb568eebaf2db376725b74b46f2"
	receiptHistoryListAbility  = "invocation.history.list"
	receiptHistoryGetAbility   = "invocation.history.get"
	receiptTraceGetAbility     = "invocation.trace.get"
)
