// Code generated by provider_routes/generate_runtime_admin_routes.py; DO NOT EDIT.
package easynet

const (
	runtimeAdminProfile             = "runtime_admin"
	runtimeAdminRouteManifestSHA256 = "193ba5b5a28180af5d5d936930e880f7d40153963f85c6d0425c54febb214d6a"
	runtimeAdminSessionListAbility  = "session.list"
)
