// EasyNet CLI — Federation Invoke Helper (PR-N1 commit 8/N)
// =========================================================
//
// File: src/support/federation_invoke.rs
// Description: CLI bridge from `easynet ability invoke <ability-ura>
//              --node <peer-ura>` to the local daemon's gRPC
//              `Invocation::invoke` with `function_name="federation.
//              forward_invoke"`. This is what unblocks the answer-
//              sheet acceptance gate raised by perf-engineer +
//              reviewer + architect during PR-N1 review:
//              commits 1-7/N ship the
//              daemon-to-daemon wire, this commit ships the user-
//              CLI-command → daemon entry point.
//
// Wire shape
// ----------
// 1. Caller passes `(ability_ura, args, node_ura)`. `node_ura` must
//    be a canonical Axon Device or Hub URA; non-canonical inputs
//    surface as a typed error before any IPC.
// 2. The helper dials the local daemon's UDS-bound gRPC
//    `Invocation` server (default `~/.easynet/daemon.sock`).
// 3. It sends an `InvokeRequest` whose `function_name` is
//    `federation.forward_invoke` and whose `arguments` is the
//    JSON `{target_ura, inner_envelope_b64}` shape that
//    `federation_wrappers::ForwardInvokeRequest` deserialises.
//    The inner envelope carries the original `(ability_ura, args)`
//    pair so the peer-side daemon can dispatch it once it lands.
// 4. The local daemon's `dispatch_federation_forward_invoke` runs
//    the cross-realm routing landed in PR-N1 commit 3b/N, dials
//    via the `CrossHubDialer` that PR-N1 commit 6/N wires at boot,
//    and returns the peer daemon's response.
//
// Why this lives in `support/` and not `facade/cli/`
// ---------------------------------------------------
// The IPC + gRPC plumbing this helper does is reusable across CLI
// subcommands (a future `easynet mission run --node X` would do
// the same dial + frame). Putting it under `support/` matches the
// existing `local_invoke.rs` placement (the helper that backs every
// CLI subcommand's local-only path) so a reader looking for
// "where does the CLI talk to the daemon" finds both helpers in
// one directory.
//
// Feature gating
// --------------
// `axon-pb` feature gates the entire module. Production builds run
// with `axon-pb` on; minimal builds (no daemon transport) can drop
// the cross-hub bridge along with the rest of the gRPC stack.
//
// Author: Silan.Hu <silan.hu@u.nus.edu>
// Copyright (c) 2026 EasyNet. All rights reserved.

use std::time::Duration;

use anyhow::{anyhow, bail, Context};
use serde_json::{json, Value};

use crate::services::invocation_transport::ProtoEnvelope;
use easynet_axon::pb::axon::v1::invocation_client::InvocationClient;
use easynet_axon::ura::{parse_ura, URAKind};

/// Validate a `--node` argument as a canonical Axon Device or Hub URA.
/// Returns the URA string when it parses; surfaces a typed error
/// when it doesn't, with the exact wire-shape we expect quoted in
/// the message so the operator can fix the typo.
///
/// The grammar decision belongs to Axon. This helper only applies
/// the CLI policy distinction after parsing: `--node` may target a
/// Device or Hub URA, never a hosted Agent/User/Ability/Resource.
/// Hub targets must be generated by Axon's `hub_ura(realm)` builder,
/// whose clean protocol identity is `easynet:///r/<realm>/hub`.
pub fn parse_node_ura(node: &str) -> anyhow::Result<String> {
    let trimmed = node.trim();
    let parsed = parse_ura(trimmed).map_err(|err| {
        anyhow::anyhow!(
            "--node `{trimmed}` is not a canonical Axon Device or Hub URA: {err}. \
             A bare hostname or `https://...` URL is not accepted. \
             {URA_DISCOVERY_HINT}"
        )
    })?;

    match parsed.kind {
        URAKind::Device => Ok(trimmed.to_string()),
        URAKind::Hub => Ok(trimmed.to_string()),
        other => bail!(
            "--node `{trimmed}` is a canonical Axon URA, but not a Device or Hub target. \
             Got kind={other}. \
             {URA_DISCOVERY_HINT}"
        ),
    }
}

/// Operator-actionable hint appended to every `--node` parse failure.
/// Names the four places a real URA can come from today, ordered
/// most-helpful-first. Centralised so the wording stays byte-identical
/// across both `parse_node_ura` failure arms — operators can grep one
/// substring across logs.
///
/// **PR-N1 user-flow review catch**: PR-N1 ships the CLI
/// invocation surface (commit 8/N) but cross-hub URA discovery
/// from a remote machine without manual config is PR-N3
/// territory (cross-realm directory federation, not yet shipped).
/// Until PR-N3 lands, operators construct URAs by hand from the
/// sources below; the error message points at them.
const URA_DISCOVERY_HINT: &str = "Where to find a canonical URA today (until PR-N3 cross-realm \
     directory federation ships): \
     (1) `cat ~/.easynet/credentials.json` on the target machine — \
     concat `easynet:///r/<realm>/device/<node_id>` from the fields. \
     (2) `cat ~/.easynet/daemon-config.toml` and read the \
     `[daemon.federated_peers]` table — keys are realms the \
     local daemon already trusts. \
     (3) `cat /etc/easynet/realm-trust.toml` and read \
     `[[trusted_agent]]` blocks with `role = \"hub\"` — those \
     are the peer hubs the cross-hub dialer can reach. \
     (4) `easynet ability list` — local-realm only \
     today; cross-realm enumeration ships in PR-N3.";

/// Canonical Ability URA that has been proven to belong to the target owner.
///
/// This is the caller-side boundary object for `federation.forward_invoke`.
/// It is not a transport wrapper and it is not a fallback for the removed
/// ability-plus-args public API. Command adapters may choose a known system
/// ability by selector, but the selector is projected into this value before
/// the daemon IPC frame is built.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct TargetOwnedAbilityUra {
    value: String,
}

impl TargetOwnedAbilityUra {
    /// Project an internal registry selector into the canonical Ability URA
    /// owned by `target_ura`.
    pub(crate) fn from_selector(target_ura: &str, selector: &str) -> anyhow::Result<Self> {
        validate_forward_target_ura(target_ura)?;
        let public_ability = crate::ura::owner_local_ability_name(target_ura, selector);
        let ability_ura =
            crate::ura::owner_ability_ura(target_ura, &public_ability).ok_or_else(|| {
                anyhow::anyhow!("derive ability URA for {target_ura} {public_ability}")
            })?;
        Self::from_ability_ura(target_ura, &ability_ura)
    }

    /// Accept an already-canonical Ability URA after proving it belongs to
    /// `target_ura`.
    pub(crate) fn from_ability_ura(target_ura: &str, ability_ura: &str) -> anyhow::Result<Self> {
        validate_forward_target_ura(target_ura)?;
        let trimmed = ability_ura.trim();
        validate_forward_ability_owner(trimmed, target_ura)?;
        Ok(Self {
            value: trimmed.to_string(),
        })
    }

    /// Borrow the canonical URA for the transport helper.
    pub(crate) fn as_str(&self) -> &str {
        &self.value
    }
}

/// Dispatch a canonical Ability URA against `node_ura` via the local daemon's
/// `federation.forward_invoke` ability.
///
/// This is the latest public boundary for remote CLI invoke paths. The caller
/// must supply the canonical callable identity up front; this helper only
/// verifies that the Ability URA belongs to the target owner before shaping the
/// daemon IPC request.
pub fn invoke_via_federation_forward_ability_ura(
    ability_ura: &str,
    args: Value,
    node_ura: &str,
    caller_ura: Option<&str>,
) -> anyhow::Result<Value> {
    validate_forward_target_ura(node_ura)?;
    validate_forward_ability_owner(ability_ura, node_ura)?;

    let socket_path = crate::support::local_daemon_grpc::resolve_socket_path();
    if !crate::support::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    // The daemon's `federation.forward_invoke` request shape per
    // DEC-N4 §2.1: `ForwardInvokeRequest { target_ura,
    // inner_envelope_b64, causal_context_bytes,
    // forward_deadline_ms }`. The inner envelope carries the
    // original `(ability_ura, args, call_id)` tuple as a JSON blob;
    // PR-N1's daemon-to-daemon wire forwards this opaquely. The
    // outer audit / deadline fields round-trip verbatim so
    // PR-N5's InvocationReceipt can stamp causal_context.list and
    // DEC-N5 §3 can derive the inner deadline. PR-N2 will
    // introduce AXIOM mapping rewrite + signature; PR-N1 ships
    // the unsigned shape.
    //
    // DEC-N4 §2.1: a client-minted `call_id` is required so the
    // daemon's `ForwardInvokeResponse.correlation_call_id` can
    // thread it back to whichever bidi was waiting for the
    // result. We use a nanosecond+rng id; the value is opaque
    // to the daemon, only the round-trip equality matters.
    let call_id = generate_call_id();
    let inner_payload = json!({
        "ability_ura": ability_ura,
        "args": args,
        "call_id": call_id,
    });
    let inner_envelope_bytes = serde_json::to_vec(&inner_payload)
        .context("serialise inner ability call as forward_invoke payload")?;
    let inner_envelope_b64 = base64_engine_encode(&inner_envelope_bytes);

    // DEC-N4 §2.1 audit-chain + deadline fields. The CLI bridge
    // is the lowest-level synchronous initiator; it has no prior
    // `ForwardReceipt` to chain (those are PR-N5 territory) and
    // no caller-side deadline budget (CLI invocations run to
    // completion). Both fields ship as their zero-shape so the
    // peer hub treats them as "no caller hint, apply defaults".
    // Once `<self>.invoke_remote` initiator becomes the upstream
    // caller (instead of a direct CLI dial), it will populate
    // both with real values per PR-N5 §1 / DEC-N5 §3.
    //
    // Build the request through the canonical `ForwardInvokeRequest`
    // type rather than a hand-rolled `json!` object. The type carries
    // base64 serde for `causal_context_bytes` (the daemon's
    // deserializer rejects a JSON byte-array with `invalid type:
    // sequence`); serialising the struct guarantees the wire shape can
    // never drift from the contract the daemon parses.
    let forward_request = easynet_axon::ForwardInvokeRequest {
        target_ura: node_ura.to_string(),
        inner_envelope_b64,
        causal_context_bytes: Vec::new(),
        forward_deadline_ms: 0,
    };
    let forward_args_bytes =
        serde_json::to_vec(&forward_request).context("serialise ForwardInvokeRequest")?;

    // Build the outer envelope. The caller URA defaults to a
    // generic `easynet:///r/cli/device/local` so the daemon's
    // admission gate has something to log; production deployments
    // will override this with the operator's identity once
    // PR-N2 cross-realm signing lands.
    //
    // AXIOM §A1 requires both `caller` and `callee`; the daemon's
    // admission gate rejects an envelope missing either with
    // `AXON_AXIOM_ENVELOPE_INCOMPLETE:callee_missing`. For a
    // `federation.forward_invoke` call the inner ability's
    // `target_ura` is the ultimate addressee, so we stamp it as
    // both `callee` (intermediate routing hop addressee per A1
    // "intermediate hops MAY repeat target") and `subject` (the
    // identity the inner ability runs against). This matches the
    // backend Go side's `daemon_grpc/invoke_remote.go` envelope
    // convention.
    // v4.1.5 §A.URA-3 strict parsing: agent tail MUST be
    // `<user-uuid>.<agent-id>` (split on dot). The
    // the legacy CLI agent-placeholder alias fails the strict parser
    // because `local` has no dot. Use the device shape instead —
    // `r/cli/device/local` parses cleanly (device tail is a bare
    // token with no dot/slash). The daemon's loopback bypass +
    // the Postel-permissive admission paths still admit either,
    // but we want the wire to ship a parseable URA so that any
    // caller-side strict validator (or a future enforce-mode
    // flip) does not reject the envelope.
    let resolved_caller_ura = caller_ura
        .unwrap_or("easynet:///r/cli/device/local")
        .to_string();
    // AXIOM §A1: `invocation_nonce` is a 16-byte random value the
    // daemon's admission gate uses to dedup replays
    // (`AXON_NONCE_REPLAY` rejects on a hit in the replay window).
    // CLI-initiated calls are one-shot, so a fresh `OsRng` 16-byte
    // sample per call is sufficient.
    let request = ProtoEnvelope::targeted(&resolved_caller_ura, node_ura, node_ura)?
        .invoke_request("federation.forward_invoke", forward_args_bytes)?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation invoke")?;

    runtime.block_on(async move {
        let channel = crate::support::local_daemon_grpc::connect_channel(
            socket_path.clone(),
            Duration::from_secs(30),
            Duration::from_secs(10),
        )
        .await
        .context("connect to local daemon gRPC endpoint")?;

        let mut client = InvocationClient::new(channel);
        let response = client.invoke(request).await.map_err(|status| {
            // DEC-N4 §2.1: cross-hub `target_offline` surfaces
            // as `Status::failed_precondition` with reason text
            // `target_offline`. Translate that into an
            // operator-actionable bail (rather than a generic
            // RPC error) so a CLI user reading the message
            // knows the call reached the daemon but the peer
            // was unreachable.
            if status.code() == tonic::Code::FailedPrecondition
                && status.message().contains("target_offline")
            {
                anyhow!(
                    "cross-hub target `{node_ura}` is offline (federation.forward_invoke \
                     reported target_offline). Run `easynet federation peers` to see \
                     reachable peers, or `easynet runtime status` on the peer machine \
                     to confirm the daemon is running."
                )
            } else {
                anyhow!(
                    "daemon error invoking federation.forward_invoke for target `{node_ura}` \
                     (code={:?}): {}",
                    status.code(),
                    status.message(),
                )
            }
        })?;
        decode_forward_invoke_response_value(&response.into_inner())
    })
}

fn decode_forward_invoke_response_value(
    body: &easynet_axon::pb::axon::v1::InvokeResponse,
) -> anyhow::Result<Value> {
    // DEC-N4 §2.1 final shape:
    // ForwardInvokeResponse { result_bytes, correlation_call_id }
    // is the wire surface. The shape belongs to the Axon SDK and
    // serialises bytes as base64 strings, not JSON byte arrays.
    // Parsing through the SDK type keeps the CLI display layer from
    // drifting when the SDK schema changes.
    let envelope: easynet_axon::ForwardInvokeResponse = serde_json::from_slice(&body.result)
        .with_context(|| {
            format!(
                "parse federation.forward_invoke ForwardInvokeResponse envelope: \
                 result_content_type={:?}",
                body.result_content_type
            )
        })?;

    decode_forward_result_bytes(&envelope.result_bytes)
}

fn decode_forward_result_bytes(result_bytes: &[u8]) -> anyhow::Result<Value> {
    if result_bytes.is_empty() {
        return Ok(Value::Null);
    }
    match serde_json::from_slice::<Value>(result_bytes) {
        Ok(v) => Ok(v),
        Err(_) => Ok(serde_json::json!({
            "result_bytes_len": result_bytes.len(),
            "result_bytes_hex": result_bytes
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect::<String>(),
        })),
    }
}

fn validate_forward_ability_owner(ability_ura: &str, node_ura: &str) -> anyhow::Result<()> {
    crate::ura::public_ability_name_from_ability_ura(node_ura, ability_ura)
        .map(|_| ())
        .ok_or_else(|| {
            anyhow::anyhow!(
                "ability URA `{ability_ura}` is not owned by target `{node_ura}`; \
                 pass a canonical Ability URA such as `easynet:///r/<realm>/ability/device.<device-id>.<namespace>.<ability-id>`"
            )
        })
}

fn validate_forward_target_ura(target_ura: &str) -> anyhow::Result<()> {
    let parsed = parse_ura(target_ura)
        .map_err(|err| anyhow::anyhow!("invalid target URA `{target_ura}`: {err}"))?;
    match parsed.kind {
        URAKind::Device => Ok(()),
        URAKind::Hub => Ok(()),
        other => bail!("target URA `{target_ura}` must identify a Device or Hub, got kind={other}"),
    }
}

/// Cross-realm directory query against the local daemon's
/// `federation.discover` ability. Returns the parsed
/// `entries: [DirectoryEntry]` array verbatim. The single
/// dial path (UDS gRPC InvocationClient → daemon's
/// `dispatch_federation_discover`) is shared with
/// `easynet federation discover`'s own subcommand — having
/// one helper means `device list` / `auth devices` / future
/// fan-out callers cannot drift on caller URA / envelope
/// shape.
///
/// Args:
///   * `agent_ura_filter` — optional URA filter passed verbatim
///     to the daemon. `None` returns the full federated
///     directory; `Some(ura)` returns at most one entry (lex
///     tie-break on peer realm).
///   * `caller_ura` — optional caller URA for the envelope. When
///     `None`, falls back to the device URA minted from
///     `credentials.json`, then the generic
///     `easynet:///r/cli/device/local` placeholder. The daemon's
///     loopback bypass admits both shapes.
///
/// Returns the `entries` array as a `Vec<Value>` (each element
/// is a `DirectoryEntry`-shaped JSON object).
pub fn invoke_federation_discover(
    agent_ura_filter: Option<&str>,
    caller_ura: Option<&str>,
) -> anyhow::Result<Vec<Value>> {
    let socket_path = crate::support::local_daemon_grpc::resolve_socket_path();
    if !crate::support::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let mut req_args = json!({});
    if let Some(ura) = agent_ura_filter {
        req_args["agent_ura"] = Value::String(ura.to_string());
    }
    let arg_bytes = serde_json::to_vec(&req_args).context("encode discover args")?;

    let resolved_caller = caller_ura
        .map(str::to_string)
        .or_else(|| {
            crate::persistence::config::load_credentials()
                .ok()
                .map(|c| crate::ura::device_ura(&c.realm, &c.node_id))
        })
        .unwrap_or_else(|| crate::ura::device_ura("cli", "local"));

    let request = ProtoEnvelope::loopback(resolved_caller)?
        .invoke_request("federation.discover", arg_bytes)?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation.discover")?;

    let response: easynet_axon::pb::axon::v1::InvokeResponse = {
        runtime.block_on(async move {
            let channel = crate::support::local_daemon_grpc::connect_channel(
                socket_path.clone(),
                Duration::from_secs(10),
                Duration::from_secs(5),
            )
            .await
            .context("connect to local daemon gRPC endpoint")?;
            let mut client = InvocationClient::new(channel);
            let resp = client.invoke(request).await.map_err(|status| {
                anyhow!(
                    "daemon rejected federation.discover: code={:?} message={}",
                    status.code(),
                    status.message()
                )
            })?;
            Ok::<_, anyhow::Error>(resp.into_inner())
        })?
    };

    let body: Value =
        serde_json::from_slice(&response.result).context("decode discover response body")?;
    Ok(body
        .get("entries")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default())
}

/// `federation.revoke` against the local daemon's gRPC
/// InvocationServer. Removes the named Agent's directory entry on
/// the hub. CLI lifecycle surfaces (`easynet device remove`,
/// `easynet device reset --force`) call this helper instead of
/// local-only `node.remove` / `node.deregister`
/// acknowledgements.
///
/// Args:
///   * `agent_ura` — canonical URA of the Agent to revoke (typically
///     a device URA `easynet:///r/<realm>/device/<id>`).
///   * `reason` — operator-supplied label, written through to the
///     receipt for audit. `"deregister"` / `"reset"` are common.
///   * `caller_ura` — same fallback chain as
///     `invoke_federation_discover`.
///
/// Returns `Ok(())` on a successful ack from the daemon. Best-effort
/// by contract on the hub side, but this helper still surfaces
/// transport / parse errors so callers can log them honestly.
pub fn invoke_federation_revoke(
    agent_ura: &str,
    reason: &str,
    caller_ura: Option<&str>,
) -> anyhow::Result<()> {
    let socket_path = crate::support::local_daemon_grpc::resolve_socket_path();
    if !crate::support::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let req_args = json!({
        "agent_ura": agent_ura,
        "reason": reason,
    });
    let arg_bytes = serde_json::to_vec(&req_args).context("encode revoke args")?;

    let resolved_caller = caller_ura
        .map(str::to_string)
        .or_else(|| {
            crate::persistence::config::load_credentials()
                .ok()
                .map(|c| crate::ura::device_ura(&c.realm, &c.node_id))
        })
        .unwrap_or_else(|| crate::ura::device_ura("cli", "local"));

    let request =
        ProtoEnvelope::loopback(resolved_caller)?.invoke_request("federation.revoke", arg_bytes)?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation.revoke")?;

    runtime.block_on(async move {
        let channel = crate::support::local_daemon_grpc::connect_channel(
            socket_path.clone(),
            Duration::from_secs(10),
            Duration::from_secs(5),
        )
        .await
        .context("connect to local daemon gRPC endpoint")?;
        let mut client = InvocationClient::new(channel);
        let _ = client.invoke(request).await.map_err(|status| {
            anyhow!(
                "daemon rejected federation.revoke: code={:?} message={}",
                status.code(),
                status.message()
            )
        })?;
        Ok::<_, anyhow::Error>(())
    })
}

/// Generate a fresh `call_id` for the inner envelope payload's
/// DEC-N4 §2.1 correlation field. Format: `cli-<nanos-hex>` —
/// nanoseconds since Unix epoch, hex-encoded, prefixed so log
/// scraping can tell CLI-minted ids apart from daemon-minted
/// ones (`<self>.invoke_remote` initiator path uses a different
/// prefix). Collision space is `2^64` per second of clock
/// resolution; for the CLI's typical hand-driven cadence the
/// risk is negligible.
fn generate_call_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("cli-{nanos:x}")
}

/// Minimal base64 encoder used for the inner envelope payload.
/// Avoids pulling `base64` as a top-level dep just for one
/// call site; the inner envelope is a CLI-internal blob, not a
/// wire-stable string, so a per-call encoder is fine. Matches
/// the standard alphabet so a daemon-side decoder using the
/// `base64` crate would interoperate.
fn base64_engine_encode(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = if chunk.len() > 1 { chunk[1] as u32 } else { 0 };
        let b2 = if chunk.len() > 2 { chunk[2] as u32 } else { 0 };
        let combined = (b0 << 16) | (b1 << 8) | b2;
        out.push(ALPHABET[((combined >> 18) & 0x3F) as usize] as char);
        out.push(ALPHABET[((combined >> 12) & 0x3F) as usize] as char);
        if chunk.len() > 1 {
            out.push(ALPHABET[((combined >> 6) & 0x3F) as usize] as char);
        } else {
            out.push('=');
        }
        if chunk.len() > 2 {
            out.push(ALPHABET[(combined & 0x3F) as usize] as char);
        } else {
            out.push('=');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_node_ura_accepts_canonical_shape() {
        let parsed =
            parse_node_ura("easynet:///r/realm-b/device/laptop-bob").expect("canonical accepted");
        assert_eq!(parsed, "easynet:///r/realm-b/device/laptop-bob");
    }

    #[test]
    fn parse_node_ura_accepts_hub_ura_for_cross_hub_calls() {
        let hub = easynet_axon::ura::hub_ura("peer-realm");
        let parsed = parse_node_ura(&hub).expect("canonical hub URA accepted");
        assert_eq!(parsed, hub);
    }

    #[test]
    fn parse_node_ura_accepts_protocol_hub_identity() {
        let parsed =
            parse_node_ura("easynet:///r/peer-realm/hub").expect("hub identity is canonical");
        assert_eq!(parsed, "easynet:///r/peer-realm/hub");
    }

    #[test]
    fn parse_node_ura_rejects_hub_with_tail() {
        let err = parse_node_ura("easynet:///r/realm/hub/extra").expect_err("hub tail rejected");
        assert!(
            err.to_string()
                .contains("not a canonical Axon Device or Hub URA"),
            "hub identity with tail must not be accepted, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_trims_surrounding_whitespace() {
        let parsed =
            parse_node_ura("  easynet:///r/realm-b/device/n1  \n").expect("whitespace trimmed");
        assert_eq!(parsed, "easynet:///r/realm-b/device/n1");
    }

    #[test]
    fn parse_node_ura_rejects_agent_device_alias_shape() {
        let err = parse_node_ura("easynet:///r/realm-b/agent/n1")
            .expect_err("device alias must be rejected");
        assert!(format!("{err}").contains("agent tail must"));
    }

    #[test]
    fn parse_node_ura_rejects_https_url() {
        let err = parse_node_ura("https://hub.example/r/foo").expect_err("https rejected");
        assert!(
            format!("{err}").contains("not a canonical Axon Device or Hub URA"),
            "error message must cite the canonical-URA requirement, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_rejects_bare_hostname() {
        let err = parse_node_ura("hub.example.com").expect_err("bare hostname rejected");
        assert!(format!("{err}").contains("canonical"));
    }

    #[test]
    fn parse_node_ura_rejects_missing_realm() {
        let err = parse_node_ura("easynet:///r//device/n1").expect_err("empty realm rejected");
        assert!(
            format!("{err}").contains("missing <realm>"),
            "must surface a structural-mismatch error, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_rejects_missing_node_id() {
        let err =
            parse_node_ura("easynet:///r/realm-b/device/").expect_err("empty node id rejected");
        // The SDK ParseError::DeviceMissingTail formats as
        // "device URA requires <device-id> tail" (note: URA, not
        // URA — the SDK ontology calls these URAs everywhere).
        // Test pins that wording so a future rename surfaces here
        // instead of silently swallowing the error condition.
        assert!(
            format!("{err}").contains("device URA requires"),
            "expected SDK DeviceMissingTail wording, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_rejects_extra_path_segments() {
        let err = parse_node_ura("easynet:///r/realm-b/device/n1/ability/x")
            .expect_err("extra segments rejected");
        // The SDK ParseError::DeviceBadShape formats as
        // "device-id must be a single path segment". The test used
        // to assert "device-id must be bare" — an older copy that
        // drifted from the SDK; we pin the live wording here.
        assert!(
            format!("{err}").contains("device-id must be a single path segment"),
            "expected SDK DeviceBadShape wording, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_rejects_real_agent_profile_ura() {
        let err = parse_node_ura("easynet:///r/realm-b/agent/alice.claude")
            .expect_err("hosted agent must not be accepted");
        assert!(format!("{err}").contains("kind=agent"));
    }

    #[test]
    fn parse_node_ura_rejects_wrong_keyword() {
        // The role segment after the realm must be one of Axon's
        // canonical URA roles. A typo is rejected before the URA
        // reaches the daemon.
        let err =
            parse_node_ura("easynet:///r/realm-b/notarole/n1").expect_err("wrong keyword rejected");
        assert!(
            format!("{err}").contains("unknown URA role"),
            "expected SDK UnknownRole wording, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_failure_message_includes_discovery_hint() {
        // PR-N1 user-flow review catch: operators have no
        // zero-config way to discover a peer's canonical URA today
        // (PR-N3 territory). Until PR-N3 ships, the error message
        // tells them where to look — credentials.json, daemon-
        // config.toml's federated_peers table, /etc/easynet/realm-
        // trust.toml's hub entries, and `easynet ability list`
        // (local-realm).
        // Both rejection arms (non-easynet scheme + structural
        // mismatch) MUST cite the discovery hint so a typo'd
        // command surfaces the same operator-actionable next step.
        let err_scheme = parse_node_ura("not-an-easynet-ura").expect_err("rejected");
        let msg_scheme = format!("{err_scheme}");
        assert!(
            msg_scheme.contains("credentials.json"),
            "scheme-arm error must cite credentials.json discovery path; got: {msg_scheme}"
        );
        assert!(
            msg_scheme.contains("daemon-config.toml"),
            "scheme-arm error must cite daemon-config.toml discovery path; got: {msg_scheme}"
        );
        assert!(
            msg_scheme.contains("realm-trust.toml"),
            "scheme-arm error must cite realm-trust.toml discovery path; got: {msg_scheme}"
        );
        assert!(
            msg_scheme.contains("easynet ability list"),
            "scheme-arm error must cite easynet ability list; got: {msg_scheme}"
        );

        // Structural-failure: empty realm tail. Use a clearly
        // malformed input to exercise the structural-arm error
        // path without depending on any retired URA aliases.
        let err_struct = parse_node_ura("easynet:///r//device/n1").expect_err("rejected");
        let msg_struct = format!("{err_struct}");
        assert!(
            msg_struct.contains("credentials.json") && msg_struct.contains("daemon-config.toml"),
            "structural-arm error must cite the same discovery hint; got: {msg_struct}"
        );
    }

    #[test]
    fn forward_ability_ura_rejects_owner_mismatch() {
        let err = validate_forward_ability_owner(
            "easynet:///r/acme/ability/device.other.fs.read",
            "easynet:///r/acme/device/dev-1",
        )
        .expect_err("owner mismatch must fail");
        let msg = err.to_string();
        assert!(
            msg.contains("not owned by target"),
            "owner mismatch must be explicit: {msg}"
        );
    }

    #[test]
    fn forward_ability_ura_accepts_matching_device_owner() {
        validate_forward_ability_owner(
            "easynet:///r/acme/ability/device.dev-1.fs.read",
            "easynet:///r/acme/device/dev-1",
        )
        .expect("matching device-owned ability URA is accepted");
    }

    #[test]
    fn target_owned_ability_ura_projects_device_selector_to_owner_ura() {
        assert_eq!(
            TargetOwnedAbilityUra::from_selector("easynet:///r/acme/device/dev-1", "fs.read",)
                .expect("device ability URA")
                .as_str(),
            "easynet:///r/acme/ability/device.dev-1.fs.read"
        );
    }

    #[test]
    fn target_owned_ability_ura_projects_device_meta_list_resources() {
        assert_eq!(
            TargetOwnedAbilityUra::from_selector(
                "easynet:///r/acme/device/02507271-6034-40df-959c-f90bc930d676",
                "meta.list_resources",
            )
            .expect("device meta.list_resources ability URA")
            .as_str(),
            "easynet:///r/acme/ability/device.02507271-6034-40df-959c-f90bc930d676.meta.list_resources"
        );
    }

    #[test]
    fn target_owned_ability_ura_accepts_prebuilt_canonical_ura() {
        assert_eq!(
            TargetOwnedAbilityUra::from_ability_ura(
                "easynet:///r/acme/device/dev-1",
                "easynet:///r/acme/ability/device.dev-1.fs.read",
            )
            .expect("prebuilt ability URA")
            .as_str(),
            "easynet:///r/acme/ability/device.dev-1.fs.read"
        );
    }

    #[test]
    fn target_owned_ability_ura_rejects_wrong_owner() {
        let err = TargetOwnedAbilityUra::from_ability_ura(
            "easynet:///r/acme/device/dev-1",
            "easynet:///r/acme/ability/device.other.fs.read",
        )
        .expect_err("wrong owner must fail");
        assert!(
            err.to_string().contains("not owned by target"),
            "owner mismatch must be explicit: {err}"
        );
    }

    #[test]
    fn target_owned_ability_ura_projects_hub_selector_to_owner_ura() {
        assert_eq!(
            TargetOwnedAbilityUra::from_selector(
                &easynet_axon::ura::hub_ura("acme"),
                "hub.federation.resolve",
            )
            .expect("hub ability URA")
            .as_str(),
            "easynet:///r/acme/ability/hub.federation.resolve"
        );
    }

    #[test]
    fn target_owned_ability_ura_projects_protocol_hub_identity() {
        assert_eq!(
            TargetOwnedAbilityUra::from_selector(
                "easynet:///r/acme/hub",
                "hub.federation.resolve",
            )
            .expect("hub identity target is canonical")
            .as_str(),
            "easynet:///r/acme/ability/hub.federation.resolve"
        );
    }

    #[test]
    fn target_owned_ability_ura_rejects_hub_with_tail() {
        let err = TargetOwnedAbilityUra::from_selector(
            "easynet:///r/acme/hub/extra",
            "hub.federation.resolve",
        )
        .expect_err("hub target with tail must be invalid");
        assert!(
            err.to_string().contains("invalid target URA"),
            "hub target with tail must fail through Axon parser, got: {err}"
        );
    }

    #[test]
    fn decode_forward_invoke_response_decodes_sdk_base64_result_bytes() {
        let envelope = easynet_axon::ForwardInvokeResponse {
            result_bytes: br#"{"content":"hello"}"#.to_vec(),
            correlation_call_id: "cli-call-1".to_string(),
        };
        let body = easynet_axon::pb::axon::v1::InvokeResponse {
            result: serde_json::to_vec(&envelope).expect("encode ForwardInvokeResponse"),
            result_content_type: "application/json".to_string(),
            ..Default::default()
        };

        let value = decode_forward_invoke_response_value(&body).expect("decode response");

        assert_eq!(value["content"], "hello");
    }

    #[test]
    fn decode_forward_invoke_response_no_longer_emits_delivery_accepted_shim() {
        let envelope = easynet_axon::ForwardInvokeResponse {
            result_bytes: Vec::new(),
            correlation_call_id: "cli-call-empty".to_string(),
        };
        let body = easynet_axon::pb::axon::v1::InvokeResponse {
            result: serde_json::to_vec(&envelope).expect("encode ForwardInvokeResponse"),
            result_content_type: "application/json".to_string(),
            ..Default::default()
        };

        let value = decode_forward_invoke_response_value(&body).expect("decode response");

        assert_eq!(
            value,
            Value::Null,
            "empty ability payload is a real empty result, not delivery=accepted"
        );
    }

    #[test]
    fn decode_forward_invoke_response_hex_encodes_non_json_payload() {
        let envelope = easynet_axon::ForwardInvokeResponse {
            result_bytes: vec![0xde, 0xad, 0xbe, 0xef],
            correlation_call_id: "cli-call-bin".to_string(),
        };
        let body = easynet_axon::pb::axon::v1::InvokeResponse {
            result: serde_json::to_vec(&envelope).expect("encode ForwardInvokeResponse"),
            result_content_type: "application/json".to_string(),
            ..Default::default()
        };

        let value = decode_forward_invoke_response_value(&body).expect("decode response");

        assert_eq!(value["result_bytes_len"], 4);
        assert_eq!(value["result_bytes_hex"], "deadbeef");
    }

    #[test]
    fn base64_encode_round_trip_against_known_vectors() {
        // RFC 4648 §10 test vectors. Pin the encoder so a regression
        // here doesn't silently break the inner envelope shape.
        assert_eq!(base64_engine_encode(b""), "");
        assert_eq!(base64_engine_encode(b"f"), "Zg==");
        assert_eq!(base64_engine_encode(b"fo"), "Zm8=");
        assert_eq!(base64_engine_encode(b"foo"), "Zm9v");
        assert_eq!(base64_engine_encode(b"foob"), "Zm9vYg==");
        assert_eq!(base64_engine_encode(b"fooba"), "Zm9vYmE=");
        assert_eq!(base64_engine_encode(b"foobar"), "Zm9vYmFy");
    }
}
