// Code generated by provider_routes/generate_principal_routes.py; DO NOT EDIT.

pub(crate) const PRINCIPAL_LIFECYCLE_PROFILE: &str = "principal_lifecycle";
pub(crate) const PRINCIPAL_ROUTE_MANIFEST_SHA256: &str =
    "477935b9f94457f164070a6e75d56fbc13fb249a2b2a274b3807bfb8f9dcfb73";
pub(crate) const PRINCIPAL_ABILITY_CREATE: &str = "principal.lifecycle.create";
pub(crate) const PRINCIPAL_ABILITY_BIND_FIRST_KEY: &str = "principal.lifecycle.bind_first_key";
pub(crate) const PRINCIPAL_ABILITY_ADD_KEY: &str = "principal.lifecycle.add_key";
pub(crate) const PRINCIPAL_ABILITY_ROTATE_KEY: &str = "principal.lifecycle.rotate_key";
pub(crate) const PRINCIPAL_ABILITY_REVOKE_KEY: &str = "principal.lifecycle.revoke_key";
pub(crate) const PRINCIPAL_ABILITY_CONFIGURE_RECOVERY: &str =
    "principal.lifecycle.configure_recovery";
pub(crate) const PRINCIPAL_ABILITY_RECOVER: &str = "principal.lifecycle.recover";
pub(crate) const PRINCIPAL_ABILITY_SUSPEND: &str = "principal.lifecycle.suspend";
pub(crate) const PRINCIPAL_ABILITY_REACTIVATE: &str = "principal.lifecycle.reactivate";
pub(crate) const PRINCIPAL_ABILITY_DELETE: &str = "principal.lifecycle.delete";
pub(crate) const PRINCIPAL_ABILITY_ISSUE_ENROLLMENT: &str = "principal.lifecycle.issue_enrollment";
pub(crate) const PRINCIPAL_ABILITY_REVOKE_ENROLLMENT: &str =
    "principal.lifecycle.revoke_enrollment";
pub(crate) const PRINCIPAL_ABILITY_ISSUE_GRANT: &str = "principal.lifecycle.issue_grant";
pub(crate) const PRINCIPAL_ABILITY_REVOKE_GRANT: &str = "principal.lifecycle.revoke_grant";
pub(crate) const PRINCIPAL_ABILITY_GET: &str = "principal.lifecycle.get";
