"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
EasyNet Axon for AgentNet
=========================

File: core/proto/axon/v1/invoke.proto
Description: Source-of-truth shared Axon protocol types, envelopes, enums, and resource contracts.

Protocol Responsibility:
- Defines the foundational wire-level types reused by control, invocation, interop, identity, stream, and federation services.
- Preserves shared resource URA binding, content-envelope, and terminal-state semantics across the protocol.

Implementation Approach:
- Keeps common enums and messages in one schema so service protos compose on a stable base contract.
- Documents protocol guarantees and URA routing conventions close to the shared type definitions.

Usage Contract:
- Changes here have broad compatibility impact and must remain wire-safe for generated clients.
- Regenerate dependent language artifacts after updating shared types or enums.

Architectural Position:
- Base protocol contract layer for the entire Axon wire surface.

Author: Silan.Hu
Email: silan.hu@u.nus.edu
Copyright (c) 2026-2027 easynet. All rights reserved.
"""

from . import types_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class InvokeRequest(google.protobuf.message.Message):
    """─── Invoke ─────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ENVELOPE_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    TIMEOUT_SECONDS_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    PAYLOAD_REF_FIELD_NUMBER: builtins.int
    CONTENT_ENVELOPE_FIELD_NUMBER: builtins.int
    arguments: builtins.bytes
    """serialized payload (protobuf, JSON, etc.); prefer payload_ref once the encoded body exceeds ~1 MiB"""
    content_type: builtins.str
    """shorthand MIME; use content_envelope for full negotiation"""
    timeout_seconds: builtins.int
    """per-call timeout (capped by envelope.deadline)"""
    @property
    def envelope(self) -> types_pb2.Envelope: ...
    @property
    def target(self) -> types_pb2.InvocationTarget:
        """descriptor-bound ability target"""

    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """passthrough metadata to executor"""

    @property
    def payload_ref(self) -> types_pb2.PayloadRef:
        """large/multimedia payload reference (recommended for payloads > ~1 MiB; when set, callers SHOULD leave arguments empty)"""

    @property
    def content_envelope(self) -> types_pb2.ContentEnvelope:
        """full content contract (encoding + schema + encryption)"""

    def __init__(
        self,
        *,
        envelope: types_pb2.Envelope | None = ...,
        target: types_pb2.InvocationTarget | None = ...,
        arguments: builtins.bytes = ...,
        content_type: builtins.str = ...,
        timeout_seconds: builtins.int = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        payload_ref: types_pb2.PayloadRef | None = ...,
        content_envelope: types_pb2.ContentEnvelope | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["content_envelope", b"content_envelope", "envelope", b"envelope", "payload_ref", b"payload_ref", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments", "content_envelope", b"content_envelope", "content_type", b"content_type", "envelope", b"envelope", "metadata", b"metadata", "payload_ref", b"payload_ref", "target", b"target", "timeout_seconds", b"timeout_seconds"]) -> None: ...

global___InvokeRequest = InvokeRequest

@typing.final
class InvokeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    RESULT_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    ELAPSED_MS_FIELD_NUMBER: builtins.int
    RESULT_REF_FIELD_NUMBER: builtins.int
    ADMISSION_RECEIPT_FIELD_NUMBER: builtins.int
    TERMINAL_RECEIPT_FIELD_NUMBER: builtins.int
    PROOF_ERROR_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    state: types_pb2.InvocationState.ValueType
    result: builtins.bytes
    """serialized result"""
    result_content_type: builtins.str
    elapsed_ms: builtins.int
    @property
    def header(self) -> types_pb2.ResponseHeader: ...
    @property
    def result_ref(self) -> types_pb2.PayloadRef:
        """large/multimedia result reference"""

    @property
    def admission_receipt(self) -> global___InvocationReceipt:
        """Signed admission receipt (RFC 001 §5.3).

        Emitted only on paths that ran the §5.2 admission pipeline — i.e.
        when the incoming envelope carried a caller_signature. The
        receipt's canonical bytes are produced per RFC 001 §4.3 and the
        callee_signature binds them to the callee identity configured at
        server startup. A verifier with only the receipt and the
        callee's public key (no runtime contact) can re-compute the
        canonical bytes and check the signature independently.

        Absent when no signed admission receipt exists. Absent on
        admission-reject paths (the Error message itself is the
        wire-visible outcome).
        """

    @property
    def terminal_receipt(self) -> global___InvocationReceipt:
        """Signed terminal checkpoint for the execution outcome. Present on unary
        responses together with the signed admission checkpoint. The two receipts
        bind one lifecycle but are not necessarily adjacent: legal intermediate
        receipts include dispatched, running, progress, and child events. Consumers
        may validate checkpoint identity, immutable bindings, states, and monotonic
        indexes from this pair. Claiming full hash-chain validation requires every
        intermediate receipt or a separately verifiable chain proof.
        """

    @property
    def proof_error(self) -> types_pb2.Error:
        """Proof-plane failure for signed terminal receipt construction. When present,
        the public terminal state MUST be Failed and `error` MUST carry the same
        fail-closed proof error; runtimes must not expose Completed without a
        terminal receipt on signed paths.
        """

    @property
    def error(self) -> types_pb2.Error: ...
    def __init__(
        self,
        *,
        header: types_pb2.ResponseHeader | None = ...,
        state: types_pb2.InvocationState.ValueType = ...,
        result: builtins.bytes = ...,
        result_content_type: builtins.str = ...,
        elapsed_ms: builtins.int = ...,
        result_ref: types_pb2.PayloadRef | None = ...,
        admission_receipt: global___InvocationReceipt | None = ...,
        terminal_receipt: global___InvocationReceipt | None = ...,
        proof_error: types_pb2.Error | None = ...,
        error: types_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["admission_receipt", b"admission_receipt", "error", b"error", "header", b"header", "proof_error", b"proof_error", "result_ref", b"result_ref", "terminal_receipt", b"terminal_receipt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["admission_receipt", b"admission_receipt", "elapsed_ms", b"elapsed_ms", "error", b"error", "header", b"header", "proof_error", b"proof_error", "result", b"result", "result_content_type", b"result_content_type", "result_ref", b"result_ref", "state", b"state", "terminal_receipt", b"terminal_receipt"]) -> None: ...

global___InvokeResponse = InvokeResponse

@typing.final
class InvocationEvent(google.protobuf.message.Message):
    """─── Invocation Event ──────────────────────────────────
    Runtime event projection used by gateway observers and local SDK runtimes.

    Event types (see document/concepts/INVOCATION_STATE_MACHINE.md §2):
      "accepted" | "admitted" | "dispatched" | "running"
      "progress" | "message_received" | "message_consumed"
      "child_spawned" | "child_terminal"
      "completed" | "failed" | "timed_out" | "cancelled"

    The sequence field MUST be monotonically increasing per invocation_id
    and is the resumption offset for local event streams.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_ID_FIELD_NUMBER: builtins.int
    INVOCATION_ID_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    RESULT_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    ELAPSED_MS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    TIMESTAMP_UNIX_MS_FIELD_NUMBER: builtins.int
    RESULT_REF_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    PAYLOAD_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    CAUSAL_CONTEXT_FIELD_NUMBER: builtins.int
    event_id: builtins.str
    invocation_id: builtins.str
    event_type: builtins.str
    """see enum of values above"""
    state: types_pb2.InvocationState.ValueType
    reason: builtins.str
    """scheduling / failure reason"""
    result: builtins.bytes
    """populated on terminal state"""
    result_content_type: builtins.str
    elapsed_ms: builtins.int
    timestamp_unix_ms: builtins.int
    sequence: builtins.int
    """monotonic per invocation; resumption offset"""
    payload: builtins.bytes
    """For "progress" chunks: payload is the delta chunk.
    For "message_received" / "message_consumed": payload is the message body.
    For "child_spawned" / "child_terminal": payload is the child invocation_id (utf-8).
    """
    payload_content_type: builtins.str
    @property
    def error(self) -> types_pb2.Error: ...
    @property
    def result_ref(self) -> types_pb2.PayloadRef:
        """large/multimedia result reference"""

    @property
    def causal_context(self) -> types_pb2.CausalContext:
        """Causal binding copied from Envelope.causal_context at creation. This is the
        current invocation-causality model; the deleted Envelope.parent_invocation_id
        field is not projected here.
        """

    def __init__(
        self,
        *,
        event_id: builtins.str = ...,
        invocation_id: builtins.str = ...,
        event_type: builtins.str = ...,
        state: types_pb2.InvocationState.ValueType = ...,
        reason: builtins.str = ...,
        result: builtins.bytes = ...,
        result_content_type: builtins.str = ...,
        elapsed_ms: builtins.int = ...,
        error: types_pb2.Error | None = ...,
        timestamp_unix_ms: builtins.int = ...,
        result_ref: types_pb2.PayloadRef | None = ...,
        sequence: builtins.int = ...,
        payload: builtins.bytes = ...,
        payload_content_type: builtins.str = ...,
        causal_context: types_pb2.CausalContext | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["causal_context", b"causal_context", "error", b"error", "result_ref", b"result_ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["causal_context", b"causal_context", "elapsed_ms", b"elapsed_ms", "error", b"error", "event_id", b"event_id", "event_type", b"event_type", "invocation_id", b"invocation_id", "payload", b"payload", "payload_content_type", b"payload_content_type", "reason", b"reason", "result", b"result", "result_content_type", b"result_content_type", "result_ref", b"result_ref", "sequence", b"sequence", "state", b"state", "timestamp_unix_ms", b"timestamp_unix_ms"]) -> None: ...

global___InvocationEvent = InvocationEvent

@typing.final
class InvokeServerStreamRequest(google.protobuf.message.Message):
    """─── Server-Stream Invocation ─────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ENVELOPE_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    TIMEOUT_SECONDS_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    PAYLOAD_REF_FIELD_NUMBER: builtins.int
    CONTENT_ENVELOPE_FIELD_NUMBER: builtins.int
    arguments: builtins.bytes
    content_type: builtins.str
    timeout_seconds: builtins.int
    @property
    def envelope(self) -> types_pb2.Envelope: ...
    @property
    def target(self) -> types_pb2.InvocationTarget: ...
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def payload_ref(self) -> types_pb2.PayloadRef:
        """large/multimedia payload reference"""

    @property
    def content_envelope(self) -> types_pb2.ContentEnvelope: ...
    def __init__(
        self,
        *,
        envelope: types_pb2.Envelope | None = ...,
        target: types_pb2.InvocationTarget | None = ...,
        arguments: builtins.bytes = ...,
        content_type: builtins.str = ...,
        timeout_seconds: builtins.int = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        payload_ref: types_pb2.PayloadRef | None = ...,
        content_envelope: types_pb2.ContentEnvelope | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["content_envelope", b"content_envelope", "envelope", b"envelope", "payload_ref", b"payload_ref", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments", "content_envelope", b"content_envelope", "content_type", b"content_type", "envelope", b"envelope", "metadata", b"metadata", "payload_ref", b"payload_ref", "target", b"target", "timeout_seconds", b"timeout_seconds"]) -> None: ...

global___InvokeServerStreamRequest = InvokeServerStreamRequest

@typing.final
class InvokeStreamChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    INVOCATION_ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    TERMINAL_FIELD_NUMBER: builtins.int
    ELAPSED_MS_FIELD_NUMBER: builtins.int
    ADMISSION_RECEIPT_FIELD_NUMBER: builtins.int
    TERMINAL_RECEIPT_FIELD_NUMBER: builtins.int
    PROOF_ERROR_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    invocation_id: builtins.str
    state: types_pb2.InvocationState.ValueType
    """RUNNING while streaming, terminal on last chunk"""
    payload: builtins.bytes
    """chunk data"""
    content_type: builtins.str
    sequence: builtins.int
    """0-based chunk sequence number"""
    terminal: builtins.bool
    """true on the last chunk"""
    elapsed_ms: builtins.int
    @property
    def header(self) -> types_pb2.ResponseHeader: ...
    @property
    def admission_receipt(self) -> global___InvocationReceipt:
        """Signed admission receipt for signed server-stream invocations.

        Present on the first emitted chunk when the request envelope passed signed
        admission. If the stream terminates before any payload chunk is emitted, the
        terminal chunk carries both admission_receipt and terminal_receipt.
        """

    @property
    def terminal_receipt(self) -> global___InvocationReceipt:
        """Signed terminal receipt for signed server-stream invocations.

        Present exactly on the terminal chunk when the request envelope passed
        signed admission. The receipt output_hash binds the deterministic stream
        transcript digest accumulated from every emitted payload chunk.
        """

    @property
    def proof_error(self) -> types_pb2.Error:
        """Proof-plane failure for signed terminal receipt construction. This remains
        separate from `error`, which belongs to execution/session outcome.
        """

    @property
    def error(self) -> types_pb2.Error: ...
    def __init__(
        self,
        *,
        header: types_pb2.ResponseHeader | None = ...,
        invocation_id: builtins.str = ...,
        state: types_pb2.InvocationState.ValueType = ...,
        payload: builtins.bytes = ...,
        content_type: builtins.str = ...,
        sequence: builtins.int = ...,
        terminal: builtins.bool = ...,
        elapsed_ms: builtins.int = ...,
        admission_receipt: global___InvocationReceipt | None = ...,
        terminal_receipt: global___InvocationReceipt | None = ...,
        proof_error: types_pb2.Error | None = ...,
        error: types_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["admission_receipt", b"admission_receipt", "error", b"error", "header", b"header", "proof_error", b"proof_error", "terminal_receipt", b"terminal_receipt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["admission_receipt", b"admission_receipt", "content_type", b"content_type", "elapsed_ms", b"elapsed_ms", "error", b"error", "header", b"header", "invocation_id", b"invocation_id", "payload", b"payload", "proof_error", b"proof_error", "sequence", b"sequence", "state", b"state", "terminal", b"terminal", "terminal_receipt", b"terminal_receipt"]) -> None: ...

global___InvokeStreamChunk = InvokeStreamChunk

@typing.final
class InvokeBidiUp(google.protobuf.message.Message):
    """─── Bidirectional Invocation (P5-rewrite-15) ─────────────────

    `InvokeBidi(stream InvokeBidiUp) returns (stream InvokeBidiDown)`
    is the realtime multimodal data plane. Distinct RPC from
    InvokeStream by design (strict-separation directive — server-
    stream's semantics MUST NOT be silently upgraded).

    Frame chain security (binding pin §A16):
      - frame 0 up: EnvelopeOpen, mac = Ed25519 signature over the
        same descriptor-bound canonical bytes the unary signed path uses
        (AXIOM §"Why these seven parameters"). One admission gate
        run per session at frame 0.
      - frame 0 down: InvocationReceipt (admission accept). No
        separate "Accept" message — receipt semantics ARE the
        accept signal.
      - frame N≥1 (both directions): mac = HMAC-SHA256-32(
            key, sequence_be_8 || prev_mac || canonical_payload )
        where canonical_payload = deterministic protobuf encoding
        of the same frame with the `mac` field zeroed out (so the
        mac self-cover does not recurse).
      - key derivation:
          up_key   = HKDF-SHA256(salt="easynet-bidi-mac:v1",
                                 ikm = envelope_signature || nonce,
                                 info = "caller-to-callee", L = 32)
          down_key = HKDF-SHA256(... info = "callee-to-caller", ...)
      - sequence: monotonic from 0; v1 receivers MUST reject any
        incoming.sequence != last_seen + 1 with broken-chain error.
      - replay window: receivers MUST drop frames whose sequence
        re-uses a previously-seen value within the session.
      - direction independence: up and down sequences are
        independent counters, each starts at 0 and rises on its
        own track. Cross-direction interleaving is allowed.

    Closure: callee emits a terminal InvocationReceipt as the last
    down frame (state ∈ {Completed, Failed, Cancelled, TimedOut}).
    Caller signals graceful close-up via BidiControl.eof = true on
    the up stream; abrupt close (TCP/QUIC reset, ctx cancel) is
    non-graceful and produces a Failed terminal receipt at the
    callee with reason="bidi_chain_broken" or
    "bidi_caller_disconnect".
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    MAC_FIELD_NUMBER: builtins.int
    ENVELOPE_OPEN_FIELD_NUMBER: builtins.int
    BINARY_CHUNK_FIELD_NUMBER: builtins.int
    CONTROL_FIELD_NUMBER: builtins.int
    DISPATCH_RESULT_FIELD_NUMBER: builtins.int
    REVERSE_DISPATCH_CALL_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """Monotonic 0-based sequence per up-direction."""
    mac: builtins.bytes
    """Frame integrity tag. Frame 0: Ed25519(64 bytes). Frame N≥1:
    HMAC-SHA256(32 bytes). Length signals which mode is in use.
    """
    @property
    def envelope_open(self) -> global___EnvelopeOpen:
        """sequence MUST be 0"""

    @property
    def binary_chunk(self) -> global___BinaryChunk: ...
    @property
    def control(self) -> global___BidiControl: ...
    @property
    def dispatch_result(self) -> global___DispatchResult:
        """Carrier-unification (dispatch-frame mini-RFC, T2.1): session
        business frames travel as canonical protocol shapes, not
        JSON-in-BinaryChunk.
        device → authority
        """

    @property
    def reverse_dispatch_call(self) -> global___ReverseDispatchCall:
        """device → authority"""

    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
        mac: builtins.bytes = ...,
        envelope_open: global___EnvelopeOpen | None = ...,
        binary_chunk: global___BinaryChunk | None = ...,
        control: global___BidiControl | None = ...,
        dispatch_result: global___DispatchResult | None = ...,
        reverse_dispatch_call: global___ReverseDispatchCall | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["binary_chunk", b"binary_chunk", "control", b"control", "dispatch_result", b"dispatch_result", "envelope_open", b"envelope_open", "payload", b"payload", "reverse_dispatch_call", b"reverse_dispatch_call"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["binary_chunk", b"binary_chunk", "control", b"control", "dispatch_result", b"dispatch_result", "envelope_open", b"envelope_open", "mac", b"mac", "payload", b"payload", "reverse_dispatch_call", b"reverse_dispatch_call", "sequence", b"sequence"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["envelope_open", "binary_chunk", "control", "dispatch_result", "reverse_dispatch_call"] | None: ...

global___InvokeBidiUp = InvokeBidiUp

@typing.final
class InvokeBidiDown(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    MAC_FIELD_NUMBER: builtins.int
    RECEIPT_FIELD_NUMBER: builtins.int
    BINARY_CHUNK_FIELD_NUMBER: builtins.int
    CONTROL_FIELD_NUMBER: builtins.int
    DISPATCH_CALL_FIELD_NUMBER: builtins.int
    REVERSE_DISPATCH_RESULT_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    mac: builtins.bytes
    @property
    def receipt(self) -> global___InvocationReceipt:
        """Frame 0 down = admission InvocationReceipt. Subsequent
        receipt frames mark interim or terminal state. There is
        no separate Accept message — receipt IS the accept.
        """

    @property
    def binary_chunk(self) -> global___BinaryChunk: ...
    @property
    def control(self) -> global___BidiControl: ...
    @property
    def dispatch_call(self) -> global___DispatchCall:
        """Carrier-unification (T2.1), mirror of the up-direction pair.
        authority → device
        """

    @property
    def reverse_dispatch_result(self) -> global___ReverseDispatchResult:
        """authority → device"""

    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
        mac: builtins.bytes = ...,
        receipt: global___InvocationReceipt | None = ...,
        binary_chunk: global___BinaryChunk | None = ...,
        control: global___BidiControl | None = ...,
        dispatch_call: global___DispatchCall | None = ...,
        reverse_dispatch_result: global___ReverseDispatchResult | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["binary_chunk", b"binary_chunk", "control", b"control", "dispatch_call", b"dispatch_call", "payload", b"payload", "receipt", b"receipt", "reverse_dispatch_result", b"reverse_dispatch_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["binary_chunk", b"binary_chunk", "control", b"control", "dispatch_call", b"dispatch_call", "mac", b"mac", "payload", b"payload", "receipt", b"receipt", "reverse_dispatch_result", b"reverse_dispatch_result", "sequence", b"sequence"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["receipt", "binary_chunk", "control", "dispatch_call", "reverse_dispatch_result"] | None: ...

global___InvokeBidiDown = InvokeBidiDown

@typing.final
class EnvelopeOpen(google.protobuf.message.Message):
    """EnvelopeOpen carries the AXIOM seven-tuple identity / binding
    (Envelope) plus session-shape metadata (target, args, streams).
    Frame 0 up MUST carry exactly this payload variant.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ENVELOPE_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    INITIAL_ARGS_FIELD_NUMBER: builtins.int
    ARGS_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    STREAMS_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    CONTENT_ENVELOPE_FIELD_NUMBER: builtins.int
    SESSION_EXT_FIELD_NUMBER: builtins.int
    initial_args: builtins.bytes
    """Canonical-encoded ability arguments — the byte string whose
    SHA-256 produces args_digest for inclusion in
    descriptor-bound canonical invocation bytes (AXIOM param 7, "args"). Encoding
    is the ability's declared input encoding (JCS-minified JSON
    for JSON-shaped abilities, deterministic prost bytes for
    proto-shaped, raw bytes for binary-shaped). The wire field
    is bytes; receivers feed it directly into SHA-256 and into
    the ability handler. NOT JSON-encoded by the bridge. NOT
    base64-encoded on the wire.
    """
    args_content_type: builtins.str
    """Content-type label for `initial_args`. Free-form; receivers
    may inspect to choose decoder (e.g. "application/json",
    "application/x-protobuf", "application/octet-stream").
    """
    @property
    def envelope(self) -> types_pb2.Envelope: ...
    @property
    def target(self) -> types_pb2.InvocationTarget: ...
    @property
    def streams(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StreamDescriptor]:
        """Multi-stream descriptors. BinaryChunk frames carry a
        stream_id selecting one of these. A session may multiplex
        e.g. (audio/opus, video/h264, text/pty) in a single
        InvokeBidi.
        """

    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Non-axiom passthrough metadata — same role as
        `InvokeRequest.metadata` and `InvokeServerStreamRequest.metadata`
        on the unary / server-stream RPCs. RFC 001 §4.1.2 forbids
        anything in this map from entering the canonical signing
        bytes; downstream consumers may use it for non-authoritative
        cross-cutting concerns such as tracing. Authority is established by
        canonical admission providers and MUST NOT be inferred from this map.
        """

    @property
    def content_envelope(self) -> types_pb2.ContentEnvelope:
        """Full content contract for `initial_args`. Unary and server-stream
        requests already carry this field; bidi frame-0 needs the same
        contract so encrypted or schema-bound session opens do not degrade
        into opaque bytes when routed through InvokeBidi / invoke_remote.
        """

    @property
    def session_ext(self) -> global___SessionOpenExt:
        """Carrier-unification frame-0 extension (T1.1 contract-skew
        observability + T1.2 claimant fingerprint + T2.1 encoding
        negotiation ride the same field). Canonical sessions require a
        non-zero supported version; receivers reject absent/zero values.
        """

    def __init__(
        self,
        *,
        envelope: types_pb2.Envelope | None = ...,
        target: types_pb2.InvocationTarget | None = ...,
        initial_args: builtins.bytes = ...,
        args_content_type: builtins.str = ...,
        streams: collections.abc.Iterable[global___StreamDescriptor] | None = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        content_envelope: types_pb2.ContentEnvelope | None = ...,
        session_ext: global___SessionOpenExt | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["content_envelope", b"content_envelope", "envelope", b"envelope", "session_ext", b"session_ext", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["args_content_type", b"args_content_type", "content_envelope", b"content_envelope", "envelope", b"envelope", "initial_args", b"initial_args", "metadata", b"metadata", "session_ext", b"session_ext", "streams", b"streams", "target", b"target"]) -> None: ...

global___EnvelopeOpen = EnvelopeOpen

@typing.final
class StreamDescriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    CODEC_PARAMS_FIELD_NUMBER: builtins.int
    ORDERING_FIELD_NUMBER: builtins.int
    stream_id: builtins.int
    """referenced by BinaryChunk.stream_id"""
    content_type: builtins.str
    """"audio/opus", "video/h264", "text/pty" """
    codec_params: builtins.str
    """free-form: "sample_rate=48000,bitrate=64000" """
    ordering: builtins.str
    """v1: "STRICT" (reliable ordered, sequence == last_seen + 1).
    PTY uses STRICT unconditionally. A future v2 amendment will
    introduce "LOSS_TOLERANT" for media; v1 receivers MUST
    reject any envelope advertising a non-STRICT ordering.
    """
    def __init__(
        self,
        *,
        stream_id: builtins.int = ...,
        content_type: builtins.str = ...,
        codec_params: builtins.str = ...,
        ordering: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["codec_params", b"codec_params", "content_type", b"content_type", "ordering", b"ordering", "stream_id", b"stream_id"]) -> None: ...

global___StreamDescriptor = StreamDescriptor

@typing.final
class BinaryChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    PTS_FIELD_NUMBER: builtins.int
    stream_id: builtins.int
    """References a StreamDescriptor in EnvelopeOpen.streams. 0 is
    legal only when there is exactly one descriptor (single-modal
    sessions); otherwise must match a declared stream_id.
    """
    data: builtins.bytes
    """Raw payload bytes for this chunk. Codec / framing / container
    are entirely defined by the StreamDescriptor.content_type and
    codec_params; the bridge is byte-blind here.
    """
    pts: builtins.int
    """Optional presentation timestamp in microseconds since the
    session reference clock established at EnvelopeOpen. Required
    for media (audio/video lip-sync); optional for PTY (which is
    intrinsically time-ordered by sequence).
    """
    def __init__(
        self,
        *,
        stream_id: builtins.int = ...,
        data: builtins.bytes = ...,
        pts: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "pts", b"pts", "stream_id", b"stream_id"]) -> None: ...

global___BinaryChunk = BinaryChunk

@typing.final
class BidiControl(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PTY_RESIZE_FIELD_NUMBER: builtins.int
    PTY_SIGNAL_FIELD_NUMBER: builtins.int
    MEDIA_PTS_FIELD_NUMBER: builtins.int
    EOF_FIELD_NUMBER: builtins.int
    SESSION_ESTABLISHED_FIELD_NUMBER: builtins.int
    eof: builtins.bool
    """Graceful close-up signal from caller (up stream) or callee
    (down stream). Receiver acknowledges by emitting the
    terminal receipt (down) or closing the gRPC stream (up).
    """
    @property
    def pty_resize(self) -> global___PtyResize: ...
    @property
    def pty_signal(self) -> global___PtySignal: ...
    @property
    def media_pts(self) -> global___MediaTimestamp: ...
    @property
    def session_established(self) -> global___BidiSessionEstablished:
        """Transport/session negotiation acknowledgement. This is control-plane
        state, not an Invocation admission fact, and therefore MUST NOT be
        encoded inside an InvocationReceipt.
        """

    def __init__(
        self,
        *,
        pty_resize: global___PtyResize | None = ...,
        pty_signal: global___PtySignal | None = ...,
        media_pts: global___MediaTimestamp | None = ...,
        eof: builtins.bool = ...,
        session_established: global___BidiSessionEstablished | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["control", b"control", "eof", b"eof", "media_pts", b"media_pts", "pty_resize", b"pty_resize", "pty_signal", b"pty_signal", "session_established", b"session_established"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["control", b"control", "eof", b"eof", "media_pts", b"media_pts", "pty_resize", b"pty_resize", "pty_signal", b"pty_signal", "session_established", b"session_established"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["control", b"control"]) -> typing.Literal["pty_resize", "pty_signal", "media_pts", "eof", "session_established"] | None: ...

global___BidiControl = BidiControl

@typing.final
class BidiSessionEstablished(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_VERSION_FIELD_NUMBER: builtins.int
    DISPATCH_ENCODING_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    DISPLACED_PRIOR_FIELD_NUMBER: builtins.int
    contract_version: builtins.int
    dispatch_encoding: builtins.str
    session_id: builtins.int
    displaced_prior: builtins.bool
    def __init__(
        self,
        *,
        contract_version: builtins.int = ...,
        dispatch_encoding: builtins.str = ...,
        session_id: builtins.int = ...,
        displaced_prior: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_version", b"contract_version", "dispatch_encoding", b"dispatch_encoding", "displaced_prior", b"displaced_prior", "session_id", b"session_id"]) -> None: ...

global___BidiSessionEstablished = BidiSessionEstablished

@typing.final
class PtyResize(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLS_FIELD_NUMBER: builtins.int
    ROWS_FIELD_NUMBER: builtins.int
    cols: builtins.int
    rows: builtins.int
    def __init__(
        self,
        *,
        cols: builtins.int = ...,
        rows: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cols", b"cols", "rows", b"rows"]) -> None: ...

global___PtyResize = PtyResize

@typing.final
class PtySignal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIGNAL_FIELD_NUMBER: builtins.int
    signal: builtins.int
    """POSIX signal number (e.g. 2 = SIGINT, 3 = SIGQUIT, 9 = SIGKILL,
    15 = SIGTERM). Receivers map to the host platform's signal
    semantics; non-POSIX hosts may ignore signals they cannot
    express.
    """
    def __init__(
        self,
        *,
        signal: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["signal", b"signal"]) -> None: ...

global___PtySignal = PtySignal

@typing.final
class MediaTimestamp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    PTS_FIELD_NUMBER: builtins.int
    stream_id: builtins.int
    pts: builtins.int
    """microseconds since session reference clock"""
    def __init__(
        self,
        *,
        stream_id: builtins.int = ...,
        pts: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pts", b"pts", "stream_id", b"stream_id"]) -> None: ...

global___MediaTimestamp = MediaTimestamp

@typing.final
class DispatchCall(google.protobuf.message.Message):
    """── Carrier-unified session dispatch frames (mini-RFC, T2.1) ──────

    The session channel's business frames in canonical protocol shape.
    DispatchCall carries the ORIGINAL caller's Envelope verbatim — the
    authority forwards, never mints or rewrites (a rewrite would destroy the
    caller signature). DispatchResult closes the receipt chain at the
    authority hop: the terminal frame carries the callee-signed execution
    receipt. DEC-F004 fixed the three review points: the authority stays OFF
    the receipt chain (forwarding fact goes to the authority-local ledger),
    reverse call_ids stay 16-byte nonces (they cross authority boundaries),
    and failures reuse axon.v1.Error single-track.

    Authority → device: run one complete Invocation on the target.

    Erratum 2 (DEC-F004 landing audit): the RFC draft mapped
    `Dispatch.ability → envelope.ability`, but the Envelope does not
    carry ability — ability/args live on the surrounding request per
    the split wire shape. Rather than re-inventing that split here,
    the frame carries the complete canonical InvokeRequest verbatim:
    zero unpack/repack at the authority (a rewrite would destroy the caller
    signature), one message shape shared with the unary wire, and
    future InvokeRequest fields (timeout_seconds, payload_ref, ...)
    inherited for free.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    OPEN_BIDI_FIELD_NUMBER: builtins.int
    call_id: builtins.int
    """Session-local routing correlation (not protocol identity; never
    part of signed bytes).
    """
    open_bidi: builtins.bool
    """true = long-lived local bidi semantics (the former BidiOpen)."""
    @property
    def request(self) -> global___InvokeRequest:
        """The complete canonical invocation, forwarded verbatim."""

    def __init__(
        self,
        *,
        call_id: builtins.int = ...,
        request: global___InvokeRequest | None = ...,
        open_bidi: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id", "open_bidi", b"open_bidi", "request", b"request"]) -> None: ...

global___DispatchCall = DispatchCall

@typing.final
class DispatchResult(google.protobuf.message.Message):
    """Device → authority: result + finalized receipt checkpoints."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    TERMINAL_FIELD_NUMBER: builtins.int
    FAILURE_FIELD_NUMBER: builtins.int
    ADMISSION_RECEIPT_FIELD_NUMBER: builtins.int
    TERMINAL_RECEIPT_FIELD_NUMBER: builtins.int
    call_id: builtins.int
    payload: builtins.bytes
    terminal: builtins.bool
    @property
    def failure(self) -> types_pb2.Error:
        """Typed single-track failure (replaces the JSON-era
        Option<String> + SessionFailure dual track).
        """

    @property
    def admission_receipt(self) -> global___InvocationReceipt:
        """Exact callee-signed admission checkpoint. It appears exactly once before
        payload frames. A terminal-only unary result carries it alongside the
        terminal checkpoint.
        """

    @property
    def terminal_receipt(self) -> global___InvocationReceipt:
        """Exact callee-signed terminal checkpoint. It appears exactly once on the
        terminal frame and binds terminal state, failure, and output_hash. Its index
        MUST be greater than admission_receipt.index; adjacency is not required and
        MUST NOT be inferred from two checkpoints alone.
        """

    def __init__(
        self,
        *,
        call_id: builtins.int = ...,
        payload: builtins.bytes = ...,
        terminal: builtins.bool = ...,
        failure: types_pb2.Error | None = ...,
        admission_receipt: global___InvocationReceipt | None = ...,
        terminal_receipt: global___InvocationReceipt | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["admission_receipt", b"admission_receipt", "failure", b"failure", "terminal_receipt", b"terminal_receipt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["admission_receipt", b"admission_receipt", "call_id", b"call_id", "failure", b"failure", "payload", b"payload", "terminal", b"terminal", "terminal_receipt", b"terminal_receipt"]) -> None: ...

global___DispatchResult = DispatchResult

@typing.final
class ReverseDispatchCall(google.protobuf.message.Message):
    """Device → authority reverse request (the former Request/RequestResult):
    same shape, 16-byte nonce call_id — it crosses authority boundaries
    where a u64 session counter would have a collision surface.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    call_id: builtins.bytes
    @property
    def request(self) -> global___InvokeRequest:
        """Complete canonical invocation, same rationale as DispatchCall."""

    def __init__(
        self,
        *,
        call_id: builtins.bytes = ...,
        request: global___InvokeRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["call_id", b"call_id", "request", b"request"]) -> None: ...

global___ReverseDispatchCall = ReverseDispatchCall

@typing.final
class ReverseDispatchResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    TERMINAL_FIELD_NUMBER: builtins.int
    FAILURE_FIELD_NUMBER: builtins.int
    ADMISSION_RECEIPT_FIELD_NUMBER: builtins.int
    TERMINAL_RECEIPT_FIELD_NUMBER: builtins.int
    call_id: builtins.bytes
    payload: builtins.bytes
    terminal: builtins.bool
    @property
    def failure(self) -> types_pb2.Error: ...
    @property
    def admission_receipt(self) -> global___InvocationReceipt:
        """Exact callee-signed admission and terminal checkpoints. Canonical reverse
        Invocation success is invalid unless both are present and verify against
        the original InvokeRequest binding.
        """

    @property
    def terminal_receipt(self) -> global___InvocationReceipt: ...
    def __init__(
        self,
        *,
        call_id: builtins.bytes = ...,
        payload: builtins.bytes = ...,
        terminal: builtins.bool = ...,
        failure: types_pb2.Error | None = ...,
        admission_receipt: global___InvocationReceipt | None = ...,
        terminal_receipt: global___InvocationReceipt | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["admission_receipt", b"admission_receipt", "failure", b"failure", "terminal_receipt", b"terminal_receipt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["admission_receipt", b"admission_receipt", "call_id", b"call_id", "failure", b"failure", "payload", b"payload", "terminal", b"terminal", "terminal_receipt", b"terminal_receipt"]) -> None: ...

global___ReverseDispatchResult = ReverseDispatchResult

@typing.final
class SessionOpenExt(google.protobuf.message.Message):
    """Frame-0 up extension (rides EnvelopeOpen.session_ext)."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_VERSION_FIELD_NUMBER: builtins.int
    CLAIMANT_BOOT_NONCE_FIELD_NUMBER: builtins.int
    contract_version: builtins.int
    """Dispatch-frame contract version. This RFC = 1. Receivers reject
    0/absent because those values cannot carry canonical Invocation frames.
    """
    claimant_boot_nonce: builtins.bytes
    """T1.2: random 16 bytes per process boot — the session slot
    claimant fingerprint. Distinguishes same-device restart from
    two devices fighting over one URA.
    """
    def __init__(
        self,
        *,
        contract_version: builtins.int = ...,
        claimant_boot_nonce: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["claimant_boot_nonce", b"claimant_boot_nonce", "contract_version", b"contract_version"]) -> None: ...

global___SessionOpenExt = SessionOpenExt

@typing.final
class InvocationReceipt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    INVOCATION_ID_FIELD_NUMBER: builtins.int
    RECEIPT_TYPE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    TIMESTAMP_UNIX_MS_FIELD_NUMBER: builtins.int
    PREV_RECEIPT_HASH_FIELD_NUMBER: builtins.int
    SELF_HASH_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    PAYLOAD_CONTENT_TYPE_FIELD_NUMBER: builtins.int
    CLEANUP_COMPLETE_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    CHILD_INVOCATION_ID_FIELD_NUMBER: builtins.int
    CALLER_BINDING_FIELD_NUMBER: builtins.int
    CALLEE_BINDING_FIELD_NUMBER: builtins.int
    SUBJECT_BINDING_FIELD_NUMBER: builtins.int
    INVOCATION_NONCE_FIELD_NUMBER: builtins.int
    CAUSAL_BINDING_FIELD_NUMBER: builtins.int
    CALLEE_SIGNATURE_FIELD_NUMBER: builtins.int
    SIGNER_BINDING_FIELD_NUMBER: builtins.int
    HOST_ATTESTATION_FIELD_NUMBER: builtins.int
    AUTHORITY_BINDING_FIELD_NUMBER: builtins.int
    ABILITY_BINDING_FIELD_NUMBER: builtins.int
    FAILURE_FIELD_NUMBER: builtins.int
    USAGE_FIELD_NUMBER: builtins.int
    SUBJECT_REF_FIELD_NUMBER: builtins.int
    DESCRIPTOR_VERSION_FIELD_NUMBER: builtins.int
    SCHEMA_HASH_FIELD_NUMBER: builtins.int
    IMPL_HASH_FIELD_NUMBER: builtins.int
    RUNTIME_ENV_FIELD_NUMBER: builtins.int
    AUTHORITY_PROOF_FIELD_NUMBER: builtins.int
    INPUT_HASH_FIELD_NUMBER: builtins.int
    OUTPUT_HASH_FIELD_NUMBER: builtins.int
    PARENT_RECEIPTS_FIELD_NUMBER: builtins.int
    index: builtins.int
    """── State-machine fields (1..12) ─────────────────────
    0-based position in the chain
    """
    invocation_id: builtins.str
    receipt_type: builtins.str
    """matches InvocationEvent.event_type values"""
    state: types_pb2.InvocationState.ValueType
    timestamp_unix_ms: builtins.int
    prev_receipt_hash: builtins.bytes
    """Canonical SHA-256 over the previous receipt's canonical serialization
    within THIS invocation's lifecycle chain (admitted → running → terminal).
    Distinct from causal_binding (field 24), which names predecessors
    across invocations. All zeros for index == 0.
    """
    self_hash: builtins.bytes
    """Canonical SHA-256 over this receipt's own canonical form (excluding
    self_hash and callee_signature). Clients recompute to verify chain
    integrity. Canonical layout per RFC 001 §4.3.
    """
    payload: builtins.bytes
    """Event-type-specific payload (delta chunk, message body, etc.)"""
    payload_content_type: builtins.str
    cleanup_complete: builtins.bool
    """For terminal receipts issued by an ability with a Supervisor, this
    MUST be true (see I5 supervisor cleanup ordering).
    """
    reason: builtins.str
    """Optional human-readable reason (failure, cancellation cause, etc.)"""
    child_invocation_id: builtins.str
    """For child invocation events: the child's invocation_id."""
    invocation_nonce: builtins.bytes
    """echoes Envelope.invocation_nonce"""
    host_attestation: builtins.bytes
    ability_binding: builtins.str
    """── RFC 001 §A14 ability binding (29) — required ───
    The exact ability name admitted by the runtime and checked against
    delegation scopes. This lives in the signed receipt region so offline
    auditors re-run the same scope rule as the admission gate instead of
    guessing from subject_binding.
    """
    descriptor_version: builtins.str
    """Compatibility projection of the AbilityDescriptorRef version component."""
    schema_hash: builtins.bytes
    """SHA-256 over the governed input/output schema; zero = schema not bound."""
    impl_hash: builtins.bytes
    """SHA-256 over the executed implementation; zero = implementation not bound."""
    runtime_env: builtins.str
    """Runtime environment identifier the invocation executed under."""
    input_hash: builtins.bytes
    """SHA-256 of the request payload bound by this receipt; zero = not bound."""
    output_hash: builtins.bytes
    """SHA-256 of the terminal output payload; zero = not bound."""
    @property
    def caller_binding(self) -> types_pb2.AgentIdentity:
        """── RFC 001 axiom binding (20..25) — required ────────
        Every receipt echoes the envelope's axiom 7-tuple binding so the
        receipt is self-contained for third-party independent audit (Phase
        10 aha demo). A verifier with no runtime contact reads only
        receipts + public keys.

        echoes Envelope.caller
        """

    @property
    def callee_binding(self) -> types_pb2.AgentIdentity:
        """RFC-005 D45/D62: owner-general callee identity — the URA the call targeted; kind MAY be authority/agent/device. AgentIdentity is the owner-general identity alias, not agent-only."""

    @property
    def subject_binding(self) -> types_pb2.SubjectIdentity:
        """echoes Envelope.subject"""

    @property
    def causal_binding(self) -> types_pb2.CausalContext:
        """echoes Envelope.causal_context"""

    @property
    def callee_signature(self) -> types_pb2.CalleeSignature:
        """Callee signature over canonical receipt bytes per RFC 001 §4.3
        (excluding callee_signature itself).
        """

    @property
    def signer_binding(self) -> types_pb2.AgentIdentity:
        """── RFC 001 §A12 hosted-Agent attestation (26..27) ───
        For hosted Agents (Plan §1.3 Model B) that have no key of their own,
        the signing authority is the hosting device-profile, not the callee Agent
        itself. The two fields below let an offline verifier check that
        a receipt attributed to a hosted callee was actually signed by
        a host that legitimately hosts that callee.

          - signer_binding present + DIFFERENT from callee_binding ⇒
            hosted (Model B). callee_signature MUST verify under
            signer_binding's pubkey, AND host_attestation MUST be a
            signature over canonical_host_attestation_bytes(callee_ura,
            signer_ura) by the same signer_binding pubkey.

          - signer_binding absent OR equal to callee_binding ⇒
            self-signed (Model A). callee_signature verifies under
            callee_binding's pubkey; host_attestation MUST be empty.

        Self-signed receipts (the only kind today) leave both fields
        unset; canonical_receipt_bytes appends an absent-signer marker
        (length-zero) for either field, so existing receipt anchors are
        structurally affected and re-anchored in the same commit.
        """

    @property
    def authority_binding(self) -> types_pb2.AuthorityBinding:
        """── RFC 001 §A14 authority binding (28) — required ───
        Proves the CALLER had authority over subject_binding/ability at
        invocation time. Self-contained for offline audit (no runtime
        contact). This is the CALLER's authority, never the callee's.
        Hashed into canonical_receipt_bytes (signed region) so it cannot
        be stripped or forged. Self-authority (caller == authority
        principal) is the default and requires no delegation.
        """

    @property
    def failure(self) -> types_pb2.Error:
        """Structured terminal failure for non-COMPLETED receipts.

        `reason` stays as the human-readable explanation. Machine consumers MUST
        branch on this typed Error instead of parsing `reason`. Producers SHOULD
        populate it whenever state is FAILED, TIMED_OUT, or CANCELLED; COMPLETED
        receipts MUST leave it unset.
        """

    @property
    def usage(self) -> global___InvocationUsage:
        """── seven-axes usage (31) — signed metadata ───────────
        What this invocation CONSUMED, fixed into the signed region so
        "how much this step cost" is exactly as tamper-evident as "who
        called whom" (DEC-010 card ①; seven-axes agenda 2026-06-13).
        ALWAYS present in canonical_receipt_bytes as a zero-valued tail
        when nothing was consumed — zero is a fact, absence is not.
        Monetary cost is deliberately NOT here (ECONOMIC product layer,
        needs currency + pricing source; spec D4).
        Canonical layout per RFC 001 §4.3.
        """

    @property
    def subject_ref(self) -> types_pb2.EntityRef:
        """── Descriptor-bound proof facts (32..40) — signed metadata ─────
        The signed descriptor/runtime proof fact slots, in declaration order.
        Canonical layout per RFC 001 §4.3. All-zero hashes are signed facts that
        mean "producer did not bind this proof slot"; verifiers MUST NOT treat a
        zero hash as a valid schema/impl/input/output proof.

        Compatibility projection of the canonical subject EntityRef. Verifiers
        re-derive the subject shape from the signed invocation subject and reject
        this field if it disagrees.
        """

    @property
    def authority_proof(self) -> types_pb2.InvocationAuthorityProof:
        """Verifiable authority proof for admission; see InvocationAuthorityProof."""

    @property
    def parent_receipts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[types_pb2.ReceiptRef]:
        """Receipts this invocation was caused by / depends on."""

    def __init__(
        self,
        *,
        index: builtins.int = ...,
        invocation_id: builtins.str = ...,
        receipt_type: builtins.str = ...,
        state: types_pb2.InvocationState.ValueType = ...,
        timestamp_unix_ms: builtins.int = ...,
        prev_receipt_hash: builtins.bytes = ...,
        self_hash: builtins.bytes = ...,
        payload: builtins.bytes = ...,
        payload_content_type: builtins.str = ...,
        cleanup_complete: builtins.bool = ...,
        reason: builtins.str = ...,
        child_invocation_id: builtins.str = ...,
        caller_binding: types_pb2.AgentIdentity | None = ...,
        callee_binding: types_pb2.AgentIdentity | None = ...,
        subject_binding: types_pb2.SubjectIdentity | None = ...,
        invocation_nonce: builtins.bytes = ...,
        causal_binding: types_pb2.CausalContext | None = ...,
        callee_signature: types_pb2.CalleeSignature | None = ...,
        signer_binding: types_pb2.AgentIdentity | None = ...,
        host_attestation: builtins.bytes = ...,
        authority_binding: types_pb2.AuthorityBinding | None = ...,
        ability_binding: builtins.str = ...,
        failure: types_pb2.Error | None = ...,
        usage: global___InvocationUsage | None = ...,
        subject_ref: types_pb2.EntityRef | None = ...,
        descriptor_version: builtins.str = ...,
        schema_hash: builtins.bytes = ...,
        impl_hash: builtins.bytes = ...,
        runtime_env: builtins.str = ...,
        authority_proof: types_pb2.InvocationAuthorityProof | None = ...,
        input_hash: builtins.bytes = ...,
        output_hash: builtins.bytes = ...,
        parent_receipts: collections.abc.Iterable[types_pb2.ReceiptRef] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["authority_binding", b"authority_binding", "authority_proof", b"authority_proof", "callee_binding", b"callee_binding", "callee_signature", b"callee_signature", "caller_binding", b"caller_binding", "causal_binding", b"causal_binding", "failure", b"failure", "signer_binding", b"signer_binding", "subject_binding", b"subject_binding", "subject_ref", b"subject_ref", "usage", b"usage"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ability_binding", b"ability_binding", "authority_binding", b"authority_binding", "authority_proof", b"authority_proof", "callee_binding", b"callee_binding", "callee_signature", b"callee_signature", "caller_binding", b"caller_binding", "causal_binding", b"causal_binding", "child_invocation_id", b"child_invocation_id", "cleanup_complete", b"cleanup_complete", "descriptor_version", b"descriptor_version", "failure", b"failure", "host_attestation", b"host_attestation", "impl_hash", b"impl_hash", "index", b"index", "input_hash", b"input_hash", "invocation_id", b"invocation_id", "invocation_nonce", b"invocation_nonce", "output_hash", b"output_hash", "parent_receipts", b"parent_receipts", "payload", b"payload", "payload_content_type", b"payload_content_type", "prev_receipt_hash", b"prev_receipt_hash", "reason", b"reason", "receipt_type", b"receipt_type", "runtime_env", b"runtime_env", "schema_hash", b"schema_hash", "self_hash", b"self_hash", "signer_binding", b"signer_binding", "state", b"state", "subject_binding", b"subject_binding", "subject_ref", b"subject_ref", "timestamp_unix_ms", b"timestamp_unix_ms", "usage", b"usage"]) -> None: ...

global___InvocationReceipt = InvocationReceipt

@typing.final
class InvocationUsage(google.protobuf.message.Message):
    """Per-invocation consumption, signed into the terminal receipt.
    Producers fill what they know: the runtime always knows
    duration_ms (admitted → terminal); token counts and external call
    counts arrive from the executing handler when it reports them.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKENS_IN_FIELD_NUMBER: builtins.int
    TOKENS_OUT_FIELD_NUMBER: builtins.int
    DURATION_MS_FIELD_NUMBER: builtins.int
    EXTERNAL_CALLS_FIELD_NUMBER: builtins.int
    tokens_in: builtins.int
    tokens_out: builtins.int
    duration_ms: builtins.int
    external_calls: builtins.int
    def __init__(
        self,
        *,
        tokens_in: builtins.int = ...,
        tokens_out: builtins.int = ...,
        duration_ms: builtins.int = ...,
        external_calls: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["duration_ms", b"duration_ms", "external_calls", b"external_calls", "tokens_in", b"tokens_in", "tokens_out", b"tokens_out"]) -> None: ...

global___InvocationUsage = InvocationUsage

@typing.final
class SupervisorSpec(google.protobuf.message.Message):
    """─── Supervisor Hints (ability-side declaration) ──────

    Carried in invocation request metadata as a serialized SupervisorSpec under
    key "axon.supervisor.spec" (base64 proto bytes). The runtime reads this to
    understand resource limits + grace periods for the invocation and to
    correctly implement orphan-reaping on host restart.

    Spelled out as its own message so SDKs can produce/consume it with
    the standard codegen rather than ad-hoc JSON.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CPU_SECONDS_LIMIT_FIELD_NUMBER: builtins.int
    MEMORY_BYTES_LIMIT_FIELD_NUMBER: builtins.int
    OPEN_FDS_LIMIT_FIELD_NUMBER: builtins.int
    SUBPROCESS_LIMIT_FIELD_NUMBER: builtins.int
    WALL_SECONDS_LIMIT_FIELD_NUMBER: builtins.int
    CANCEL_GRACE_SECONDS_FIELD_NUMBER: builtins.int
    PERSIST_FOR_RECOVERY_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    cpu_seconds_limit: builtins.float
    """Soft + hard limits; runtime enforces hard via OS rlimit/cgroup where
    possible, and the SDK Supervisor enforces soft in-process.
    0 = unset
    """
    memory_bytes_limit: builtins.int
    open_fds_limit: builtins.int
    subprocess_limit: builtins.int
    wall_seconds_limit: builtins.float
    cancel_grace_seconds: builtins.float
    """Grace period between cooperative cancel (SIGTERM) and forced kill
    (SIGKILL on POSIX, TerminateProcess on Windows).
    default 5.0 on SDK side if unset
    """
    persist_for_recovery: builtins.bool
    """Whether the ability host persists its supervisor state to survive
    host restart (enables orphan reaping on recovery).
    """
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Free-form tags for operator visibility (not load-bearing)."""

    def __init__(
        self,
        *,
        cpu_seconds_limit: builtins.float = ...,
        memory_bytes_limit: builtins.int = ...,
        open_fds_limit: builtins.int = ...,
        subprocess_limit: builtins.int = ...,
        wall_seconds_limit: builtins.float = ...,
        cancel_grace_seconds: builtins.float = ...,
        persist_for_recovery: builtins.bool = ...,
        tags: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cancel_grace_seconds", b"cancel_grace_seconds", "cpu_seconds_limit", b"cpu_seconds_limit", "memory_bytes_limit", b"memory_bytes_limit", "open_fds_limit", b"open_fds_limit", "persist_for_recovery", b"persist_for_recovery", "subprocess_limit", b"subprocess_limit", "tags", b"tags", "wall_seconds_limit", b"wall_seconds_limit"]) -> None: ...

global___SupervisorSpec = SupervisorSpec
