# mypy: ignore-errors
# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import invoke_pb2 as axon_dot_v1_dot_invoke__pb2


class InvocationStub(object):
    """─────────────────────────────────────────────────────────
    Invocation Plane: All execution modes with guarantees.

    Every call carries a complete signed descriptor-bound Envelope. No
    exceptions.

    Every call terminates in a decidable state:
    Completed | Failed | TimedOut | Cancelled

    Product routing, scheduling, quota, and policy projections belong to the
    downstream host. Axon transports only canonical invocation lifecycle facts.
    ─────────────────────────────────────────────────────────

    RFC-001 P1.2.g: Invocation service collapsed to the active invocation
    primitives below.

    Per AXON-RFC-001 §A1+A2: the only network primitive is Invocation.
    Former direct helper RPCs (fan-out, async tracking, cancellation,
    result replay, inbound messaging, receipt query, and batch submit) are
    modeled as explicit abilities or caller-side composition, not as
    additional Invocation service methods or orphan wire messages
    per docs/rfc/AXON-RFC-001-restatement-mapping.md §2 invoke.proto.

    `InvokeServerStream` is renamed to `InvokeStream` semantically
    (still uses the InvokeServerStreamRequest message for now; full
    rename happens in P2 SDK collapse).

    P5-rewrite-15 adds `InvokeBidi` for realtime bidirectional
    multimodal streams (PTY full-duplex, audio/video). Per the
    strict-separation directive, InvokeBidi is a NEW RPC — it does
    NOT silently upgrade InvokeStream's server-stream semantics.
    The three RPCs partition the invocation surface:

    Invoke       — unary control invocation
    InvokeStream — server-stream control / receipt subscription
    InvokeBidi   — bidirectional realtime binary multimodal stream

    InvokeBidi's frame schema, signature/MAC chain model, and
    session-as-subject (PTY) usage are pinned in
    AXON-RFC-001-plan-v4.1.3-amendment.md §A16. Summary:
    - frame 0 up   = EnvelopeOpen, mac = Ed25519 over canonical
    invocation bytes (AXIOM seven-tuple).
    - frame 0 down = InvocationReceipt (admission accept). No
    second response model.
    - frame N≥1    = HMAC-SHA256 chain keyed by HKDF of the
    envelope signature + nonce, per direction.
    - sequence     = monotonic; v1 receivers MUST require
    incoming.sequence == last_seen + 1.
    - BinaryChunk  = (stream_id, data, pts) — stream_id refs
    one of EnvelopeOpen.streams[] descriptors.
    - initial_args = canonical-encoded args bytes (NOT JSON,
    NOT base64) — the same byte string that
    SHA-256 produces args_digest from.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/axon.v1.Invocation/Invoke',
                request_serializer=axon_dot_v1_dot_invoke__pb2.InvokeRequest.SerializeToString,
                response_deserializer=axon_dot_v1_dot_invoke__pb2.InvokeResponse.FromString,
                )
        self.InvokeStream = channel.unary_stream(
                '/axon.v1.Invocation/InvokeStream',
                request_serializer=axon_dot_v1_dot_invoke__pb2.InvokeServerStreamRequest.SerializeToString,
                response_deserializer=axon_dot_v1_dot_invoke__pb2.InvokeStreamChunk.FromString,
                )
        self.InvokeBidi = channel.stream_stream(
                '/axon.v1.Invocation/InvokeBidi',
                request_serializer=axon_dot_v1_dot_invoke__pb2.InvokeBidiUp.SerializeToString,
                response_deserializer=axon_dot_v1_dot_invoke__pb2.InvokeBidiDown.FromString,
                )


class InvocationServicer(object):
    """─────────────────────────────────────────────────────────
    Invocation Plane: All execution modes with guarantees.

    Every call carries a complete signed descriptor-bound Envelope. No
    exceptions.

    Every call terminates in a decidable state:
    Completed | Failed | TimedOut | Cancelled

    Product routing, scheduling, quota, and policy projections belong to the
    downstream host. Axon transports only canonical invocation lifecycle facts.
    ─────────────────────────────────────────────────────────

    RFC-001 P1.2.g: Invocation service collapsed to the active invocation
    primitives below.

    Per AXON-RFC-001 §A1+A2: the only network primitive is Invocation.
    Former direct helper RPCs (fan-out, async tracking, cancellation,
    result replay, inbound messaging, receipt query, and batch submit) are
    modeled as explicit abilities or caller-side composition, not as
    additional Invocation service methods or orphan wire messages
    per docs/rfc/AXON-RFC-001-restatement-mapping.md §2 invoke.proto.

    `InvokeServerStream` is renamed to `InvokeStream` semantically
    (still uses the InvokeServerStreamRequest message for now; full
    rename happens in P2 SDK collapse).

    P5-rewrite-15 adds `InvokeBidi` for realtime bidirectional
    multimodal streams (PTY full-duplex, audio/video). Per the
    strict-separation directive, InvokeBidi is a NEW RPC — it does
    NOT silently upgrade InvokeStream's server-stream semantics.
    The three RPCs partition the invocation surface:

    Invoke       — unary control invocation
    InvokeStream — server-stream control / receipt subscription
    InvokeBidi   — bidirectional realtime binary multimodal stream

    InvokeBidi's frame schema, signature/MAC chain model, and
    session-as-subject (PTY) usage are pinned in
    AXON-RFC-001-plan-v4.1.3-amendment.md §A16. Summary:
    - frame 0 up   = EnvelopeOpen, mac = Ed25519 over canonical
    invocation bytes (AXIOM seven-tuple).
    - frame 0 down = InvocationReceipt (admission accept). No
    second response model.
    - frame N≥1    = HMAC-SHA256 chain keyed by HKDF of the
    envelope signature + nonce, per direction.
    - sequence     = monotonic; v1 receivers MUST require
    incoming.sequence == last_seen + 1.
    - BinaryChunk  = (stream_id, data, pts) — stream_id refs
    one of EnvelopeOpen.streams[] descriptors.
    - initial_args = canonical-encoded args bytes (NOT JSON,
    NOT base64) — the same byte string that
    SHA-256 produces args_digest from.
    """

    def Invoke(self, request, context):
        """Single invocation (the only sync semantic primitive).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeStream(self, request, context):
        """Server-stream invocation (control / receipt streaming only).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeBidi(self, request_iterator, context):
        """Bidirectional invocation for realtime multimodal sessions.
        Product session creation and attachment are provider abilities built on
        this generic stream primitive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvocationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=axon_dot_v1_dot_invoke__pb2.InvokeRequest.FromString,
                    response_serializer=axon_dot_v1_dot_invoke__pb2.InvokeResponse.SerializeToString,
            ),
            'InvokeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InvokeStream,
                    request_deserializer=axon_dot_v1_dot_invoke__pb2.InvokeServerStreamRequest.FromString,
                    response_serializer=axon_dot_v1_dot_invoke__pb2.InvokeStreamChunk.SerializeToString,
            ),
            'InvokeBidi': grpc.stream_stream_rpc_method_handler(
                    servicer.InvokeBidi,
                    request_deserializer=axon_dot_v1_dot_invoke__pb2.InvokeBidiUp.FromString,
                    response_serializer=axon_dot_v1_dot_invoke__pb2.InvokeBidiDown.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axon.v1.Invocation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Invocation(object):
    """─────────────────────────────────────────────────────────
    Invocation Plane: All execution modes with guarantees.

    Every call carries a complete signed descriptor-bound Envelope. No
    exceptions.

    Every call terminates in a decidable state:
    Completed | Failed | TimedOut | Cancelled

    Product routing, scheduling, quota, and policy projections belong to the
    downstream host. Axon transports only canonical invocation lifecycle facts.
    ─────────────────────────────────────────────────────────

    RFC-001 P1.2.g: Invocation service collapsed to the active invocation
    primitives below.

    Per AXON-RFC-001 §A1+A2: the only network primitive is Invocation.
    Former direct helper RPCs (fan-out, async tracking, cancellation,
    result replay, inbound messaging, receipt query, and batch submit) are
    modeled as explicit abilities or caller-side composition, not as
    additional Invocation service methods or orphan wire messages
    per docs/rfc/AXON-RFC-001-restatement-mapping.md §2 invoke.proto.

    `InvokeServerStream` is renamed to `InvokeStream` semantically
    (still uses the InvokeServerStreamRequest message for now; full
    rename happens in P2 SDK collapse).

    P5-rewrite-15 adds `InvokeBidi` for realtime bidirectional
    multimodal streams (PTY full-duplex, audio/video). Per the
    strict-separation directive, InvokeBidi is a NEW RPC — it does
    NOT silently upgrade InvokeStream's server-stream semantics.
    The three RPCs partition the invocation surface:

    Invoke       — unary control invocation
    InvokeStream — server-stream control / receipt subscription
    InvokeBidi   — bidirectional realtime binary multimodal stream

    InvokeBidi's frame schema, signature/MAC chain model, and
    session-as-subject (PTY) usage are pinned in
    AXON-RFC-001-plan-v4.1.3-amendment.md §A16. Summary:
    - frame 0 up   = EnvelopeOpen, mac = Ed25519 over canonical
    invocation bytes (AXIOM seven-tuple).
    - frame 0 down = InvocationReceipt (admission accept). No
    second response model.
    - frame N≥1    = HMAC-SHA256 chain keyed by HKDF of the
    envelope signature + nonce, per direction.
    - sequence     = monotonic; v1 receivers MUST require
    incoming.sequence == last_seen + 1.
    - BinaryChunk  = (stream_id, data, pts) — stream_id refs
    one of EnvelopeOpen.streams[] descriptors.
    - initial_args = canonical-encoded args bytes (NOT JSON,
    NOT base64) — the same byte string that
    SHA-256 produces args_digest from.
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/axon.v1.Invocation/Invoke',
            axon_dot_v1_dot_invoke__pb2.InvokeRequest.SerializeToString,
            axon_dot_v1_dot_invoke__pb2.InvokeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InvokeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/axon.v1.Invocation/InvokeStream',
            axon_dot_v1_dot_invoke__pb2.InvokeServerStreamRequest.SerializeToString,
            axon_dot_v1_dot_invoke__pb2.InvokeStreamChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InvokeBidi(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/axon.v1.Invocation/InvokeBidi',
            axon_dot_v1_dot_invoke__pb2.InvokeBidiUp.SerializeToString,
            axon_dot_v1_dot_invoke__pb2.InvokeBidiDown.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
