"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
EasyNet Axon for AgentNet
=========================

File: core/proto/axon/v1/invoke.proto
Description: Source-of-truth shared Axon protocol types, envelopes, enums, and resource contracts.

Protocol Responsibility:
- Defines the foundational wire-level types reused by control, invocation, interop, identity, stream, and federation services.
- Preserves shared resource-addressing, content-envelope, and terminal-state semantics across the protocol.

Implementation Approach:
- Keeps common enums and messages in one schema so service protos compose on a stable base contract.
- Documents protocol guarantees and addressing conventions close to the shared type definitions.

Usage Contract:
- Changes here have broad compatibility impact and must remain wire-safe for generated clients.
- Regenerate dependent language artifacts after updating shared types or enums.

Architectural Position:
- Base protocol contract layer for the entire Axon wire surface.

Author: Silan.Hu
Email: silan.hu@u.nus.edu
Copyright (c) 2026-2027 easynet. All rights reserved.
"""

import abc
from . import invoke_pb2
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class InvocationStub:
    """─────────────────────────────────────────────────────────
    Invocation Plane: All execution modes with guarantees.

    Every call carries a complete signed descriptor-bound Envelope. No
    exceptions.

    Every call terminates in a decidable state:
    Completed | Failed | TimedOut | Cancelled

    Product routing, scheduling, quota, and policy projections belong to the
    downstream host. Axon transports only canonical invocation lifecycle facts.
    ─────────────────────────────────────────────────────────

    RFC-001 P1.2.g: Invocation service collapsed to the active invocation
    primitives below.

    Per AXON-RFC-001 §A1+A2: the only network primitive is Invocation.
    Former direct helper RPCs (fan-out, async tracking, cancellation,
    result replay, inbound messaging, receipt query, and batch submit) are
    modeled as explicit abilities or caller-side composition, not as
    additional Invocation service methods or orphan wire messages
    per docs/rfc/AXON-RFC-001-restatement-mapping.md §2 invoke.proto.

    `InvokeServerStream` is renamed to `InvokeStream` semantically
    (still uses the InvokeServerStreamRequest message for now; full
    rename happens in P2 SDK collapse).

    P5-rewrite-15 adds `InvokeBidi` for realtime bidirectional
    multimodal streams (PTY full-duplex, audio/video). Per the
    strict-separation directive, InvokeBidi is a NEW RPC — it does
    NOT silently upgrade InvokeStream's server-stream semantics.
    The three RPCs partition the invocation surface:

      Invoke       — unary control invocation
      InvokeStream — server-stream control / receipt subscription
      InvokeBidi   — bidirectional realtime binary multimodal stream

    InvokeBidi's frame schema, signature/MAC chain model, and
    session-as-subject (PTY) usage are pinned in
    AXON-RFC-001-plan-v4.1.3-amendment.md §A16. Summary:
      - frame 0 up   = EnvelopeOpen, mac = Ed25519 over canonical
                       invocation bytes (AXIOM seven-tuple).
      - frame 0 down = InvocationReceipt (admission accept). No
                       second response model.
      - frame N≥1    = HMAC-SHA256 chain keyed by HKDF of the
                       envelope signature + nonce, per direction.
      - sequence     = monotonic; v1 receivers MUST require
                       incoming.sequence == last_seen + 1.
      - BinaryChunk  = (stream_id, data, pts) — stream_id refs
                       one of EnvelopeOpen.streams[] descriptors.
      - initial_args = canonical-encoded args bytes (NOT JSON,
                       NOT base64) — the same byte string that
                       SHA-256 produces args_digest from.
    """

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Invoke: grpc.UnaryUnaryMultiCallable[
        invoke_pb2.InvokeRequest,
        invoke_pb2.InvokeResponse,
    ]
    """Single invocation (the only sync semantic primitive)."""

    InvokeStream: grpc.UnaryStreamMultiCallable[
        invoke_pb2.InvokeServerStreamRequest,
        invoke_pb2.InvokeStreamChunk,
    ]
    """Server-stream invocation (control / receipt streaming only)."""

    InvokeBidi: grpc.StreamStreamMultiCallable[
        invoke_pb2.InvokeBidiUp,
        invoke_pb2.InvokeBidiDown,
    ]
    """Bidirectional invocation for realtime multimodal sessions.
    Product session creation and attachment are provider abilities built on
    this generic stream primitive.
    """

class InvocationAsyncStub:
    """─────────────────────────────────────────────────────────
    Invocation Plane: All execution modes with guarantees.

    Every call carries a complete signed descriptor-bound Envelope. No
    exceptions.

    Every call terminates in a decidable state:
    Completed | Failed | TimedOut | Cancelled

    Product routing, scheduling, quota, and policy projections belong to the
    downstream host. Axon transports only canonical invocation lifecycle facts.
    ─────────────────────────────────────────────────────────

    RFC-001 P1.2.g: Invocation service collapsed to the active invocation
    primitives below.

    Per AXON-RFC-001 §A1+A2: the only network primitive is Invocation.
    Former direct helper RPCs (fan-out, async tracking, cancellation,
    result replay, inbound messaging, receipt query, and batch submit) are
    modeled as explicit abilities or caller-side composition, not as
    additional Invocation service methods or orphan wire messages
    per docs/rfc/AXON-RFC-001-restatement-mapping.md §2 invoke.proto.

    `InvokeServerStream` is renamed to `InvokeStream` semantically
    (still uses the InvokeServerStreamRequest message for now; full
    rename happens in P2 SDK collapse).

    P5-rewrite-15 adds `InvokeBidi` for realtime bidirectional
    multimodal streams (PTY full-duplex, audio/video). Per the
    strict-separation directive, InvokeBidi is a NEW RPC — it does
    NOT silently upgrade InvokeStream's server-stream semantics.
    The three RPCs partition the invocation surface:

      Invoke       — unary control invocation
      InvokeStream — server-stream control / receipt subscription
      InvokeBidi   — bidirectional realtime binary multimodal stream

    InvokeBidi's frame schema, signature/MAC chain model, and
    session-as-subject (PTY) usage are pinned in
    AXON-RFC-001-plan-v4.1.3-amendment.md §A16. Summary:
      - frame 0 up   = EnvelopeOpen, mac = Ed25519 over canonical
                       invocation bytes (AXIOM seven-tuple).
      - frame 0 down = InvocationReceipt (admission accept). No
                       second response model.
      - frame N≥1    = HMAC-SHA256 chain keyed by HKDF of the
                       envelope signature + nonce, per direction.
      - sequence     = monotonic; v1 receivers MUST require
                       incoming.sequence == last_seen + 1.
      - BinaryChunk  = (stream_id, data, pts) — stream_id refs
                       one of EnvelopeOpen.streams[] descriptors.
      - initial_args = canonical-encoded args bytes (NOT JSON,
                       NOT base64) — the same byte string that
                       SHA-256 produces args_digest from.
    """

    Invoke: grpc.aio.UnaryUnaryMultiCallable[
        invoke_pb2.InvokeRequest,
        invoke_pb2.InvokeResponse,
    ]
    """Single invocation (the only sync semantic primitive)."""

    InvokeStream: grpc.aio.UnaryStreamMultiCallable[
        invoke_pb2.InvokeServerStreamRequest,
        invoke_pb2.InvokeStreamChunk,
    ]
    """Server-stream invocation (control / receipt streaming only)."""

    InvokeBidi: grpc.aio.StreamStreamMultiCallable[
        invoke_pb2.InvokeBidiUp,
        invoke_pb2.InvokeBidiDown,
    ]
    """Bidirectional invocation for realtime multimodal sessions.
    Product session creation and attachment are provider abilities built on
    this generic stream primitive.
    """

class InvocationServicer(metaclass=abc.ABCMeta):
    """─────────────────────────────────────────────────────────
    Invocation Plane: All execution modes with guarantees.

    Every call carries a complete signed descriptor-bound Envelope. No
    exceptions.

    Every call terminates in a decidable state:
    Completed | Failed | TimedOut | Cancelled

    Product routing, scheduling, quota, and policy projections belong to the
    downstream host. Axon transports only canonical invocation lifecycle facts.
    ─────────────────────────────────────────────────────────

    RFC-001 P1.2.g: Invocation service collapsed to the active invocation
    primitives below.

    Per AXON-RFC-001 §A1+A2: the only network primitive is Invocation.
    Former direct helper RPCs (fan-out, async tracking, cancellation,
    result replay, inbound messaging, receipt query, and batch submit) are
    modeled as explicit abilities or caller-side composition, not as
    additional Invocation service methods or orphan wire messages
    per docs/rfc/AXON-RFC-001-restatement-mapping.md §2 invoke.proto.

    `InvokeServerStream` is renamed to `InvokeStream` semantically
    (still uses the InvokeServerStreamRequest message for now; full
    rename happens in P2 SDK collapse).

    P5-rewrite-15 adds `InvokeBidi` for realtime bidirectional
    multimodal streams (PTY full-duplex, audio/video). Per the
    strict-separation directive, InvokeBidi is a NEW RPC — it does
    NOT silently upgrade InvokeStream's server-stream semantics.
    The three RPCs partition the invocation surface:

      Invoke       — unary control invocation
      InvokeStream — server-stream control / receipt subscription
      InvokeBidi   — bidirectional realtime binary multimodal stream

    InvokeBidi's frame schema, signature/MAC chain model, and
    session-as-subject (PTY) usage are pinned in
    AXON-RFC-001-plan-v4.1.3-amendment.md §A16. Summary:
      - frame 0 up   = EnvelopeOpen, mac = Ed25519 over canonical
                       invocation bytes (AXIOM seven-tuple).
      - frame 0 down = InvocationReceipt (admission accept). No
                       second response model.
      - frame N≥1    = HMAC-SHA256 chain keyed by HKDF of the
                       envelope signature + nonce, per direction.
      - sequence     = monotonic; v1 receivers MUST require
                       incoming.sequence == last_seen + 1.
      - BinaryChunk  = (stream_id, data, pts) — stream_id refs
                       one of EnvelopeOpen.streams[] descriptors.
      - initial_args = canonical-encoded args bytes (NOT JSON,
                       NOT base64) — the same byte string that
                       SHA-256 produces args_digest from.
    """

    @abc.abstractmethod
    def Invoke(
        self,
        request: invoke_pb2.InvokeRequest,
        context: _ServicerContext,
    ) -> typing.Union[invoke_pb2.InvokeResponse, collections.abc.Awaitable[invoke_pb2.InvokeResponse]]:
        """Single invocation (the only sync semantic primitive)."""

    @abc.abstractmethod
    def InvokeStream(
        self,
        request: invoke_pb2.InvokeServerStreamRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[invoke_pb2.InvokeStreamChunk], collections.abc.AsyncIterator[invoke_pb2.InvokeStreamChunk]]:
        """Server-stream invocation (control / receipt streaming only)."""

    @abc.abstractmethod
    def InvokeBidi(
        self,
        request_iterator: _MaybeAsyncIterator[invoke_pb2.InvokeBidiUp],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[invoke_pb2.InvokeBidiDown], collections.abc.AsyncIterator[invoke_pb2.InvokeBidiDown]]:
        """Bidirectional invocation for realtime multimodal sessions.
        Product session creation and attachment are provider abilities built on
        this generic stream primitive.
        """

def add_InvocationServicer_to_server(servicer: InvocationServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
