from typing import Any

class _Message:
    def __init__(self, **kwargs: Any) -> None: ...

class InvokeRequest(_Message): ...
class InvokeServerStreamRequest(_Message): ...
class InvokeBidiUp(_Message): ...
class BidiControl(_Message): ...
class EnvelopeOpen(_Message): ...
class StreamDescriptor(_Message): ...
class BinaryChunk(_Message): ...
class PtyResize(_Message): ...
class PtySignal(_Message): ...
class MediaTimestamp(_Message): ...
