from typing import Any

class InvocationStub:
    def __init__(self, channel: Any) -> None: ...
    def Invoke(self, request: Any, *, timeout: float) -> Any: ...
    def InvokeStream(self, request: Any, *, timeout: float) -> Any: ...
    def InvokeBidi(self, requests: Any, *, timeout: float) -> Any: ...
