"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
File: core/proto/axon/v1/types.proto
Description: Source-of-truth canonical runtime envelopes, proof facts, receipts, and content contracts.

Protocol Responsibility:
- Defines the generic wire types reused by invocation and payload transfer.
- Preserves complete invocation-tuple, proof, content, and terminal-state semantics.

Implementation Approach:
- Keeps common enums and messages in one schema so service protos compose on a stable base contract.
- Documents protocol guarantees and URA routing conventions close to the shared type definitions.

Usage Contract:
- Changes here have broad compatibility impact and must remain wire-safe for generated clients.
- Regenerate dependent language artifacts after updating shared types or enums.

Architectural Position:
- Canonical runtime protocol contract. Product directory, deployment, policy,
  and topology models are downstream concerns.

Author: Silan.Hu
Email: silan.hu@u.nus.edu
Copyright (c) 2026-2027 easynet. All rights reserved.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ExecutionMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ExecutionModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ExecutionMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EXECUTION_MODE_UNSPECIFIED: _ExecutionMode.ValueType  # 0
    EXECUTION_MODE_SYNC: _ExecutionMode.ValueType  # 1
    """block until result"""
    EXECUTION_MODE_SERVER_STREAM: _ExecutionMode.ValueType  # 3
    """progressive result delivery"""
    EXECUTION_MODE_BIDI_STREAM: _ExecutionMode.ValueType  # 6
    """bidirectional realtime session"""

class ExecutionMode(_ExecutionMode, metaclass=_ExecutionModeEnumTypeWrapper):
    """─── Protocol: Execution Semantics ──────────────────────

    First-class execution modes implemented by the Invocation service.
    """

EXECUTION_MODE_UNSPECIFIED: ExecutionMode.ValueType  # 0
EXECUTION_MODE_SYNC: ExecutionMode.ValueType  # 1
"""block until result"""
EXECUTION_MODE_SERVER_STREAM: ExecutionMode.ValueType  # 3
"""progressive result delivery"""
EXECUTION_MODE_BIDI_STREAM: ExecutionMode.ValueType  # 6
"""bidirectional realtime session"""
global___ExecutionMode = ExecutionMode

class _Priority:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PriorityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Priority.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRIORITY_UNSPECIFIED: _Priority.ValueType  # 0
    """treated as NORMAL"""
    PRIORITY_CRITICAL: _Priority.ValueType  # 1
    """runtime-critical invocation work"""
    PRIORITY_HIGH: _Priority.ValueType  # 2
    """interactive: LLM response, real-time sensor"""
    PRIORITY_NORMAL: _Priority.ValueType  # 3
    """default: standard invocations"""
    PRIORITY_LOW: _Priority.ValueType  # 4
    """deferrable: batch processing, background sync"""
    PRIORITY_BACKGROUND: _Priority.ValueType  # 5
    """best-effort: analytics, pre-computation"""

class Priority(_Priority, metaclass=_PriorityEnumTypeWrapper):
    """─── Protocol: Request Priority ─────────────────────────

    Priority hint carried by every Envelope. The runtime host maps it to its
    own bounded execution policy.
    """

PRIORITY_UNSPECIFIED: Priority.ValueType  # 0
"""treated as NORMAL"""
PRIORITY_CRITICAL: Priority.ValueType  # 1
"""runtime-critical invocation work"""
PRIORITY_HIGH: Priority.ValueType  # 2
"""interactive: LLM response, real-time sensor"""
PRIORITY_NORMAL: Priority.ValueType  # 3
"""default: standard invocations"""
PRIORITY_LOW: Priority.ValueType  # 4
"""deferrable: batch processing, background sync"""
PRIORITY_BACKGROUND: Priority.ValueType  # 5
"""best-effort: analytics, pre-computation"""
global___Priority = Priority

class _EncryptionAlgorithm:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EncryptionAlgorithmEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EncryptionAlgorithm.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ENCRYPTION_UNSPECIFIED: _EncryptionAlgorithm.ValueType  # 0
    """plaintext — no encryption applied"""
    ENCRYPTION_AES_256_GCM: _EncryptionAlgorithm.ValueType  # 1
    """AEAD: AES-256-GCM (NIST)"""
    ENCRYPTION_CHACHA20_POLY1305: _EncryptionAlgorithm.ValueType  # 2
    """AEAD: ChaCha20-Poly1305 (RFC 8439)"""

class EncryptionAlgorithm(_EncryptionAlgorithm, metaclass=_EncryptionAlgorithmEnumTypeWrapper):
    """─── Protocol: End-to-End Encryption ────────────────────

    When payloads traverse intermediaries, E2E encryption ensures only the intended recipient
    can decrypt. Key exchange uses ECDH via Identity.NegotiateSessionKey.

    Flow:
      1. Source negotiates or obtains a recipient encryption public key
      2. Source encrypts payload → EncryptedPayload bytes
      3. ContentEnvelope.encryption + key_id declare the scheme
      4. Intermediaries forward ciphertext without access
      5. Destination retrieves the key material → decrypts
    """

ENCRYPTION_UNSPECIFIED: EncryptionAlgorithm.ValueType  # 0
"""plaintext — no encryption applied"""
ENCRYPTION_AES_256_GCM: EncryptionAlgorithm.ValueType  # 1
"""AEAD: AES-256-GCM (NIST)"""
ENCRYPTION_CHACHA20_POLY1305: EncryptionAlgorithm.ValueType  # 2
"""AEAD: ChaCha20-Poly1305 (RFC 8439)"""
global___EncryptionAlgorithm = EncryptionAlgorithm

class _EntityRefKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EntityRefKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EntityRefKind.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ENTITY_REF_KIND_UNSPECIFIED: _EntityRefKind.ValueType  # 0
    ENTITY_REF_KIND_RESOURCE: _EntityRefKind.ValueType  # 1
    ENTITY_REF_KIND_AGENT: _EntityRefKind.ValueType  # 2
    ENTITY_REF_KIND_ABILITY: _EntityRefKind.ValueType  # 3
    ENTITY_REF_KIND_SESSION: _EntityRefKind.ValueType  # 4
    ENTITY_REF_KIND_CONTINUATION: _EntityRefKind.ValueType  # 5
    ENTITY_REF_KIND_STATE_OBJECT: _EntityRefKind.ValueType  # 6
    ENTITY_REF_KIND_DEVICE: _EntityRefKind.ValueType  # 7

class EntityRefKind(_EntityRefKind, metaclass=_EntityRefKindEnumTypeWrapper):
    """EntityRef is the normalized reference shape used when descriptor-bound
    signing derives a subject binding from `SubjectIdentity`. `SubjectIdentity`
    remains the envelope subject source of truth; EntityRef carries the derived
    kind plus the same URA/profile for compatibility and receipt proof slots.
    """

ENTITY_REF_KIND_UNSPECIFIED: EntityRefKind.ValueType  # 0
ENTITY_REF_KIND_RESOURCE: EntityRefKind.ValueType  # 1
ENTITY_REF_KIND_AGENT: EntityRefKind.ValueType  # 2
ENTITY_REF_KIND_ABILITY: EntityRefKind.ValueType  # 3
ENTITY_REF_KIND_SESSION: EntityRefKind.ValueType  # 4
ENTITY_REF_KIND_CONTINUATION: EntityRefKind.ValueType  # 5
ENTITY_REF_KIND_STATE_OBJECT: EntityRefKind.ValueType  # 6
ENTITY_REF_KIND_DEVICE: EntityRefKind.ValueType  # 7
global___EntityRefKind = EntityRefKind

class _ErrorStage:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorStageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorStage.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERROR_STAGE_UNSPECIFIED: _ErrorStage.ValueType  # 0
    ERROR_STAGE_TRANSPORT: _ErrorStage.ValueType  # 1
    ERROR_STAGE_GLOBAL_ADMISSION: _ErrorStage.ValueType  # 2
    ERROR_STAGE_CALLER_AUTHENTICATION: _ErrorStage.ValueType  # 3
    ERROR_STAGE_AUTHORITY_VALIDATION: _ErrorStage.ValueType  # 4
    ERROR_STAGE_BOOTSTRAP_AUTHORIZATION: _ErrorStage.ValueType  # 5
    ERROR_STAGE_QUOTA: _ErrorStage.ValueType  # 6
    ERROR_STAGE_ABILITY_RESOLUTION: _ErrorStage.ValueType  # 7
    ERROR_STAGE_ABILITY_POLICY: _ErrorStage.ValueType  # 8
    ERROR_STAGE_REQUEST_VALIDATION: _ErrorStage.ValueType  # 9
    ERROR_STAGE_EXECUTION: _ErrorStage.ValueType  # 10

class ErrorStage(_ErrorStage, metaclass=_ErrorStageEnumTypeWrapper): ...

ERROR_STAGE_UNSPECIFIED: ErrorStage.ValueType  # 0
ERROR_STAGE_TRANSPORT: ErrorStage.ValueType  # 1
ERROR_STAGE_GLOBAL_ADMISSION: ErrorStage.ValueType  # 2
ERROR_STAGE_CALLER_AUTHENTICATION: ErrorStage.ValueType  # 3
ERROR_STAGE_AUTHORITY_VALIDATION: ErrorStage.ValueType  # 4
ERROR_STAGE_BOOTSTRAP_AUTHORIZATION: ErrorStage.ValueType  # 5
ERROR_STAGE_QUOTA: ErrorStage.ValueType  # 6
ERROR_STAGE_ABILITY_RESOLUTION: ErrorStage.ValueType  # 7
ERROR_STAGE_ABILITY_POLICY: ErrorStage.ValueType  # 8
ERROR_STAGE_REQUEST_VALIDATION: ErrorStage.ValueType  # 9
ERROR_STAGE_EXECUTION: ErrorStage.ValueType  # 10
global___ErrorStage = ErrorStage

class _SecurityClass:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SecurityClassEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SecurityClass.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SECURITY_CLASS_UNSPECIFIED: _SecurityClass.ValueType  # 0
    SECURITY_CLASS_IDENTITY: _SecurityClass.ValueType  # 1
    SECURITY_CLASS_AUTHENTICATION: _SecurityClass.ValueType  # 2
    SECURITY_CLASS_AUTHORITY: _SecurityClass.ValueType  # 3
    SECURITY_CLASS_BOOTSTRAP: _SecurityClass.ValueType  # 4
    SECURITY_CLASS_AUTHORIZATION: _SecurityClass.ValueType  # 5
    SECURITY_CLASS_RESOURCE: _SecurityClass.ValueType  # 6
    SECURITY_CLASS_TRANSPORT: _SecurityClass.ValueType  # 7
    SECURITY_CLASS_INTERNAL: _SecurityClass.ValueType  # 8

class SecurityClass(_SecurityClass, metaclass=_SecurityClassEnumTypeWrapper): ...

SECURITY_CLASS_UNSPECIFIED: SecurityClass.ValueType  # 0
SECURITY_CLASS_IDENTITY: SecurityClass.ValueType  # 1
SECURITY_CLASS_AUTHENTICATION: SecurityClass.ValueType  # 2
SECURITY_CLASS_AUTHORITY: SecurityClass.ValueType  # 3
SECURITY_CLASS_BOOTSTRAP: SecurityClass.ValueType  # 4
SECURITY_CLASS_AUTHORIZATION: SecurityClass.ValueType  # 5
SECURITY_CLASS_RESOURCE: SecurityClass.ValueType  # 6
SECURITY_CLASS_TRANSPORT: SecurityClass.ValueType  # 7
SECURITY_CLASS_INTERNAL: SecurityClass.ValueType  # 8
global___SecurityClass = SecurityClass

class _LedgerEventPayloadKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LedgerEventPayloadKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LedgerEventPayloadKind.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LEDGER_EVENT_PAYLOAD_KIND_UNSPECIFIED: _LedgerEventPayloadKind.ValueType  # 0
    LEDGER_EVENT_PAYLOAD_KIND_DIGEST: _LedgerEventPayloadKind.ValueType  # 1
    LEDGER_EVENT_PAYLOAD_KIND_SEALED: _LedgerEventPayloadKind.ValueType  # 2
    LEDGER_EVENT_PAYLOAD_KIND_MULTI_SEALED: _LedgerEventPayloadKind.ValueType  # 3

class LedgerEventPayloadKind(_LedgerEventPayloadKind, metaclass=_LedgerEventPayloadKindEnumTypeWrapper):
    """─── Protocol: Invocation Ledger ────────────────────────

    Invocation ledger records are the participant-facing audit surface for
    invoke history. They carry full URAs from the original envelope and
    store content as either digests or recipient-sealed encrypted payloads.
    Operators may index request/trace/state metadata, but plaintext args,
    results, and logs must be visible only to authorised participants.
    """

LEDGER_EVENT_PAYLOAD_KIND_UNSPECIFIED: LedgerEventPayloadKind.ValueType  # 0
LEDGER_EVENT_PAYLOAD_KIND_DIGEST: LedgerEventPayloadKind.ValueType  # 1
LEDGER_EVENT_PAYLOAD_KIND_SEALED: LedgerEventPayloadKind.ValueType  # 2
LEDGER_EVENT_PAYLOAD_KIND_MULTI_SEALED: LedgerEventPayloadKind.ValueType  # 3
global___LedgerEventPayloadKind = LedgerEventPayloadKind

class _InvocationState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InvocationStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InvocationState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    INVOCATION_STATE_UNSPECIFIED: _InvocationState.ValueType  # 0
    INVOCATION_STATE_ACCEPTED: _InvocationState.ValueType  # 1
    INVOCATION_STATE_ADMITTED: _InvocationState.ValueType  # 2
    INVOCATION_STATE_DISPATCHED: _InvocationState.ValueType  # 3
    INVOCATION_STATE_RUNNING: _InvocationState.ValueType  # 4
    INVOCATION_STATE_COMPLETED: _InvocationState.ValueType  # 5
    INVOCATION_STATE_FAILED: _InvocationState.ValueType  # 6
    INVOCATION_STATE_TIMED_OUT: _InvocationState.ValueType  # 7
    INVOCATION_STATE_CANCELLED: _InvocationState.ValueType  # 8

class InvocationState(_InvocationState, metaclass=_InvocationStateEnumTypeWrapper):
    """Invocation state machine:
    Accepted → Admitted → Dispatched → Running → Completed | Failed | TimedOut | Cancelled
    """

INVOCATION_STATE_UNSPECIFIED: InvocationState.ValueType  # 0
INVOCATION_STATE_ACCEPTED: InvocationState.ValueType  # 1
INVOCATION_STATE_ADMITTED: InvocationState.ValueType  # 2
INVOCATION_STATE_DISPATCHED: InvocationState.ValueType  # 3
INVOCATION_STATE_RUNNING: InvocationState.ValueType  # 4
INVOCATION_STATE_COMPLETED: InvocationState.ValueType  # 5
INVOCATION_STATE_FAILED: InvocationState.ValueType  # 6
INVOCATION_STATE_TIMED_OUT: InvocationState.ValueType  # 7
INVOCATION_STATE_CANCELLED: InvocationState.ValueType  # 8
global___InvocationState = InvocationState

class _InvocationTargetKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InvocationTargetKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InvocationTargetKind.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    INVOCATION_TARGET_KIND_UNSPECIFIED: _InvocationTargetKind.ValueType  # 0
    INVOCATION_TARGET_KIND_ABILITY: _InvocationTargetKind.ValueType  # 1
    """Native Axon ability"""

class InvocationTargetKind(_InvocationTargetKind, metaclass=_InvocationTargetKindEnumTypeWrapper):
    """Distinguishes the semantic kind of invocation target at the protocol level,
    so the runtime can resolve the correct binding path without overloading
    ability_name.
    """

INVOCATION_TARGET_KIND_UNSPECIFIED: InvocationTargetKind.ValueType  # 0
INVOCATION_TARGET_KIND_ABILITY: InvocationTargetKind.ValueType  # 1
"""Native Axon ability"""
global___InvocationTargetKind = InvocationTargetKind

@typing.final
class ContentEnvelope(google.protobuf.message.Message):
    """─── Protocol: Content Contract ─────────────────────────

    Content negotiation envelope for any payload crossing
    the protocol boundary (arguments, results, stream chunks).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    ENCODING_FIELD_NUMBER: builtins.int
    SCHEMA_URA_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int
    ENCRYPTION_FIELD_NUMBER: builtins.int
    KEY_ID_FIELD_NUMBER: builtins.int
    content_type: builtins.str
    """MIME: "application/json", "image/png", ..."""
    encoding: builtins.str
    """"identity" | "gzip" | "zstd" """
    schema_ura: builtins.str
    """optional full URA for schema resource"""
    encryption: global___EncryptionAlgorithm.ValueType
    """UNSPECIFIED = plaintext"""
    key_id: builtins.str
    """session key used for E2E encryption"""
    @property
    def meta(self) -> global___ContentMeta:
        """multimedia metadata (when applicable)"""

    def __init__(
        self,
        *,
        content_type: builtins.str = ...,
        encoding: builtins.str = ...,
        schema_ura: builtins.str = ...,
        meta: global___ContentMeta | None = ...,
        encryption: global___EncryptionAlgorithm.ValueType = ...,
        key_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "encoding", b"encoding", "encryption", b"encryption", "key_id", b"key_id", "meta", b"meta", "schema_ura", b"schema_ura"]) -> None: ...

global___ContentEnvelope = ContentEnvelope

@typing.final
class EncryptedPayload(google.protobuf.message.Message):
    """Encrypted payload envelope. Wraps any payload that requires
    end-to-end confidentiality across intermediary nodes.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALGORITHM_FIELD_NUMBER: builtins.int
    KEY_ID_FIELD_NUMBER: builtins.int
    NONCE_FIELD_NUMBER: builtins.int
    CIPHERTEXT_FIELD_NUMBER: builtins.int
    AUTH_TAG_FIELD_NUMBER: builtins.int
    AAD_FIELD_NUMBER: builtins.int
    EPHEMERAL_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    algorithm: global___EncryptionAlgorithm.ValueType
    key_id: builtins.str
    """full URA or stable key identifier for the recipient key"""
    nonce: builtins.bytes
    """unique per encryption operation (12 bytes for GCM/Poly1305)"""
    ciphertext: builtins.bytes
    """encrypted data"""
    auth_tag: builtins.bytes
    """authentication tag"""
    aad: builtins.bytes
    """additional authenticated data (e.g. serialized Envelope)"""
    ephemeral_public_key: builtins.bytes
    """sender ephemeral X25519 public key"""
    def __init__(
        self,
        *,
        algorithm: global___EncryptionAlgorithm.ValueType = ...,
        key_id: builtins.str = ...,
        nonce: builtins.bytes = ...,
        ciphertext: builtins.bytes = ...,
        auth_tag: builtins.bytes = ...,
        aad: builtins.bytes = ...,
        ephemeral_public_key: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aad", b"aad", "algorithm", b"algorithm", "auth_tag", b"auth_tag", "ciphertext", b"ciphertext", "ephemeral_public_key", b"ephemeral_public_key", "key_id", b"key_id", "nonce", b"nonce"]) -> None: ...

global___EncryptedPayload = EncryptedPayload

@typing.final
class AgentIdentity(google.protobuf.message.Message):
    """─── Protocol: Axiom Identity (RFC 001 §3.1) ────────────

    URA composite identity carrier. `AgentIdentity` is the compatibility
    wire name for the actor/owner slots: caller is an initiating agent
    identity; callee is owner-general and may be an authority, agent, or device
    URA after RFC-005 namespace resolution. The `profile` selector is
    structurally bound to the URA it profiles — see AXIOM.tex §5.4 Axis B.

    Canonicalisation: URA §3 verbatim. Axon does not re-specify.

    See document/rfcs/001-envelope-axiom-alignment.md §3.1.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URA_FIELD_NUMBER: builtins.int
    PROFILE_FIELD_NUMBER: builtins.int
    ura: builtins.str
    """URA canonical form per URA §3. Examples:
      "EasyNet URA /r/silan/agent/alice.quote-bot"
      "EasyNet URA /r/silan/authority/research-authority"
      "EasyNet URA /r/silan/device/macbook-pro"
    """
    profile: builtins.str
    """URA profile selector. Known values:
      "axon-strict-v2"  — RFC 001 default.
      "web-safe-v2"        — RFC-3986-compatible subset.
    """
    def __init__(
        self,
        *,
        ura: builtins.str = ...,
        profile: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["profile", b"profile", "ura", b"ura"]) -> None: ...

global___AgentIdentity = AgentIdentity

@typing.final
class SubjectIdentity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URA_FIELD_NUMBER: builtins.int
    PROFILE_FIELD_NUMBER: builtins.int
    ura: builtins.str
    profile: builtins.str
    def __init__(
        self,
        *,
        ura: builtins.str = ...,
        profile: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["profile", b"profile", "ura", b"ura"]) -> None: ...

global___SubjectIdentity = SubjectIdentity

@typing.final
class EntityRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KIND_FIELD_NUMBER: builtins.int
    URA_FIELD_NUMBER: builtins.int
    PROFILE_FIELD_NUMBER: builtins.int
    kind: global___EntityRefKind.ValueType
    ura: builtins.str
    """full canonical URA"""
    profile: builtins.str
    """URA profile selector. proto3 cannot distinguish an empty string from an
    absent field, so this non-empty requirement is NOT expressible in the
    schema: producers MUST reject an empty profile before signing, and
    verifiers MUST reject an EntityRef with an empty profile in signed
    material. The canonical signing layout length-prefixes this field
    (RFC 001 §4.3).
    """
    def __init__(
        self,
        *,
        kind: global___EntityRefKind.ValueType = ...,
        ura: builtins.str = ...,
        profile: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["kind", b"kind", "profile", b"profile", "ura", b"ura"]) -> None: ...

global___EntityRef = EntityRef

@typing.final
class InvocationAuthorityProof(google.protobuf.message.Message):
    """Verifiable authority proof envelope for invocation admission and receipts.
    Axon defines the signed shape; concrete policy source, device_ura binding,
    and session delegation rules are supplied by the runtime/daemon layer.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROOF_TYPE_FIELD_NUMBER: builtins.int
    BINDING_FIELD_NUMBER: builtins.int
    PROOF_PAYLOAD_FIELD_NUMBER: builtins.int
    PROOF_HASH_FIELD_NUMBER: builtins.int
    ISSUER_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    ADMISSION_HOOK_FIELD_NUMBER: builtins.int
    proof_type: builtins.str
    """"self" | "delegation" | "session" | policy-specific profile"""
    proof_payload: builtins.bytes
    """canonical external proof payload, if any"""
    proof_hash: builtins.bytes
    """SHA-256 over proof_payload or binding projection"""
    admission_hook: builtins.str
    """extension point name; policy implementation is external"""
    @property
    def binding(self) -> global___AuthorityBinding:
        """structured authority facts when representable in Axon"""

    @property
    def issuer(self) -> global___AgentIdentity:
        """signer/issuer of proof_payload, when known"""

    @property
    def signature(self) -> global___CalleeSignature:
        """signature over proof_hash/admission payload"""

    def __init__(
        self,
        *,
        proof_type: builtins.str = ...,
        binding: global___AuthorityBinding | None = ...,
        proof_payload: builtins.bytes = ...,
        proof_hash: builtins.bytes = ...,
        issuer: global___AgentIdentity | None = ...,
        signature: global___CalleeSignature | None = ...,
        admission_hook: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["binding", b"binding", "issuer", b"issuer", "signature", b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["admission_hook", b"admission_hook", "binding", b"binding", "issuer", b"issuer", "proof_hash", b"proof_hash", "proof_payload", b"proof_payload", "proof_type", b"proof_type", "signature", b"signature"]) -> None: ...

global___InvocationAuthorityProof = InvocationAuthorityProof

@typing.final
class CausalContext(google.protobuf.message.Message):
    """─── Protocol: Axiom Causal Context (RFC 001 §3.3) ──────

    AXIOM.tex §2.2 resolves `causal_context` into one of four canonical
    forms. Each form has its own oneof arm. Unknown form ⇒ admission reject.
    Canonical byte layout: RFC 001 §4.2.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NONE_FIELD_NUMBER: builtins.int
    SCALAR_FIELD_NUMBER: builtins.int
    LIST_FIELD_NUMBER: builtins.int
    MERKLE_FIELD_NUMBER: builtins.int
    @property
    def none(self) -> global___Empty:
        """root invocation"""

    @property
    def scalar(self) -> global___ReceiptRef:
        """linear successor"""

    @property
    def list(self) -> global___ReceiptList:
        """fan-in join (bounded by profile)"""

    @property
    def merkle(self) -> global___MerkleRoot:
        """large fan-in (wire reserved, auditor deferred)"""

    def __init__(
        self,
        *,
        none: global___Empty | None = ...,
        scalar: global___ReceiptRef | None = ...,
        list: global___ReceiptList | None = ...,
        merkle: global___MerkleRoot | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["form", b"form", "list", b"list", "merkle", b"merkle", "none", b"none", "scalar", b"scalar"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["form", b"form", "list", b"list", "merkle", b"merkle", "none", b"none", "scalar", b"scalar"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["form", b"form"]) -> typing.Literal["none", "scalar", "list", "merkle"] | None: ...

global___CausalContext = CausalContext

@typing.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing.final
class ReceiptRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECEIPT_HASH_FIELD_NUMBER: builtins.int
    RECEIPT_URA_FIELD_NUMBER: builtins.int
    receipt_hash: builtins.bytes
    """SHA-256 over the referenced receipt's canonical bytes. 32 bytes."""
    receipt_ura: builtins.str
    """URA locator for auditor fetch. Required."""
    def __init__(
        self,
        *,
        receipt_hash: builtins.bytes = ...,
        receipt_ura: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["receipt_hash", b"receipt_hash", "receipt_ura", b"receipt_ura"]) -> None: ...

global___ReceiptRef = ReceiptRef

@typing.final
class ReceiptList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRIOR_FIELD_NUMBER: builtins.int
    @property
    def prior(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ReceiptRef]:
        """Caller-asserted join order. Covered by caller's signature.
        Runtime MUST NOT reorder.
        """

    def __init__(
        self,
        *,
        prior: collections.abc.Iterable[global___ReceiptRef] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["prior", b"prior"]) -> None: ...

global___ReceiptList = ReceiptList

@typing.final
class MerkleRoot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROOT_FIELD_NUMBER: builtins.int
    PROOF_URA_FIELD_NUMBER: builtins.int
    root: builtins.bytes
    """32 bytes"""
    proof_ura: builtins.str
    """URA of the published proof artefact"""
    def __init__(
        self,
        *,
        root: builtins.bytes = ...,
        proof_ura: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["proof_ura", b"proof_ura", "root", b"root"]) -> None: ...

global___MerkleRoot = MerkleRoot

@typing.final
class CallerSignature(google.protobuf.message.Message):
    """─── Protocol: Axiom Signatures (RFC 001 §3.5, §3.6) ────

    Caller signs canonical invocation bytes (RFC 001 §4.1) over the
    full axiom 7-tuple including nonce, causal_context, and subject.
    Callee signs canonical receipt bytes (RFC 001 §4.3) excluding the
    callee_signature field itself.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALGORITHM_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    KEY_ID_HINT_FIELD_NUMBER: builtins.int
    algorithm: builtins.str
    """Signing algorithm id per URA §7 algorithm registry.
    Known values: "ed25519", "ecdsa-p256-sha256".
    """
    signature: builtins.bytes
    key_id_hint: builtins.str
    """Key id hint (non-trustworthy — verifiers MUST resolve independently)."""
    def __init__(
        self,
        *,
        algorithm: builtins.str = ...,
        signature: builtins.bytes = ...,
        key_id_hint: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["algorithm", b"algorithm", "key_id_hint", b"key_id_hint", "signature", b"signature"]) -> None: ...

global___CallerSignature = CallerSignature

@typing.final
class CalleeSignature(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALGORITHM_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    KEY_ID_HINT_FIELD_NUMBER: builtins.int
    algorithm: builtins.str
    signature: builtins.bytes
    key_id_hint: builtins.str
    def __init__(
        self,
        *,
        algorithm: builtins.str = ...,
        signature: builtins.bytes = ...,
        key_id_hint: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["algorithm", b"algorithm", "key_id_hint", b"key_id_hint", "signature", b"signature"]) -> None: ...

global___CalleeSignature = CalleeSignature

@typing.final
class AuthorityBinding(google.protobuf.message.Message):
    """─── Protocol: Authority Binding (RFC 001 §A14) ─────────

    Records WHO had authority over the invocation's subject/ability.
    Lives in the receipt's SIGNED region (canonical_receipt_bytes).
    Exactly one arm is set. Unknown/absent arm ⇒ verification reject.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SELF_AUTHORITY_FIELD_NUMBER: builtins.int
    DELEGATED_AUTHORITY_FIELD_NUMBER: builtins.int
    CAPABILITY_GRANT_FIELD_NUMBER: builtins.int
    POLICY_GRANT_FIELD_NUMBER: builtins.int
    SESSION_AUTHORITY_FIELD_NUMBER: builtins.int
    BOOTSTRAP_AUTHORITY_FIELD_NUMBER: builtins.int
    @property
    def self_authority(self) -> global___SelfAuthority:
        """caller == authority principal; no delegation"""

    @property
    def delegated_authority(self) -> global___DelegationProof:
        """caller acts for subject under issuer delegation"""

    @property
    def capability_grant(self) -> global___CapabilityGrant:
        """reserved (RFC 002)"""

    @property
    def policy_grant(self) -> global___PolicyGrant:
        """reserved (RFC 002)"""

    @property
    def session_authority(self) -> global___SessionAuthority:
        """backend-signed interactive login session authority"""

    @property
    def bootstrap_authority(self) -> global___BootstrapAuthority:
        """trust-anchor / self-identity bootstrap authority"""

    def __init__(
        self,
        *,
        self_authority: global___SelfAuthority | None = ...,
        delegated_authority: global___DelegationProof | None = ...,
        capability_grant: global___CapabilityGrant | None = ...,
        policy_grant: global___PolicyGrant | None = ...,
        session_authority: global___SessionAuthority | None = ...,
        bootstrap_authority: global___BootstrapAuthority | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["authority", b"authority", "bootstrap_authority", b"bootstrap_authority", "capability_grant", b"capability_grant", "delegated_authority", b"delegated_authority", "policy_grant", b"policy_grant", "self_authority", b"self_authority", "session_authority", b"session_authority"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "bootstrap_authority", b"bootstrap_authority", "capability_grant", b"capability_grant", "delegated_authority", b"delegated_authority", "policy_grant", b"policy_grant", "self_authority", b"self_authority", "session_authority", b"session_authority"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["authority", b"authority"]) -> typing.Literal["self_authority", "delegated_authority", "capability_grant", "policy_grant", "session_authority", "bootstrap_authority"] | None: ...

global___AuthorityBinding = AuthorityBinding

@typing.final
class SelfAuthority(google.protobuf.message.Message):
    """caller is itself the authority principal (caller == subject principal).
    The structural complement of DelegationProof: present precisely when
    no delegation is required. NOT callee authority.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRINCIPAL_URA_FIELD_NUMBER: builtins.int
    principal_ura: builtins.str
    """The principal URA the caller asserts authority as. MUST equal
    caller_binding.ura; verifiers reject otherwise.
    """
    def __init__(
        self,
        *,
        principal_ura: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["principal_ura", b"principal_ura"]) -> None: ...

global___SelfAuthority = SelfAuthority

@typing.final
class DelegationProof(google.protobuf.message.Message):
    """Canonical delegated-authority evidence. Verification semantics are owned by
    the authority provider that admits the invocation; core transports do not
    infer this evidence from product metadata.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_URA_FIELD_NUMBER: builtins.int
    SUBJECT_URA_FIELD_NUMBER: builtins.int
    CALLER_URA_FIELD_NUMBER: builtins.int
    AUDIENCE_FIELD_NUMBER: builtins.int
    SCOPES_FIELD_NUMBER: builtins.int
    ISSUED_AT_MS_FIELD_NUMBER: builtins.int
    EXPIRES_AT_MS_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    issuer_ura: builtins.str
    subject_ura: builtins.str
    caller_ura: builtins.str
    audience: builtins.str
    issued_at_ms: builtins.int
    expires_at_ms: builtins.int
    signature: builtins.bytes
    """ed25519 signature by issuer over canonical_delegation_payload_json."""
    @property
    def scopes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        issuer_ura: builtins.str = ...,
        subject_ura: builtins.str = ...,
        caller_ura: builtins.str = ...,
        audience: builtins.str = ...,
        scopes: collections.abc.Iterable[builtins.str] | None = ...,
        issued_at_ms: builtins.int = ...,
        expires_at_ms: builtins.int = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["audience", b"audience", "caller_ura", b"caller_ura", "expires_at_ms", b"expires_at_ms", "issued_at_ms", b"issued_at_ms", "issuer_ura", b"issuer_ura", "scopes", b"scopes", "signature", b"signature", "subject_ura", b"subject_ura"]) -> None: ...

global___DelegationProof = DelegationProof

@typing.final
class CapabilityGrant(google.protobuf.message.Message):
    """Reserved for RFC 002 capability tokens. Minimal today."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAPABILITY_URA_FIELD_NUMBER: builtins.int
    capability_ura: builtins.str
    def __init__(
        self,
        *,
        capability_ura: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["capability_ura", b"capability_ura"]) -> None: ...

global___CapabilityGrant = CapabilityGrant

@typing.final
class PolicyGrant(google.protobuf.message.Message):
    """Reserved for RFC 002 policy grants. Minimal today."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POLICY_URA_FIELD_NUMBER: builtins.int
    policy_ura: builtins.str
    def __init__(
        self,
        *,
        policy_ura: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["policy_ura", b"policy_ura"]) -> None: ...

global___PolicyGrant = PolicyGrant

@typing.final
class SessionAuthority(google.protobuf.message.Message):
    """Session authority is not user delegation. It proves that a trusted
    issuer is acting under an authenticated interactive subject session,
    and is signed by the issuer identity. It does not claim that the
    subject private key signed the invocation authority.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_URA_FIELD_NUMBER: builtins.int
    SUBJECT_URA_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    SCOPES_FIELD_NUMBER: builtins.int
    AUDIENCES_FIELD_NUMBER: builtins.int
    ISSUED_AT_MS_FIELD_NUMBER: builtins.int
    EXPIRES_AT_MS_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    issuer_ura: builtins.str
    subject_ura: builtins.str
    session_id: builtins.str
    issued_at_ms: builtins.int
    expires_at_ms: builtins.int
    signature: builtins.bytes
    """ed25519 signature by issuer over canonical_session_authority_payload_json."""
    @property
    def scopes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def audiences(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        issuer_ura: builtins.str = ...,
        subject_ura: builtins.str = ...,
        session_id: builtins.str = ...,
        scopes: collections.abc.Iterable[builtins.str] | None = ...,
        audiences: collections.abc.Iterable[builtins.str] | None = ...,
        issued_at_ms: builtins.int = ...,
        expires_at_ms: builtins.int = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["audiences", b"audiences", "expires_at_ms", b"expires_at_ms", "issued_at_ms", b"issued_at_ms", "issuer_ura", b"issuer_ura", "scopes", b"scopes", "session_id", b"session_id", "signature", b"signature", "subject_ura", b"subject_ura"]) -> None: ...

global___SessionAuthority = SessionAuthority

@typing.final
class BootstrapAuthority(google.protobuf.message.Message):
    """Bootstrap authority is the signed-receipt authority binding for
    identity/presence bootstrap abilities whose caller already passed
    strict caller admission but must not depend on normal delegation:
    `identity.register_pubkey`, `runtime.bootstrap_self_identity`,
    and `federation.advertise_agent`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRINCIPAL_URA_FIELD_NUMBER: builtins.int
    REALM_FIELD_NUMBER: builtins.int
    ABILITY_FIELD_NUMBER: builtins.int
    principal_ura: builtins.str
    """admitted caller that exercised bootstrap authority"""
    realm: builtins.str
    """daemon/runtime realm in which bootstrap is valid"""
    ability: builtins.str
    """bootstrap ability admitted by the bootstrap gate"""
    def __init__(
        self,
        *,
        principal_ura: builtins.str = ...,
        realm: builtins.str = ...,
        ability: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ability", b"ability", "principal_ura", b"principal_ura", "realm", b"realm"]) -> None: ...

global___BootstrapAuthority = BootstrapAuthority

@typing.final
class Envelope(google.protobuf.message.Message):
    """─── Protocol: Request/Response Envelope ────────────────

    Envelope carries the axiom 7-tuple parameters that identify and bind
    an invocation, plus a small set of operational fields (request_id,
    idempotency, deadline, trace). See document/concepts/AXIOM.tex §2 and
    RFC 001 §3.2.

    Pre-release notice (RFC 001 v0.2 overlay). Four compatibility fields — field
    numbers 3, 4, 5, 12 — have been removed. They were superseded by the
    axiom 7-tuple, and since Axon is pre-release there is no v1 wire to
    keep compatible:

      field 3  tenant_id            → tenant lives in caller.ura / subject.ura
      field 4  agent_id             → superseded by caller.ura
      field 5  principal_id         → superseded by caller.ura
      field 12 parent_invocation_id → subsumed by causal_context.scalar

    The numbers are `reserved` below so future additions cannot silently
    re-use them and cross-wire with any stale generated code.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    IDEMPOTENCY_KEY_FIELD_NUMBER: builtins.int
    DEADLINE_UNIX_MS_FIELD_NUMBER: builtins.int
    TRACE_ID_FIELD_NUMBER: builtins.int
    SPAN_ID_FIELD_NUMBER: builtins.int
    RETRY_ATTEMPT_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    CALLER_FIELD_NUMBER: builtins.int
    CALLEE_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    INVOCATION_NONCE_FIELD_NUMBER: builtins.int
    CAUSAL_CONTEXT_FIELD_NUMBER: builtins.int
    CALLER_SIGNATURE_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    """── Operational metadata ─────────────────────────────
    globally unique, caller-assigned
    """
    idempotency_key: builtins.str
    """application-level dedup window key"""
    deadline_unix_ms: builtins.int
    trace_id: builtins.str
    span_id: builtins.str
    retry_attempt: builtins.int
    priority: global___Priority.ValueType
    invocation_nonce: builtins.bytes
    """16 bytes CSPRNG, caller-generated"""
    @property
    def caller(self) -> global___AgentIdentity:
        """── RFC 001 axiom 7-tuple ────────────────────────────
        INV-1 requires all seven parameters present in the signing region.

        Four identity / binding parameters live here on the Envelope; the
        remaining two axiom parameters — `ability` and `args` — live on the
        surrounding request message (e.g. InvokeRequest.function_name and
        InvokeRequest.arguments) because they are per-call, not per-session.
        The caller_signature below binds over all seven.

        Q1 first-class initiating agent identity
        """

    @property
    def callee(self) -> global___AgentIdentity:
        """Q2 stable owner-general callee identity"""

    @property
    def subject(self) -> global___SubjectIdentity:
        """Canonical subject identity. Descriptor-bound signing normalizes this
        subject into EntityRef inside admission/receipt construction; callers
        MUST NOT send a separate subject_ref request fact.
        """

    @property
    def causal_context(self) -> global___CausalContext:
        """Q3/Q4 signed causal binding"""

    @property
    def caller_signature(self) -> global___CallerSignature:
        """Caller signature over canonical invocation bytes per RFC 001 §4.1.
        Covers caller/callee/subject(EntityRef projection)/ability_descriptor_ref/
        args_digest/nonce/causal_context.
        """

    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        idempotency_key: builtins.str = ...,
        deadline_unix_ms: builtins.int = ...,
        trace_id: builtins.str = ...,
        span_id: builtins.str = ...,
        retry_attempt: builtins.int = ...,
        priority: global___Priority.ValueType = ...,
        caller: global___AgentIdentity | None = ...,
        callee: global___AgentIdentity | None = ...,
        subject: global___SubjectIdentity | None = ...,
        invocation_nonce: builtins.bytes = ...,
        causal_context: global___CausalContext | None = ...,
        caller_signature: global___CallerSignature | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["callee", b"callee", "caller", b"caller", "caller_signature", b"caller_signature", "causal_context", b"causal_context", "subject", b"subject"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["callee", b"callee", "caller", b"caller", "caller_signature", b"caller_signature", "causal_context", b"causal_context", "deadline_unix_ms", b"deadline_unix_ms", "idempotency_key", b"idempotency_key", "invocation_nonce", b"invocation_nonce", "priority", b"priority", "request_id", b"request_id", "retry_attempt", b"retry_attempt", "span_id", b"span_id", "subject", b"subject", "trace_id", b"trace_id"]) -> None: ...

global___Envelope = Envelope

@typing.final
class ResponseHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    TRACE_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PERMANENT_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    trace_id: builtins.str
    status: builtins.str
    """"accepted" | "completed" | "rejected" """
    permanent: builtins.bool
    """When true, the status represents a permanent rejection — the client should
    disconnect rather than retry. Allows the Authority to introduce new rejection
    statuses without requiring client-side string matching updates.
    """
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
        trace_id: builtins.str = ...,
        status: builtins.str = ...,
        permanent: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["permanent", b"permanent", "request_id", b"request_id", "status", b"status", "trace_id", b"trace_id"]) -> None: ...

global___ResponseHeader = ResponseHeader

@typing.final
class Error(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ContextEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    RETRYABLE_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    STAGE_FIELD_NUMBER: builtins.int
    SECURITY_CLASS_FIELD_NUMBER: builtins.int
    code: builtins.str
    """canonical machine-readable ErrorCode, e.g. "CALLER_SIGNATURE_INVALID" """
    message: builtins.str
    """human-readable"""
    retryable: builtins.bool
    stage: global___ErrorStage.ValueType
    security_class: global___SecurityClass.ValueType
    @property
    def context(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        message: builtins.str = ...,
        retryable: builtins.bool = ...,
        context: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        stage: global___ErrorStage.ValueType = ...,
        security_class: global___SecurityClass.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "context", b"context", "message", b"message", "retryable", b"retryable", "security_class", b"security_class", "stage", b"stage"]) -> None: ...

global___Error = Error

@typing.final
class SealedLedgerEventPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALGORITHM_FIELD_NUMBER: builtins.int
    RECIPIENT_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    EPHEMERAL_PUBLIC_KEY_FIELD_NUMBER: builtins.int
    NONCE_FIELD_NUMBER: builtins.int
    AAD_SHA256_FIELD_NUMBER: builtins.int
    PLAINTEXT_SHA256_FIELD_NUMBER: builtins.int
    CIPHERTEXT_FIELD_NUMBER: builtins.int
    algorithm: builtins.str
    """e.g. x25519-chacha20poly1305-sha256-aad-v1"""
    recipient_public_key: builtins.bytes
    """encryption key, not signing key"""
    ephemeral_public_key: builtins.bytes
    nonce: builtins.bytes
    aad_sha256: builtins.str
    plaintext_sha256: builtins.str
    ciphertext: builtins.bytes
    def __init__(
        self,
        *,
        algorithm: builtins.str = ...,
        recipient_public_key: builtins.bytes = ...,
        ephemeral_public_key: builtins.bytes = ...,
        nonce: builtins.bytes = ...,
        aad_sha256: builtins.str = ...,
        plaintext_sha256: builtins.str = ...,
        ciphertext: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aad_sha256", b"aad_sha256", "algorithm", b"algorithm", "ciphertext", b"ciphertext", "ephemeral_public_key", b"ephemeral_public_key", "nonce", b"nonce", "plaintext_sha256", b"plaintext_sha256", "recipient_public_key", b"recipient_public_key"]) -> None: ...

global___SealedLedgerEventPayload = SealedLedgerEventPayload

@typing.final
class LedgerEventPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KIND_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    SHA256_FIELD_NUMBER: builtins.int
    SIZE_BYTES_FIELD_NUMBER: builtins.int
    SEALED_FIELD_NUMBER: builtins.int
    RECIPIENTS_FIELD_NUMBER: builtins.int
    kind: global___LedgerEventPayloadKind.ValueType
    content_type: builtins.str
    sha256: builtins.str
    """present for digest payloads"""
    size_bytes: builtins.int
    """present for digest payloads"""
    @property
    def sealed(self) -> global___SealedLedgerEventPayload: ...
    @property
    def recipients(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RecipientSealedLedgerEventPayload]: ...
    def __init__(
        self,
        *,
        kind: global___LedgerEventPayloadKind.ValueType = ...,
        content_type: builtins.str = ...,
        sha256: builtins.str = ...,
        size_bytes: builtins.int = ...,
        sealed: global___SealedLedgerEventPayload | None = ...,
        recipients: collections.abc.Iterable[global___RecipientSealedLedgerEventPayload] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["sealed", b"sealed"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "kind", b"kind", "recipients", b"recipients", "sealed", b"sealed", "sha256", b"sha256", "size_bytes", b"size_bytes"]) -> None: ...

global___LedgerEventPayload = LedgerEventPayload

@typing.final
class RecipientSealedLedgerEventPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECIPIENT_URA_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    recipient_ura: builtins.str
    @property
    def payload(self) -> global___SealedLedgerEventPayload: ...
    def __init__(
        self,
        *,
        recipient_ura: builtins.str = ...,
        payload: global___SealedLedgerEventPayload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload", "recipient_ura", b"recipient_ura"]) -> None: ...

global___RecipientSealedLedgerEventPayload = RecipientSealedLedgerEventPayload

@typing.final
class LedgerPayloadVisibility(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POLICY_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    ENCRYPTED_FIELD_NUMBER: builtins.int
    RECOVERABLE_FIELD_NUMBER: builtins.int
    RECIPIENT_URAS_FIELD_NUMBER: builtins.int
    SIZE_BYTES_FIELD_NUMBER: builtins.int
    policy: builtins.str
    """digest_only | sealed_single_recipient | sealed_explicit_recipients"""
    content_type: builtins.str
    encrypted: builtins.bool
    recoverable: builtins.bool
    size_bytes: builtins.int
    @property
    def recipient_uras(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        policy: builtins.str = ...,
        content_type: builtins.str = ...,
        encrypted: builtins.bool = ...,
        recoverable: builtins.bool = ...,
        recipient_uras: collections.abc.Iterable[builtins.str] | None = ...,
        size_bytes: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "encrypted", b"encrypted", "policy", b"policy", "recipient_uras", b"recipient_uras", "recoverable", b"recoverable", "size_bytes", b"size_bytes"]) -> None: ...

global___LedgerPayloadVisibility = LedgerPayloadVisibility

@typing.final
class LedgerVisibilitySummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARGS_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    DIAGNOSTICS_FIELD_NUMBER: builtins.int
    @property
    def args(self) -> global___LedgerPayloadVisibility: ...
    @property
    def result(self) -> global___LedgerPayloadVisibility: ...
    @property
    def diagnostics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LedgerPayloadVisibility]: ...
    def __init__(
        self,
        *,
        args: global___LedgerPayloadVisibility | None = ...,
        result: global___LedgerPayloadVisibility | None = ...,
        diagnostics: collections.abc.Iterable[global___LedgerPayloadVisibility] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["args", b"args", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["args", b"args", "diagnostics", b"diagnostics", "result", b"result"]) -> None: ...

global___LedgerVisibilitySummary = LedgerVisibilitySummary

@typing.final
class LedgerErrorRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ContextEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    SOURCE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    RETRYABLE_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    source: builtins.str
    code: builtins.str
    message: builtins.str
    retryable: builtins.bool
    @property
    def context(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        source: builtins.str = ...,
        code: builtins.str = ...,
        message: builtins.str = ...,
        retryable: builtins.bool = ...,
        context: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "context", b"context", "message", b"message", "retryable", b"retryable", "source", b"source"]) -> None: ...

global___LedgerErrorRecord = LedgerErrorRecord

@typing.final
class LedgerDiagnosticRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_UNIX_MS_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    RETRYABLE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    timestamp_unix_ms: builtins.int
    level: builtins.str
    source: builtins.str
    code: builtins.str
    message: builtins.str
    retryable: builtins.bool
    @property
    def payload(self) -> global___LedgerEventPayload: ...
    def __init__(
        self,
        *,
        timestamp_unix_ms: builtins.int = ...,
        level: builtins.str = ...,
        source: builtins.str = ...,
        code: builtins.str = ...,
        message: builtins.str = ...,
        retryable: builtins.bool = ...,
        payload: global___LedgerEventPayload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "level", b"level", "message", b"message", "payload", b"payload", "retryable", b"retryable", "source", b"source", "timestamp_unix_ms", b"timestamp_unix_ms"]) -> None: ...

global___LedgerDiagnosticRecord = LedgerDiagnosticRecord

@typing.final
class InvocationReceiptAnchor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECEIPT_URA_FIELD_NUMBER: builtins.int
    RECEIPT_HASH_FIELD_NUMBER: builtins.int
    RECEIPT_TYPE_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    TIMESTAMP_UNIX_MS_FIELD_NUMBER: builtins.int
    receipt_ura: builtins.str
    receipt_hash: builtins.str
    receipt_type: builtins.str
    state: builtins.str
    timestamp_unix_ms: builtins.int
    def __init__(
        self,
        *,
        receipt_ura: builtins.str = ...,
        receipt_hash: builtins.str = ...,
        receipt_type: builtins.str = ...,
        state: builtins.str = ...,
        timestamp_unix_ms: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["receipt_hash", b"receipt_hash", "receipt_type", b"receipt_type", "receipt_ura", b"receipt_ura", "state", b"state", "timestamp_unix_ms", b"timestamp_unix_ms"]) -> None: ...

global___InvocationReceiptAnchor = InvocationReceiptAnchor

@typing.final
class InvocationReceiptChainSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANCHORS_FIELD_NUMBER: builtins.int
    VERIFIED_FIELD_NUMBER: builtins.int
    HEAD_RECEIPT_HASH_FIELD_NUMBER: builtins.int
    VERIFICATION_DETAIL_FIELD_NUMBER: builtins.int
    verified: builtins.bool
    head_receipt_hash: builtins.str
    verification_detail: builtins.str
    @property
    def anchors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InvocationReceiptAnchor]: ...
    def __init__(
        self,
        *,
        anchors: collections.abc.Iterable[global___InvocationReceiptAnchor] | None = ...,
        verified: builtins.bool = ...,
        head_receipt_hash: builtins.str = ...,
        verification_detail: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["anchors", b"anchors", "head_receipt_hash", b"head_receipt_hash", "verification_detail", b"verification_detail", "verified", b"verified"]) -> None: ...

global___InvocationReceiptChainSummary = InvocationReceiptChainSummary

@typing.final
class InvocationCausalLink(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_INVOCATION_URA_FIELD_NUMBER: builtins.int
    SOURCE_RECEIPT_URA_FIELD_NUMBER: builtins.int
    SOURCE_RECEIPT_HASH_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    source_invocation_ura: builtins.str
    source_receipt_ura: builtins.str
    source_receipt_hash: builtins.str
    relation: builtins.str
    def __init__(
        self,
        *,
        source_invocation_ura: builtins.str = ...,
        source_receipt_ura: builtins.str = ...,
        source_receipt_hash: builtins.str = ...,
        relation: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["relation", b"relation", "source_invocation_ura", b"source_invocation_ura", "source_receipt_hash", b"source_receipt_hash", "source_receipt_ura", b"source_receipt_ura"]) -> None: ...

global___InvocationCausalLink = InvocationCausalLink

@typing.final
class InvocationTraceEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_INVOCATION_URA_FIELD_NUMBER: builtins.int
    FROM_RECEIPT_URA_FIELD_NUMBER: builtins.int
    FROM_RECEIPT_HASH_FIELD_NUMBER: builtins.int
    TO_INVOCATION_URA_FIELD_NUMBER: builtins.int
    RELATION_FIELD_NUMBER: builtins.int
    from_invocation_ura: builtins.str
    from_receipt_ura: builtins.str
    from_receipt_hash: builtins.str
    to_invocation_ura: builtins.str
    relation: builtins.str
    def __init__(
        self,
        *,
        from_invocation_ura: builtins.str = ...,
        from_receipt_ura: builtins.str = ...,
        from_receipt_hash: builtins.str = ...,
        to_invocation_ura: builtins.str = ...,
        relation: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["from_invocation_ura", b"from_invocation_ura", "from_receipt_hash", b"from_receipt_hash", "from_receipt_ura", b"from_receipt_ura", "relation", b"relation", "to_invocation_ura", b"to_invocation_ura"]) -> None: ...

global___InvocationTraceEdge = InvocationTraceEdge

@typing.final
class InvocationTraceGraph(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRACE_ID_FIELD_NUMBER: builtins.int
    RECORDS_FIELD_NUMBER: builtins.int
    EDGES_FIELD_NUMBER: builtins.int
    trace_id: builtins.str
    @property
    def records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InvocationLedgerRecord]: ...
    @property
    def edges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InvocationTraceEdge]: ...
    def __init__(
        self,
        *,
        trace_id: builtins.str = ...,
        records: collections.abc.Iterable[global___InvocationLedgerRecord] | None = ...,
        edges: collections.abc.Iterable[global___InvocationTraceEdge] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["edges", b"edges", "records", b"records", "trace_id", b"trace_id"]) -> None: ...

global___InvocationTraceGraph = InvocationTraceGraph

@typing.final
class InvocationLedgerRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOCATION_URA_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    TRACE_ID_FIELD_NUMBER: builtins.int
    SPAN_ID_FIELD_NUMBER: builtins.int
    CALLER_URA_FIELD_NUMBER: builtins.int
    CALLEE_URA_FIELD_NUMBER: builtins.int
    SUBJECT_URA_FIELD_NUMBER: builtins.int
    ABILITY_URA_FIELD_NUMBER: builtins.int
    ABILITY_NAME_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    STARTED_UNIX_MS_FIELD_NUMBER: builtins.int
    COMPLETED_UNIX_MS_FIELD_NUMBER: builtins.int
    ELAPSED_MS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    DIAGNOSTICS_FIELD_NUMBER: builtins.int
    CAUSAL_LINKS_FIELD_NUMBER: builtins.int
    RECEIPT_CHAIN_FIELD_NUMBER: builtins.int
    VISIBILITY_FIELD_NUMBER: builtins.int
    AUTHORITY_BINDING_FIELD_NUMBER: builtins.int
    invocation_ura: builtins.str
    request_id: builtins.str
    trace_id: builtins.str
    span_id: builtins.str
    caller_ura: builtins.str
    callee_ura: builtins.str
    subject_ura: builtins.str
    ability_ura: builtins.str
    ability_name: builtins.str
    state: builtins.str
    started_unix_ms: builtins.int
    completed_unix_ms: builtins.int
    elapsed_ms: builtins.int
    authority_binding: builtins.str
    """"self" | "delegated" | "bootstrap" """
    @property
    def args(self) -> global___LedgerEventPayload: ...
    @property
    def result(self) -> global___LedgerEventPayload: ...
    @property
    def error(self) -> global___LedgerErrorRecord: ...
    @property
    def diagnostics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LedgerDiagnosticRecord]: ...
    @property
    def causal_links(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InvocationCausalLink]: ...
    @property
    def receipt_chain(self) -> global___InvocationReceiptChainSummary: ...
    @property
    def visibility(self) -> global___LedgerVisibilitySummary: ...
    def __init__(
        self,
        *,
        invocation_ura: builtins.str = ...,
        request_id: builtins.str = ...,
        trace_id: builtins.str = ...,
        span_id: builtins.str = ...,
        caller_ura: builtins.str = ...,
        callee_ura: builtins.str = ...,
        subject_ura: builtins.str = ...,
        ability_ura: builtins.str = ...,
        ability_name: builtins.str = ...,
        state: builtins.str = ...,
        started_unix_ms: builtins.int = ...,
        completed_unix_ms: builtins.int = ...,
        elapsed_ms: builtins.int = ...,
        args: global___LedgerEventPayload | None = ...,
        result: global___LedgerEventPayload | None = ...,
        error: global___LedgerErrorRecord | None = ...,
        diagnostics: collections.abc.Iterable[global___LedgerDiagnosticRecord] | None = ...,
        causal_links: collections.abc.Iterable[global___InvocationCausalLink] | None = ...,
        receipt_chain: global___InvocationReceiptChainSummary | None = ...,
        visibility: global___LedgerVisibilitySummary | None = ...,
        authority_binding: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["args", b"args", "error", b"error", "receipt_chain", b"receipt_chain", "result", b"result", "visibility", b"visibility"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ability_name", b"ability_name", "ability_ura", b"ability_ura", "args", b"args", "authority_binding", b"authority_binding", "callee_ura", b"callee_ura", "caller_ura", b"caller_ura", "causal_links", b"causal_links", "completed_unix_ms", b"completed_unix_ms", "diagnostics", b"diagnostics", "elapsed_ms", b"elapsed_ms", "error", b"error", "invocation_ura", b"invocation_ura", "receipt_chain", b"receipt_chain", "request_id", b"request_id", "result", b"result", "span_id", b"span_id", "started_unix_ms", b"started_unix_ms", "state", b"state", "subject_ura", b"subject_ura", "trace_id", b"trace_id", "visibility", b"visibility"]) -> None: ...

global___InvocationLedgerRecord = InvocationLedgerRecord

@typing.final
class AbilityTarget(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ABILITY_NAME_FIELD_NUMBER: builtins.int
    FUNCTION_NAME_FIELD_NUMBER: builtins.int
    ability_name: builtins.str
    function_name: builtins.str
    def __init__(
        self,
        *,
        ability_name: builtins.str = ...,
        function_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ability_name", b"ability_name", "function_name", b"function_name"]) -> None: ...

global___AbilityTarget = AbilityTarget

@typing.final
class InvocationTarget(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ABILITY_FIELD_NUMBER: builtins.int
    @property
    def ability(self) -> global___AbilityTarget: ...
    def __init__(
        self,
        *,
        ability: global___AbilityTarget | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ability", b"ability", "typed_target", b"typed_target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ability", b"ability", "typed_target", b"typed_target"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["typed_target", b"typed_target"]) -> typing.Literal["ability"] | None: ...

global___InvocationTarget = InvocationTarget

@typing.final
class ContentMeta(google.protobuf.message.Message):
    """─── Protocol: Multimedia Metadata ──────────────────────

    Multimedia metadata for rich content payloads.
    All fields are optional; populate only what applies.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_FIELD_NUMBER: builtins.int
    CHANNELS_FIELD_NUMBER: builtins.int
    CODEC_FIELD_NUMBER: builtins.int
    DURATION_SEC_FIELD_NUMBER: builtins.int
    FRAME_RATE_FIELD_NUMBER: builtins.int
    width: builtins.int
    """pixels (image/video)"""
    height: builtins.int
    """pixels (image/video)"""
    sample_rate: builtins.int
    """Hz (audio)"""
    channels: builtins.int
    """audio channels"""
    codec: builtins.str
    """e.g. "h264", "opus", "png" """
    duration_sec: builtins.float
    """seconds (audio/video)"""
    frame_rate: builtins.float
    """fps (video)"""
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
        sample_rate: builtins.int = ...,
        channels: builtins.int = ...,
        codec: builtins.str = ...,
        duration_sec: builtins.float = ...,
        frame_rate: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channels", b"channels", "codec", b"codec", "duration_sec", b"duration_sec", "frame_rate", b"frame_rate", "height", b"height", "sample_rate", b"sample_rate", "width", b"width"]) -> None: ...

global___ContentMeta = ContentMeta

@typing.final
class PayloadRef(google.protobuf.message.Message):
    """─── Protocol: Large Payload Reference ──────────────────

    Reference to a large or out-of-band payload managed by the
    canonical runtime. Identified by a full URA.

    Used instead of inline bytes when payload exceeds practical
    gRPC message limits or needs independent lifecycle management.
    Recommendation: once a serialized payload exceeds ~1 MiB, prefer
    PayloadRef over inline request/response bytes to keep RPC frames small
    and to make retries/resume semantics independent from a single call.
    Storage backends are an implementation detail invisible to callers —
    the protocol only exposes the full URA.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    URA_FIELD_NUMBER: builtins.int
    DIGEST_FIELD_NUMBER: builtins.int
    SIZE_BYTES_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    EXPIRES_AT_UNIX_MS_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    ura: builtins.str
    """canonical payload URA"""
    digest: builtins.str
    """"sha256:<hex>" integrity hash"""
    size_bytes: builtins.int
    expires_at_unix_ms: builtins.int
    """0 = no expiry"""
    @property
    def content(self) -> global___ContentEnvelope:
        """content negotiation (type + encoding + schema + meta)"""

    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        ura: builtins.str = ...,
        digest: builtins.str = ...,
        size_bytes: builtins.int = ...,
        content: global___ContentEnvelope | None = ...,
        expires_at_unix_ms: builtins.int = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["content", b"content"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "digest", b"digest", "expires_at_unix_ms", b"expires_at_unix_ms", "labels", b"labels", "size_bytes", b"size_bytes", "ura", b"ura"]) -> None: ...

global___PayloadRef = PayloadRef
