from typing import Any

class _Message:
    def __init__(self, **kwargs: Any) -> None: ...

class Envelope(_Message): ...
class SubjectIdentity(_Message): ...
class ContentEnvelope(_Message): ...
class InvocationTarget(_Message): ...
class AbilityTarget(_Message): ...
class AgentIdentity(_Message): ...
class CallerSignature(_Message): ...
class CausalContext(_Message): ...
class Empty(_Message): ...
class ReceiptList(_Message): ...
class MerkleRoot(_Message): ...
class ReceiptRef(_Message): ...

INVOCATION_STATE_ACCEPTED: int
INVOCATION_STATE_ADMITTED: int
INVOCATION_STATE_DISPATCHED: int
INVOCATION_STATE_RUNNING: int
INVOCATION_STATE_COMPLETED: int
INVOCATION_STATE_FAILED: int
INVOCATION_STATE_TIMED_OUT: int
INVOCATION_STATE_CANCELLED: int

class ErrorStage:
    @staticmethod
    def Name(value: int) -> str: ...
