"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
File: core/proto/axon/v1/types.proto
Description: Source-of-truth canonical runtime envelopes, proof facts, receipts, and content contracts.

Protocol Responsibility:
- Defines the generic wire types reused by invocation and payload transfer.
- Preserves complete invocation-tuple, proof, content, and terminal-state semantics.

Implementation Approach:
- Keeps common enums and messages in one schema so service protos compose on a stable base contract.
- Documents protocol guarantees and URA routing conventions close to the shared type definitions.

Usage Contract:
- Changes here have broad compatibility impact and must remain wire-safe for generated clients.
- Regenerate dependent language artifacts after updating shared types or enums.

Architectural Position:
- Canonical runtime protocol contract. Product directory, deployment, policy,
  and topology models are downstream concerns.

Author: Silan.Hu
Email: silan.hu@u.nus.edu
Copyright (c) 2026-2027 easynet. All rights reserved.
"""

import abc
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...
