#!/usr/bin/env python3
"""Case01 ARIS native runtime mock.

Producer-side AAL is still a contract (BCC deferred), so this file provides a
pragmatic local runtime that materializes ARIS-style artifacts while preserving
ontology boundaries:

- public abilities are explicit function calls
- private skill logic stays inside this runtime
- all calls emit ability_graph_traces for auditability
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import textwrap
from pathlib import Path
from typing import Any, Dict, List


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def short_json(data: Any, limit: int = 400) -> str:
    raw = json.dumps(data, ensure_ascii=True)
    if len(raw) <= limit:
        return raw
    return raw[: limit - 3] + "..."


class ArisNativeRuntime:
    def __init__(self, workspace: Path) -> None:
        self.workspace = workspace
        self.trace_file = self.workspace / "ability_graph_traces.json"
        self.manifest_file = self.workspace / "MANIFEST.md"
        self.memory_graph_file = self.workspace / "research-wiki/graph/memory_graph.json"
        self._ensure_workspace_layout()

    def _ensure_workspace_layout(self) -> None:
        dirs = [
            "idea-stage/docs",
            "refine-logs",
            "review-stage",
            "paper",
            "research-wiki/graph",
            "artifacts",
        ]
        for rel in dirs:
            (self.workspace / rel).mkdir(parents=True, exist_ok=True)

        claudemd = self.workspace / "CLAUDE.md"
        if not claudemd.exists():
            claudemd.write_text(
                textwrap.dedent(
                    """\
                    # ARIS Case01 Dashboard

                    ## Pipeline Status
                    - Stage: bootstrap
                    - Last update (UTC): TBD

                    ## Notes
                    - This workspace is generated by gallery/case01-aris/runtime/aris_native_runtime.py.
                    - Treat this as a local stand-in for ability graph memory/workflow state.
                    """
                ),
                encoding="utf-8",
            )

        findings = self.workspace / "findings.md"
        if not findings.exists():
            findings.write_text(
                "# Findings\n\n", encoding="utf-8"
            )

        if not self.manifest_file.exists():
            self.manifest_file.write_text(
                "# Output Manifest\n\n"
                "| timestamp_utc | ability | file | stage | description |\n"
                "| --- | --- | --- | --- | --- |\n",
                encoding="utf-8",
            )

        if not self.trace_file.exists():
            self.trace_file.write_text("[]\n", encoding="utf-8")

        if not self.memory_graph_file.exists():
            self.memory_graph_file.write_text(
                json.dumps(
                    {
                        "papers": [],
                        "ideas": [],
                        "experiments": [],
                        "claims": [],
                        "updated_at_utc": utc_now(),
                    },
                    indent=2,
                    ensure_ascii=True,
                )
                + "\n",
                encoding="utf-8",
            )

    def _load_traces(self) -> List[Dict[str, Any]]:
        try:
            return json.loads(self.trace_file.read_text(encoding="utf-8"))
        except Exception:
            return []

    def _save_traces(self, traces: List[Dict[str, Any]]) -> None:
        self.trace_file.write_text(
            json.dumps(traces, indent=2, ensure_ascii=True) + "\n",
            encoding="utf-8",
        )

    def _append_manifest(self, ability: str, file_path: Path, stage: str, description: str) -> None:
        row = f"| {utc_now()} | {ability} | {file_path.relative_to(self.workspace)} | {stage} | {description} |\n"
        with self.manifest_file.open("a", encoding="utf-8") as f:
            f.write(row)

    def _write_text(self, ability: str, rel_path: str, content: str, stage: str, description: str) -> Path:
        path = self.workspace / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        self._append_manifest(ability, path, stage, description)
        return path

    def _append_findings(self, title: str, detail: str) -> None:
        findings = self.workspace / "findings.md"
        with findings.open("a", encoding="utf-8") as f:
            f.write(f"## {utc_now()} - {title}\n")
            f.write(f"- {detail}\n\n")

    def _load_memory_graph(self) -> Dict[str, Any]:
        return json.loads(self.memory_graph_file.read_text(encoding="utf-8"))

    def _save_memory_graph(self, data: Dict[str, Any]) -> None:
        data["updated_at_utc"] = utc_now()
        self.memory_graph_file.write_text(
            json.dumps(data, indent=2, ensure_ascii=True) + "\n",
            encoding="utf-8",
        )

    def run_ability(self, ability: str, args: Dict[str, Any]) -> Dict[str, Any]:
        start = utc_now()

        handlers = {
            "aris_bootstrap": self._ability_bootstrap,
            "aris_run_idea_discovery": self._ability_run_idea_discovery,
            "aris_run_experiments": self._ability_run_experiments,
            "aris_run_auto_review": self._ability_run_auto_review,
            "aris_write_narrative": self._ability_write_narrative,
            "aris_persist_artifact": self._ability_persist_artifact,
            "aris_load_artifact": self._ability_load_artifact,
            "aris_metrics_ping": self._ability_metrics_ping,
        }
        if ability not in handlers:
            raise ValueError(f"unknown ability: {ability}")

        output = handlers[ability](args)
        end = utc_now()

        traces = self._load_traces()
        traces.append(
            {
                "trace_id": f"trace-{len(traces) + 1:03d}",
                "ability": ability,
                "started_at_utc": start,
                "completed_at_utc": end,
                "inputs": args,
                "output_summary": short_json(output),
            }
        )
        self._save_traces(traces)
        return output

    def _ability_bootstrap(self, args: Dict[str, Any]) -> Dict[str, Any]:
        ability = "aris_bootstrap"
        project = args.get("project", "case01-aris")
        direction = args.get("direction", "unspecified")
        stage = args.get("stage", "bootstrap")

        self._write_text(
            ability,
            "idea-stage/docs/research_contract.md",
            textwrap.dedent(
                f"""\
                # Research Contract

                - project: {project}
                - direction: {direction}
                - stage: {stage}
                - generated_at_utc: {utc_now()}

                ## Problem Anchor
                We optimize for a reproducible paper-improvement loop with explicit evidence.

                ## Non-goals
                - no hidden state outside workspace files
                - no direct private-skill invocation from external callers
                """
            ),
            "bootstrap",
            "initialized research contract",
        )

        self._write_text(
            ability,
            "CLAUDE.md",
            textwrap.dedent(
                f"""\
                # ARIS Case01 Dashboard

                ## Pipeline Status
                - Stage: {stage}
                - Last update (UTC): {utc_now()}
                - Direction: {direction}

                ## Next
                - Run idea discovery
                - Build experiment plan
                - Enter auto-review loop
                """
            ),
            "bootstrap",
            "updated dashboard",
        )

        memory = self._load_memory_graph()
        memory["papers"] = [
            {
                "id": "paper-001",
                "title": "Reference baseline for ARIS case",
                "source": "local-seed",
            }
        ]
        self._save_memory_graph(memory)

        return {
            "status": "ok",
            "project_root": str(self.workspace),
            "direction": direction,
        }

    def _ability_run_idea_discovery(self, args: Dict[str, Any]) -> Dict[str, Any]:
        ability = "aris_run_idea_discovery"
        direction = args.get("direction", "unspecified")

        idea_report = textwrap.dedent(
            f"""\
            # IDEA_REPORT

            direction: {direction}
            generated_at_utc: {utc_now()}

            ## Ranked Ideas
            1. Structured reviewer-memory constrained refinement (recommended)
               - pilot_signal: positive (+6.1%)
               - novelty: confirmed in local search set
            2. Adaptive ablation budget controller
               - pilot_signal: weak positive (+2.4%)
               - novelty: partial overlap with prior work
            3. One-shot full-pipeline write
               - pilot_signal: negative
               - novelty: low

            ## Recommendation
            Proceed with Idea 1 and materialize experiments via EXPERIMENT_PLAN.md.
            """
        )
        proposal = textwrap.dedent(
            """\
            # FINAL_PROPOSAL

            ## Core Thesis
            Couple reviewer memory with bounded-round implementation updates to improve convergence stability.

            ## Dominant Contribution
            A reproducible review-to-fix loop with explicit state recovery and claim tracking.
            """
        )
        experiment_plan = textwrap.dedent(
            """\
            # EXPERIMENT_PLAN

            ## Claim Blocks
            - C1: memory-aware review loop converges faster than no-memory baseline.
            - C2: bounded rounds (<= 4) preserve quality while limiting compute.

            ## First Runs
            1. baseline_no_memory
            2. memory_medium_difficulty
            3. memory_hard_difficulty
            """
        )

        self._write_text(ability, "idea-stage/IDEA_REPORT.md", idea_report, "idea", "generated ranked ideas")
        self._write_text(ability, "refine-logs/FINAL_PROPOSAL.md", proposal, "refine", "generated final proposal")
        self._write_text(
            ability,
            "refine-logs/EXPERIMENT_PLAN.md",
            experiment_plan,
            "refine",
            "generated experiment plan",
        )

        self._append_findings(
            "idea-discovery",
            "Top idea selected: reviewer-memory constrained refinement",
        )

        memory = self._load_memory_graph()
        memory["ideas"].append(
            {
                "id": "idea-001",
                "title": "reviewer-memory constrained refinement",
                "status": "selected",
            }
        )
        memory["claims"] = [
            {"id": "C1", "status": "planned"},
            {"id": "C2", "status": "planned"},
        ]
        self._save_memory_graph(memory)

        return {
            "status": "ok",
            "selected_idea": "idea-001",
            "outputs": [
                "idea-stage/IDEA_REPORT.md",
                "refine-logs/FINAL_PROPOSAL.md",
                "refine-logs/EXPERIMENT_PLAN.md",
            ],
        }

    def _ability_run_experiments(self, args: Dict[str, Any]) -> Dict[str, Any]:
        ability = "aris_run_experiments"
        payload = args.get("payload", {})
        if not isinstance(payload, dict):
            payload = {}
        plan = args.get("plan", payload.get("plan", "from refine-logs/EXPERIMENT_PLAN.md"))
        budget = args.get("budget", payload.get("budget", "small"))

        results = textwrap.dedent(
            f"""\
            # EXPERIMENT_RESULTS

            generated_at_utc: {utc_now()}
            budget: {budget}
            plan_ref: {plan}

            ## Summary
            - baseline_no_memory: score 5.1
            - memory_medium_difficulty: score 6.3
            - memory_hard_difficulty: score 6.8
            """
        )
        exp_log = textwrap.dedent(
            """\
            # EXPERIMENT_LOG

            - run_id: run-001, config: baseline_no_memory, score: 5.1
            - run_id: run-002, config: memory_medium_difficulty, score: 6.3
            - run_id: run-003, config: memory_hard_difficulty, score: 6.8
            """
        )

        self._write_text(ability, "refine-logs/EXPERIMENT_RESULTS.md", results, "experiment", "generated experiment results")
        self._write_text(ability, "refine-logs/EXPERIMENT_LOG.md", exp_log, "experiment", "logged experiment runs")

        self._append_findings(
            "experiments",
            "Memory-aware settings outperform baseline by +1.7 absolute score",
        )

        memory = self._load_memory_graph()
        memory["experiments"].append(
            {
                "id": "run-batch-001",
                "budget": budget,
                "status": "completed",
            }
        )
        for claim in memory.get("claims", []):
            if claim["id"] in {"C1", "C2"}:
                claim["status"] = "supported"
        self._save_memory_graph(memory)

        return {
            "status": "ok",
            "best_score": 6.8,
            "outputs": [
                "refine-logs/EXPERIMENT_RESULTS.md",
                "refine-logs/EXPERIMENT_LOG.md",
            ],
        }

    def _ability_run_auto_review(self, args: Dict[str, Any]) -> Dict[str, Any]:
        ability = "aris_run_auto_review"
        topic = args.get("topic", "unspecified")
        difficulty = args.get("difficulty", "medium")
        rounds = int(args.get("rounds", 2))

        score = 5.6
        lines: List[str] = [
            "# AUTO_REVIEW",
            "",
            f"topic: {topic}",
            f"difficulty: {difficulty}",
            f"generated_at_utc: {utc_now()}",
            "",
        ]

        for round_idx in range(1, max(rounds, 1) + 1):
            score += 0.7
            lines.extend(
                [
                    f"## Round {round_idx}",
                    f"- reviewer_score: {score:.1f}/10",
                    "- weakness: evidence linkage could be tighter",
                    "- applied_fix: tied each claim to concrete experiment rows",
                    "",
                ]
            )

        verdict = "ready" if score >= 6.0 else "not-ready"
        lines.extend([
            "## Final",
            f"- score: {score:.1f}/10",
            f"- verdict: {verdict}",
            "",
        ])

        self._write_text(
            ability,
            "review-stage/AUTO_REVIEW.md",
            "\n".join(lines),
            "review",
            "completed auto-review rounds",
        )

        review_state = {
            "round": rounds,
            "status": "completed",
            "difficulty": difficulty,
            "last_score": round(score, 1),
            "last_verdict": verdict,
            "timestamp": utc_now(),
        }
        self._write_text(
            ability,
            "review-stage/REVIEW_STATE.json",
            json.dumps(review_state, indent=2, ensure_ascii=True) + "\n",
            "review",
            "persisted review state",
        )

        self._append_findings(
            "auto-review",
            f"Loop converged in {rounds} rounds with final score {score:.1f}",
        )

        return {
            "status": "ok",
            "final_score": round(score, 1),
            "verdict": verdict,
        }

    def _ability_write_narrative(self, args: Dict[str, Any]) -> Dict[str, Any]:
        ability = "aris_write_narrative"
        topic = args.get("topic", "unspecified")

        narrative = textwrap.dedent(
            f"""\
            # NARRATIVE_REPORT

            topic: {topic}
            generated_at_utc: {utc_now()}

            ## Problem
            Build a bounded, auditable autonomous research loop that can run overnight.

            ## Method
            Combine idea discovery, experiment execution, and reviewer-memory guided iterative fixes.

            ## Key Results
            - score improved from 5.1 (baseline) to 6.8 (memory-aware)
            - review loop reached ready-for-submission threshold in <= 4 rounds

            ## Remaining Risks
            - external validity on larger benchmark suites
            - tighter ablation coverage for reviewer objections
            """
        )

        paper_tex = textwrap.dedent(
            r"""\
            \documentclass{article}
            \begin{document}
            \section*{Case01 ARIS Draft}
            This draft is generated by the local case runtime as a handoff artifact.
            \end{document}
            """
        )

        self._write_text(ability, "NARRATIVE_REPORT.md", narrative, "narrative", "generated narrative handoff")
        self._write_text(ability, "paper/main.tex", paper_tex, "paper", "generated latex draft")

        return {
            "status": "ok",
            "outputs": ["NARRATIVE_REPORT.md", "paper/main.tex"],
        }

    def _ability_persist_artifact(self, args: Dict[str, Any]) -> Dict[str, Any]:
        ability = "aris_persist_artifact"
        stage = args.get("stage", "unknown")
        payload = args.get("payload", {})

        out = {
            "stage": stage,
            "saved_at_utc": utc_now(),
            "payload": payload,
        }
        path = self._write_text(
            ability,
            f"artifacts/{stage}_snapshot.json",
            json.dumps(out, indent=2, ensure_ascii=True) + "\n",
            "artifact",
            f"persisted {stage} snapshot",
        )
        return {"status": "ok", "artifact": str(path)}

    def _ability_load_artifact(self, args: Dict[str, Any]) -> Dict[str, Any]:
        stage = args.get("stage", "idea")
        mapping = {
            "idea": "refine-logs/FINAL_PROPOSAL.md",
            "review": "review-stage/AUTO_REVIEW.md",
            "narrative": "NARRATIVE_REPORT.md",
        }
        rel = mapping.get(stage, "refine-logs/FINAL_PROPOSAL.md")
        path = self.workspace / rel
        if not path.exists():
            return {"status": "missing", "stage": stage, "content": ""}
        return {
            "status": "ok",
            "stage": stage,
            "content": path.read_text(encoding="utf-8")[:1200],
        }

    def _ability_metrics_ping(self, args: Dict[str, Any]) -> Dict[str, Any]:
        ability = "aris_metrics_ping"
        event = args.get("event", "unknown")
        metrics_path = self.workspace / "artifacts/metrics.log"
        metrics_path.parent.mkdir(parents=True, exist_ok=True)
        with metrics_path.open("a", encoding="utf-8") as f:
            f.write(f"{utc_now()} {event}\n")
        self._append_manifest(ability, metrics_path, "metrics", "logged metric event")
        return {"status": "ok", "event": event, "file": str(metrics_path)}

    def run_demo(self, direction: str, topic: str, rounds: int, difficulty: str) -> Dict[str, Any]:
        bootstrap = self.run_ability(
            "aris_bootstrap",
            {
                "project": "case01-aris",
                "direction": direction,
                "stage": "bootstrap",
            },
        )
        idea = self.run_ability(
            "aris_run_idea_discovery",
            {"direction": direction, "constraints": bootstrap["project_root"]},
        )
        experiments = self.run_ability(
            "aris_run_experiments",
            {"plan": "refine-logs/EXPERIMENT_PLAN.md", "budget": "small"},
        )
        review = self.run_ability(
            "aris_run_auto_review",
            {
                "topic": topic,
                "difficulty": difficulty,
                "rounds": rounds,
            },
        )
        narrative = self.run_ability("aris_write_narrative", {"topic": topic})
        snapshot = self.run_ability(
            "aris_persist_artifact",
            {"stage": "narrative", "payload": narrative},
        )
        ping = self.run_ability(
            "aris_metrics_ping",
            {"event": "case01_demo_completed"},
        )
        return {
            "workspace": str(self.workspace),
            "bootstrap": bootstrap,
            "idea": idea,
            "experiments": experiments,
            "review": review,
            "narrative": narrative,
            "snapshot": snapshot,
            "metrics": ping,
        }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Case01 ARIS native runtime")
    sub = parser.add_subparsers(dest="command", required=True)

    demo = sub.add_parser("demo", help="run local end-to-end demo")
    demo.add_argument("--workspace", default="gallery/case01-aris/runtime/demo-workspace")
    demo.add_argument("--direction", required=True)
    demo.add_argument("--topic", required=True)
    demo.add_argument("--rounds", type=int, default=2)
    demo.add_argument("--difficulty", default="medium")

    ability = sub.add_parser("ability", help="run one ability")
    ability.add_argument("ability_name")
    ability.add_argument("--workspace", default="gallery/case01-aris/runtime/demo-workspace")
    ability.add_argument("--project", default="case01-aris")
    ability.add_argument("--direction", default="factorized gap in discrete diffusion LMs")
    ability.add_argument("--topic", default="factorized gap in discrete diffusion LMs")
    ability.add_argument("--stage", default="idea")
    ability.add_argument("--rounds", type=int, default=2)
    ability.add_argument("--difficulty", default="medium")
    ability.add_argument("--payload", default="{}")
    ability.add_argument("--event", default="manual_event")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    runtime = ArisNativeRuntime(Path(args.workspace))

    if args.command == "demo":
        result = runtime.run_demo(
            direction=args.direction,
            topic=args.topic,
            rounds=args.rounds,
            difficulty=args.difficulty,
        )
        print(json.dumps(result, indent=2, ensure_ascii=True))
        return

    payload: Any
    try:
        payload = json.loads(args.payload)
    except json.JSONDecodeError:
        payload = {"raw": args.payload}

    ability_args = {
        "project": args.project,
        "direction": args.direction,
        "topic": args.topic,
        "stage": args.stage,
        "rounds": args.rounds,
        "difficulty": args.difficulty,
        "payload": payload,
        "event": args.event,
    }
    result = runtime.run_ability(args.ability_name, ability_args)
    print(json.dumps(result, indent=2, ensure_ascii=True))


if __name__ == "__main__":
    main()
