// EasyNet CLI — Federation Invoke Helper (PR-N1 commit 8/N)
// =========================================================
//
// File: src/support/federation_invoke.rs
// Description: CLI bridge from `easynet ability invoke <ability-ura>
//              --node <peer-ura>` to the local daemon's gRPC
//              `Invocation::invoke` with `function_name="federation.
//              forward_invoke"`. This is what unblocks the answer-
//              sheet acceptance gate raised by perf-engineer +
//              reviewer + architect during PR-N1 review:
//              commits 1-7/N ship the
//              daemon-to-daemon wire, this commit ships the user-
//              CLI-command → daemon entry point.
//
// Wire shape
// ----------
// 1. Caller passes `(ability_ura, args, node_ura)`. `node_ura` must
//    be a canonical Axon Device or Hub URA; non-canonical inputs
//    surface as a typed error before any IPC.
// 2. The helper dials the local daemon's UDS-bound gRPC
//    `Invocation` server (default `~/.easynet/daemon.sock`).
// 3. It sends an `InvokeRequest` whose `function_name` is
//    `federation.forward_invoke` and whose `arguments` is the
//    JSON `{target_ura, inner_envelope_b64}` shape that
//    `federation_wrappers::ForwardInvokeRequest` deserialises.
//    The inner envelope carries the original `(ability_ura, args)`
//    pair so the peer-side daemon can dispatch it once it lands.
// 4. The local daemon's `dispatch_federation_forward_invoke` runs
//    the cross-realm routing landed in PR-N1 commit 3b/N, dials
//    via the `CrossHubDialer` that PR-N1 commit 6/N wires at boot,
//    and returns the peer daemon's response.
//
// Why this lives in `support/` and not `facade/cli/`
// ---------------------------------------------------
// The IPC + gRPC plumbing this helper does is reusable across CLI
// subcommands (a future `easynet mission run --node X` would do
// the same dial + frame). Putting it under `support/` matches the
// existing `local_invoke.rs` placement (the helper that backs every
// CLI subcommand's local-only path) so a reader looking for
// "where does the CLI talk to the daemon" finds both helpers in
// one directory.
//
// Feature gating
// --------------
// `axon-pb` feature gates the entire module. Production builds run
// with `axon-pb` on; minimal builds (no daemon transport) can drop
// the cross-hub bridge along with the rest of the gRPC stack.
//
// Author: Silan.Hu <silan.hu@u.nus.edu>
// Copyright (c) 2026 EasyNet. All rights reserved.

use std::time::Duration;

use anyhow::{anyhow, bail, Context};
use base64::{engine::general_purpose::STANDARD as BASE64_STANDARD, Engine as _};
use serde_json::{json, Value};

use crate::runtime::local_invocation_identity::LOCAL_SYSTEM_AGENT_URA;
use crate::services::invocation_transport::ProtoEnvelope;
use crate::services::self_identity::LocalDaemonSigner;
use easynet_axon::pb::axon::v1::invocation_client::InvocationClient;
use easynet_axon::pb::axon::v1::{
    InvocationState as WireInvocationState, InvokeRequest, InvokeResponse,
};
use easynet_axon::ura::{parse_ura, URAKind};

/// Validate a `--node` argument as a canonical Axon Device or Hub URA.
/// Returns the URA string when it parses; surfaces a typed error
/// when it doesn't, with the exact wire-shape we expect quoted in
/// the message so the operator can fix the typo.
///
/// The grammar decision belongs to Axon. This helper only applies
/// the CLI policy distinction after parsing: `--node` may target a
/// Device or Hub URA, never a hosted Agent/User/Ability/Resource.
/// Hub targets must be generated by Axon's `hub_ura(realm)` builder,
/// whose clean protocol identity is `easynet:///r/<realm>/hub`.
pub fn parse_node_ura(node: &str) -> anyhow::Result<String> {
    let trimmed = node.trim();
    let parsed = parse_ura(trimmed).map_err(|err| {
        anyhow::anyhow!(
            "--node `{trimmed}` is not a canonical Axon Device or Hub URA: {err}. \
             A bare hostname or `https://...` URL is not accepted. \
             {URA_DISCOVERY_HINT}"
        )
    })?;

    match parsed.kind {
        URAKind::Device => Ok(trimmed.to_string()),
        URAKind::Hub => Ok(trimmed.to_string()),
        other => bail!(
            "--node `{trimmed}` is a canonical Axon URA, but not a Device or Hub target. \
             Got kind={other}. \
             {URA_DISCOVERY_HINT}"
        ),
    }
}

/// Operator-actionable hint appended to every `--node` parse failure.
/// Names the four places a real URA can come from today, ordered
/// most-helpful-first. Centralised so the wording stays byte-identical
/// across both `parse_node_ura` failure arms — operators can grep one
/// substring across logs.
///
/// **PR-N1 user-flow review catch**: PR-N1 ships the CLI
/// invocation surface (commit 8/N) but cross-hub URA discovery
/// from a remote machine without manual config is PR-N3
/// territory (cross-realm directory federation, not yet shipped).
/// Until PR-N3 lands, operators construct URAs by hand from the
/// sources below; the error message points at them.
const URA_DISCOVERY_HINT: &str = "Where to find a canonical URA today (until PR-N3 cross-realm \
     directory federation ships): \
     (1) `cat ~/.easynet/credentials.json` on the target machine — \
     concat `easynet:///r/<realm>/device/<node_id>` from the fields. \
     (2) `cat ~/.easynet/daemon-config.toml` and read the \
     `[daemon.federated_peers]` table — keys are realms the \
     local daemon already trusts. \
     (3) `cat /etc/easynet/realm-trust.toml` and read \
     `[[trusted_agent]]` blocks with `role = \"hub\"` — those \
     are the peer hubs the cross-hub dialer can reach. \
     (4) `easynet ability list` — local-realm only \
     today; cross-realm enumeration ships in PR-N3.";

/// Complete caller-side target for `federation.forward_invoke`.
///
/// This value object is the root fix for the execution-target/callee-owner
/// split. `execution_target_ura` is the node or hub the local daemon sends the
/// frame to. `callee_ura` is the Agent/Device/Hub identity that advertises the
/// AbilityDescriptor. They are equal for device-owned system abilities and
/// intentionally different for hosted-agent abilities executed on a device.
///
/// What this is not: it is not a route answer. The remote daemon/hub remains
/// responsible for proving that a hosted Agent is actually runnable at the
/// execution target. This object only prevents the CLI from corrupting the
/// signed Invocation tuple before the resolver gets a chance to decide.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct RemoteAbilityInvocationTarget {
    execution_target_ura: String,
    ability_ura: String,
    callee_ura: String,
    public_ability: String,
}

impl RemoteAbilityInvocationTarget {
    /// Project a target-owned system ability selector into a full remote
    /// invocation target.
    ///
    /// Use this for command adapters whose product contract is "call this
    /// device/hub-owned system ability on `--node`". It is deliberately named
    /// target-owned so it is not reused for arbitrary Ability URAs.
    pub(crate) fn for_target_owned_selector(
        execution_target_ura: &str,
        selector: &str,
    ) -> anyhow::Result<Self> {
        validate_forward_target_ura(execution_target_ura)?;
        let public_ability = crate::ura::owner_local_ability_name(execution_target_ura, selector);
        let ability_ura = crate::ura::owner_ability_ura(execution_target_ura, &public_ability)
            .ok_or_else(|| {
                anyhow::anyhow!("derive ability URA for {execution_target_ura} {public_ability}")
            })?;
        Self::from_ability_ura(execution_target_ura, &ability_ura)
    }

    /// Accept an already-canonical Ability URA and bind it to an execution
    /// target without rewriting the Ability owner.
    pub(crate) fn from_ability_ura(
        execution_target_ura: &str,
        ability_ura: &str,
    ) -> anyhow::Result<Self> {
        validate_forward_target_ura(execution_target_ura)?;
        let trimmed = ability_ura.trim();
        let selector = crate::ura::AbilitySelector::parse(trimmed)?;
        validate_forward_execution_target(execution_target_ura, &selector)?;
        Ok(Self {
            execution_target_ura: execution_target_ura.trim().to_string(),
            ability_ura: trimmed.to_string(),
            callee_ura: selector.owner_ura().to_string(),
            public_ability: selector.public_name().to_string(),
        })
    }

    /// Borrow the canonical URA for the transport helper.
    pub(crate) fn as_str(&self) -> &str {
        &self.ability_ura
    }

    /// Node or hub that receives the forwarding request.
    pub(crate) fn execution_target_ura(&self) -> &str {
        &self.execution_target_ura
    }
}

pub(crate) fn invoke_via_federation_forward_target(
    target: &RemoteAbilityInvocationTarget,
    args: Value,
    caller_ura: Option<&str>,
) -> anyhow::Result<Value> {
    invoke_via_federation_forward_target_with_timeout(
        target,
        args,
        caller_ura,
        Duration::from_secs(30),
    )
}

pub(crate) fn invoke_via_federation_forward_target_with_timeout(
    target: &RemoteAbilityInvocationTarget,
    args: Value,
    caller_ura: Option<&str>,
    timeout: Duration,
) -> anyhow::Result<Value> {
    let socket_path = crate::support::local_daemon_grpc::resolve_socket_path();
    if !crate::support::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    // The daemon's `federation.forward_invoke` request shape per
    // DEC-N4 §2.1: `ForwardInvokeRequest { target_ura,
    // inner_envelope_b64, causal_context_bytes,
    // forward_deadline_ms }`. The inner envelope carries the
    // original `(ability_ura, args, call_id)` tuple as a JSON blob;
    // PR-N1's daemon-to-daemon wire forwards this opaquely. The
    // outer audit / deadline fields round-trip verbatim so
    // PR-N5's InvocationReceipt can stamp causal_context.list and
    // DEC-N5 §3 can derive the inner deadline. PR-N2 will
    // introduce AXIOM mapping rewrite + signature; PR-N1 ships
    // the unsigned shape.
    //
    // DEC-N4 §2.1: a client-minted `call_id` is required so the
    // daemon's `ForwardInvokeResponse.correlation_call_id` can
    // thread it back to whichever bidi was waiting for the
    // result. We use a nanosecond+rng id; the value is opaque
    // to the daemon, only the round-trip equality matters.
    let call_id = generate_call_id();
    // Sign over the exact byte shape the hub re-serialises: the hub
    // decodes `args` to a `serde_json::Value` and re-encodes it before
    // pushing the dispatch frame, so the claim must cover to_vec(Value)
    // of the SAME value — not whatever bytes the operator typed.
    let args_bytes_for_claim =
        serde_json::to_vec(&args).context("serialise args for origin-caller claim")?;
    let origin_caller =
        caller_ura.and_then(|caller| device_origin_claim(caller, target, &args_bytes_for_claim));
    let inner_payload = json!({
        "ability_ura": target.as_str(),
        "args": args,
        "call_id": call_id,
    });
    let inner_envelope_bytes = serde_json::to_vec(&inner_payload)
        .context("serialise inner ability call as forward_invoke payload")?;
    let inner_envelope_b64 = BASE64_STANDARD.encode(&inner_envelope_bytes);

    // DEC-N4 §2.1 audit-chain + deadline fields. The CLI bridge
    // is the lowest-level synchronous initiator; it has no prior
    // `ForwardReceipt` to chain (those are PR-N5 territory). The
    // caller-side timeout is propagated as `forward_deadline_ms`, so
    // the peer hub can bound the forwarded work instead of applying
    // a silent default that disagrees with the CLI surface.
    // Once `<self>.invoke_remote` initiator becomes the upstream
    // caller (instead of a direct CLI dial), it will populate
    // both with real values per PR-N5 §1 / DEC-N5 §3.
    //
    // Build the request through the canonical `ForwardInvokeRequest`
    // type rather than a hand-rolled `json!` object. The type carries
    // base64 serde for `causal_context_bytes` (the daemon's
    // deserializer rejects a JSON byte-array with `invalid type:
    // sequence`); serialising the struct guarantees the wire shape can
    // never drift from the contract the daemon parses.
    let forward_request = easynet_axon::ForwardInvokeRequest {
        target_ura: target.execution_target_ura().to_string(),
        inner_envelope_b64,
        causal_context_bytes: Vec::new(),
        forward_deadline_ms: u64::try_from(timeout.as_millis()).unwrap_or(u64::MAX),
        origin_caller,
    };
    let forward_args_bytes =
        serde_json::to_vec(&forward_request).context("serialise ForwardInvokeRequest")?;

    // Build the outer envelope. When the CLI is only asking its local
    // daemon control plane to forward work, the caller is the daemon's
    // process-local `_system.local` subject, not a guessed device/user
    // identity. Explicit caller URAs still sign through their own keyring
    // identity.
    //
    // AXIOM §A1 requires both `caller` and `callee`; the daemon's
    // admission gate rejects an envelope missing either with
    // `AXON_AXIOM_ENVELOPE_INCOMPLETE:callee_missing`. For a
    // `federation.forward_invoke` call the `callee` remains the
    // target node/peer for routing, while the descriptor-bound
    // `subject` is the target-owned federation ability. Hub/User
    // identities are legal routing/caller identities, but Axon's
    // signed `EntityRef` subject set is intentionally narrower.
    // v4.1.5 §A.URA-3 strict parsing: agent tail MUST be
    // `<user-uuid>.<agent-id>` (split on dot). The
    // the legacy CLI agent-placeholder alias fails the strict parser
    // because `local` has no dot. Use the device shape instead —
    // `r/cli/device/local` parses cleanly (device tail is a bare
    // token with no dot/slash). The daemon's loopback bypass +
    // the Postel-permissive admission paths still admit either,
    // but we want the wire to ship a parseable URA so that any
    // caller-side strict validator does not reject the envelope.
    let resolved_caller_ura = resolved_local_caller_ura(caller_ura);
    let forward_subject_ura =
        crate::ura::owner_ability_ura(target.execution_target_ura(), "federation.forward_invoke")
            .ok_or_else(|| {
            anyhow!(
                "derive descriptor subject for federation.forward_invoke owned by `{}`",
                target.execution_target_ura()
            )
        })?;
    // AXIOM §A1: `invocation_nonce` is a 16-byte random value the
    // daemon's admission gate uses to dedup replays
    // (`AXON_NONCE_REPLAY` rejects on a hit in the replay window).
    // CLI-initiated calls are one-shot, so a fresh `OsRng` 16-byte
    // sample per call is sufficient.
    let request = signed_local_daemon_request(
        &resolved_caller_ura,
        ProtoEnvelope::targeted(
            &resolved_caller_ura,
            target.execution_target_ura(),
            forward_subject_ura,
        )?,
        "federation.forward_invoke",
        forward_args_bytes,
    )?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation invoke")?;

    runtime.block_on(async move {
        let channel = crate::support::local_daemon_grpc::connect_channel(
            socket_path.clone(),
            timeout,
            Duration::from_secs(10),
        )
        .await
        .context("connect to local daemon gRPC endpoint")?;

        let mut client = InvocationClient::new(channel);
        let response = client.invoke(request).await.map_err(|status| {
            // DEC-N4 §2.1: cross-hub `target_offline` surfaces
            // as `Status::failed_precondition` with reason text
            // `target_offline`. Translate that into an
            // operator-actionable bail (rather than a generic
            // RPC error) so a CLI user reading the message
            // knows the call reached the daemon but the peer
            // was unreachable.
            if status.code() == tonic::Code::FailedPrecondition
                && status.message().contains("target_offline")
            {
                anyhow!(
                    "cross-hub target `{}` is offline (federation.forward_invoke \
                     reported target_offline). Run `easynet federation peers` to see \
                     reachable peers, or `easynet runtime status` on the peer machine \
                     to confirm the daemon is running.",
                    target.execution_target_ura()
                )
            } else {
                anyhow!(
                    "daemon error invoking federation.forward_invoke for target `{}` \
                     (code={:?}): {}",
                    target.execution_target_ura(),
                    status.code(),
                    status.message(),
                )
            }
        })?;
        decode_forward_invoke_response_value(&response.into_inner())
    })
}

fn decode_forward_invoke_response_value(body: &InvokeResponse) -> anyhow::Result<Value> {
    ensure_completed_invoke_response("federation.forward_invoke", body)?;

    // DEC-N4 §2.1 final shape:
    // ForwardInvokeResponse { result_bytes, correlation_call_id }
    // is the wire surface. The shape belongs to the Axon SDK and
    // serialises bytes as base64 strings, not JSON byte arrays.
    // Parsing through the SDK type keeps the CLI display layer from
    // drifting when the SDK schema changes.
    let envelope: easynet_axon::ForwardInvokeResponse = serde_json::from_slice(&body.result)
        .with_context(|| {
            format!(
                "parse federation.forward_invoke ForwardInvokeResponse envelope: \
                 result_content_type={:?}",
                body.result_content_type
            )
        })?;

    decode_forward_result_bytes(&envelope.result_bytes)
}

fn ensure_completed_invoke_response(surface: &str, body: &InvokeResponse) -> anyhow::Result<()> {
    let completed = easynet_axon::invocation::InvocationState::Completed.to_wire_i32();
    if body.state == completed {
        return Ok(());
    }

    let state = WireInvocationState::try_from(body.state)
        .map(|state| state.as_str_name().to_string())
        .unwrap_or_else(|_| format!("UNKNOWN_STATE_{}", body.state));
    let (code, message) = body
        .error
        .as_ref()
        .map(|error| {
            (
                error.code.trim().to_string(),
                error.message.trim().to_string(),
            )
        })
        .unwrap_or_else(|| {
            (
                "INVOKE_NOT_COMPLETED".to_string(),
                "InvokeResponse did not carry a structured error".to_string(),
            )
        });
    bail!(
        "{surface} did not complete: state={state} code={} message={}",
        if code.is_empty() {
            "INVOKE_NOT_COMPLETED"
        } else {
            code.as_str()
        },
        if message.is_empty() {
            "InvokeResponse did not carry an error message"
        } else {
            message.as_str()
        }
    )
}

fn decode_forward_result_bytes(result_bytes: &[u8]) -> anyhow::Result<Value> {
    if result_bytes.is_empty() {
        return Ok(Value::Null);
    }
    match serde_json::from_slice::<Value>(result_bytes) {
        Ok(v) => Ok(v),
        Err(_) => Ok(serde_json::json!({
            "result_bytes_len": result_bytes.len(),
            "result_bytes_hex": result_bytes
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect::<String>(),
        })),
    }
}

/// Sign the origin-caller claim with the SUBMITTING DEVICE's
/// registered key (the same derivation `device join` registered into
/// the hub trust set), so the executing device can verify the inner
/// canonical bytes cryptographically and run the ability with the
/// real caller instead of the `_system` trust-domain placeholder.
///
/// The signed tuple must match what the executing device rebuilds
/// (`OriginCaller::into_wire_dispatch` fed by the hub's dispatch
/// frame): callee = the ability's owner identity (the route resolver
/// selects exactly this as callee), subject = the callee default (the
/// forward path relays no explicit subject), causal = None, ability =
/// the PUBLIC name, args = the hub-re-serialised bytes.
///
/// Returns `None` when the caller is not a device URA — fidelity is
/// additive; execution then proceeds with the trust-domain identity.
fn device_origin_claim(
    caller_ura: &str,
    target: &RemoteAbilityInvocationTarget,
    args_bytes: &[u8],
) -> Option<easynet_axon::OriginCallerClaim> {
    use base64::engine::general_purpose::STANDARD as B64;
    use base64::Engine as _;
    use easynet_axon::invocation::{
        sign_descriptor_bound_invocation, AgentIdentity, CausalContext, DescriptorBoundEnvelope,
        DescriptorBoundEnvelopeParts, EntityRef, SubjectIdentity, UraProfile,
    };

    let parsed = parse_ura(caller_ura).ok()?;
    if parsed.kind != URAKind::Device {
        return None;
    }
    let device_id = parsed.device_id()?.to_string();
    let callee_ura = target.callee_ura.to_string();
    let public_ability = target.public_ability.to_string();

    let subject_id = easynet_axon::invocation::private_agent_subject_id(&device_id);
    let (seed, signer_pubkey_b64) =
        crate::runtime::publish::derive_subject_keypair(&parsed.realm, &subject_id);
    let signing = ed25519_dalek::SigningKey::from_bytes(&seed);

    let nonce = easynet_axon::invocation::fresh_nonce();
    let descriptor_version = crate::runtime::ability::DEFAULT_ABILITY_DESCRIPTOR_VERSION;
    let subject_ura = match EntityRef::try_from_subject_identity(&SubjectIdentity::new(
        callee_ura.clone(),
        UraProfile::EasynetStrictV2,
    )) {
        Ok(_) => callee_ura.clone(),
        Err(_) => crate::ura::owner_ability_ura(&callee_ura, &public_ability)?,
    };
    let subject = SubjectIdentity::new(subject_ura, UraProfile::EasynetStrictV2);
    let ability = crate::runtime::axon_bridge::wire_descriptor::ability_descriptor_ref_for_wire(
        &callee_ura,
        &public_ability,
        descriptor_version,
    )
    .ok()?;

    EntityRef::try_from_subject_identity(&subject).ok()?;
    let descriptor_bound = DescriptorBoundEnvelope::from_parts(DescriptorBoundEnvelopeParts {
        caller: AgentIdentity::new(caller_ura.to_string(), UraProfile::EasynetStrictV2),
        callee: AgentIdentity::new(callee_ura.clone(), UraProfile::EasynetStrictV2),
        ability,
        subject,
        invocation_nonce: nonce,
        causal_context: CausalContext::None,
        args_bytes,
    })
    .ok()?;
    let signature = sign_descriptor_bound_invocation(&signing, &descriptor_bound, "device-origin");

    Some(easynet_axon::OriginCallerClaim {
        caller_ura: caller_ura.to_string(),
        ability: public_ability,
        descriptor_version: descriptor_version.to_string(),
        signature_b64: B64.encode(signature.signature),
        signer_pubkey_b64,
        nonce_b64: B64.encode(nonce),
    })
}

fn validate_forward_execution_target(
    execution_target_ura: &str,
    selector: &crate::ura::AbilitySelector,
) -> anyhow::Result<()> {
    let target = parse_ura(execution_target_ura)
        .map_err(|err| anyhow!("invalid target URA `{execution_target_ura}`: {err}"))?;
    let owner = parse_ura(selector.owner_ura()).map_err(|err| {
        anyhow!(
            "invalid ability owner URA `{}`: {err}",
            selector.owner_ura()
        )
    })?;
    if owner.realm != target.realm {
        bail!(
            "ability URA `{}` belongs to realm `{}`, but execution target `{}` belongs to realm `{}`",
            selector.ability_ura(),
            owner.realm,
            execution_target_ura,
            target.realm
        );
    }

    match (target.kind, selector.owner_kind()) {
        (URAKind::Device, "agent") => Ok(()),
        (URAKind::Device, "device") => {
            if selector.owner_ura() == execution_target_ura.trim() {
                Ok(())
            } else {
                bail!(
                    "device-owned ability URA `{}` must execute on its owning device `{}`, not `{}`",
                    selector.ability_ura(),
                    selector.owner_ura(),
                    execution_target_ura
                );
            }
        }
        (URAKind::Hub, "hub") => {
            if selector.owner_ura() == execution_target_ura.trim() {
                Ok(())
            } else {
                bail!(
                    "hub-owned ability URA `{}` must execute on its owning hub `{}`, not `{}`",
                    selector.ability_ura(),
                    selector.owner_ura(),
                    execution_target_ura
                );
            }
        }
        (URAKind::Hub, "agent") => Ok(()),
        (URAKind::Device, "hub") => bail!(
            "hub-owned ability URA `{}` requires a Hub execution target, not device `{}`",
            selector.ability_ura(),
            execution_target_ura
        ),
        (URAKind::Hub, "device") => bail!(
            "device-owned ability URA `{}` requires its owning Device execution target `{}`, not hub `{}`",
            selector.ability_ura(),
            selector.owner_ura(),
            execution_target_ura
        ),
        (target_kind, owner_kind) => bail!(
            "ability URA `{}` cannot execute on target `{}`: unsupported owner/target pair owner_kind={} target_kind={}",
            selector.ability_ura(),
            execution_target_ura,
            owner_kind,
            target_kind
        ),
    }
}

fn validate_forward_target_ura(target_ura: &str) -> anyhow::Result<()> {
    let parsed = parse_ura(target_ura)
        .map_err(|err| anyhow::anyhow!("invalid target URA `{target_ura}`: {err}"))?;
    match parsed.kind {
        URAKind::Device => Ok(()),
        URAKind::Hub => Ok(()),
        other => bail!("target URA `{target_ura}` must identify a Device or Hub, got kind={other}"),
    }
}

/// Cross-realm directory query against the local daemon's
/// `federation.discover` ability. Returns the parsed
/// `entries: [DirectoryEntry]` array verbatim. The single
/// dial path (UDS gRPC InvocationClient → daemon's
/// `dispatch_federation_discover`) is shared with
/// `easynet federation discover`'s own subcommand — having
/// one helper means `device list` / `auth devices` / future
/// fan-out callers cannot drift on caller URA / envelope
/// shape.
///
/// Args:
///   * `agent_ura_filter` — optional URA filter passed verbatim
///     to the daemon. `None` returns the full federated
///     directory; `Some(ura)` returns at most one entry (lex
///     tie-break on peer realm).
///   * `caller_ura` — optional caller URA for the envelope. When
///     `None`, uses the daemon's process-local `_system.local`
///     control-plane identity. It is not a device, user, or hub
///     identity and cannot be reproduced by external callers.
///
/// Returns the `entries` array as a `Vec<Value>` (each element
/// is a `DirectoryEntry`-shaped JSON object).
pub fn invoke_federation_discover(
    agent_ura_filter: Option<&str>,
    caller_ura: Option<&str>,
) -> anyhow::Result<Vec<Value>> {
    invoke_federation_discover_filtered(agent_ura_filter, None, caller_ura)
}

/// Same daemon-backed discovery path as `invoke_federation_discover`,
/// with the optional PR-N4 user-binding privacy filter exposed for
/// the operator CLI. Keeping this in the transport service avoids a
/// second facade-owned gRPC request builder that can drift from the
/// signed daemon IPC contract.
pub fn invoke_federation_discover_filtered(
    agent_ura_filter: Option<&str>,
    local_user_id_filter: Option<&str>,
    caller_ura: Option<&str>,
) -> anyhow::Result<Vec<Value>> {
    let socket_path = crate::support::local_daemon_grpc::resolve_socket_path();
    if !crate::support::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let mut req_args = json!({});
    if let Some(ura) = agent_ura_filter {
        req_args["agent_ura"] = Value::String(ura.to_string());
    }
    if let Some(user) = local_user_id_filter {
        req_args["local_user_id"] = Value::String(user.to_string());
    }
    let arg_bytes = serde_json::to_vec(&req_args).context("encode discover args")?;

    let resolved_caller = resolved_local_caller_ura(caller_ura);

    let request = signed_local_daemon_request(
        &resolved_caller,
        ProtoEnvelope::loopback(resolved_caller.as_str())?,
        "federation.discover",
        arg_bytes,
    )?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation.discover")?;

    let response: easynet_axon::pb::axon::v1::InvokeResponse = {
        runtime.block_on(async move {
            let channel = crate::support::local_daemon_grpc::connect_channel(
                socket_path.clone(),
                Duration::from_secs(10),
                Duration::from_secs(5),
            )
            .await
            .context("connect to local daemon gRPC endpoint")?;
            let mut client = InvocationClient::new(channel);
            let resp = client.invoke(request).await.map_err(|status| {
                anyhow!(
                    "daemon rejected federation.discover: code={:?} message={}",
                    status.code(),
                    status.message()
                )
            })?;
            Ok::<_, anyhow::Error>(resp.into_inner())
        })?
    };

    ensure_completed_invoke_response("federation.discover", &response)?;

    let body: Value =
        serde_json::from_slice(&response.result).context("decode discover response body")?;
    Ok(body
        .get("entries")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default())
}

/// `federation.revoke` against the local daemon's gRPC
/// InvocationServer. Removes the named Agent's directory entry on
/// the hub. CLI lifecycle surfaces (`easynet device remove`,
/// `easynet device reset --force`) call this helper instead of
/// relying on local-only `node.remove` acknowledgements.
///
/// Args:
///   * `agent_ura` — canonical URA of the Agent to revoke (typically
///     a device URA `easynet:///r/<realm>/device/<id>`).
///   * `reason` — operator-supplied label, written through to the
///     receipt for audit. `"deregister"` / `"reset"` are common.
///   * `caller_ura` — same caller identity rule as
///     `invoke_federation_discover`.
///
/// Returns `Ok(())` on a successful ack from the daemon. Best-effort
/// by contract on the hub side, but this helper still surfaces
/// transport / parse errors so callers can log them honestly.
pub fn invoke_federation_revoke(
    agent_ura: &str,
    reason: &str,
    caller_ura: Option<&str>,
) -> anyhow::Result<()> {
    let socket_path = crate::support::local_daemon_grpc::resolve_socket_path();
    if !crate::support::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let req_args = json!({
        "agent_ura": agent_ura,
        "reason": reason,
    });
    let arg_bytes = serde_json::to_vec(&req_args).context("encode revoke args")?;

    let resolved_caller = resolved_local_caller_ura(caller_ura);

    let request = signed_local_daemon_request(
        &resolved_caller,
        ProtoEnvelope::loopback(resolved_caller.as_str())?,
        "federation.revoke",
        arg_bytes,
    )?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation.revoke")?;

    runtime.block_on(async move {
        let channel = crate::support::local_daemon_grpc::connect_channel(
            socket_path.clone(),
            Duration::from_secs(10),
            Duration::from_secs(5),
        )
        .await
        .context("connect to local daemon gRPC endpoint")?;
        let mut client = InvocationClient::new(channel);
        let response = client.invoke(request).await.map_err(|status| {
            anyhow!(
                "daemon rejected federation.revoke: code={:?} message={}",
                status.code(),
                status.message()
            )
        })?;
        ensure_completed_invoke_response("federation.revoke", &response.into_inner())?;
        Ok::<_, anyhow::Error>(())
    })
}

/// Generate a fresh `call_id` for the inner envelope payload's
/// DEC-N4 §2.1 correlation field. Format: `cli-<nanos-hex>` —
/// nanoseconds since Unix epoch, hex-encoded, prefixed so log
/// scraping can tell CLI-minted ids apart from daemon-minted
/// ones (`<self>.invoke_remote` initiator path uses a different
/// prefix). Collision space is `2^64` per second of clock
/// resolution; for the CLI's typical hand-driven cadence the
/// risk is negligible.
fn generate_call_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("cli-{nanos:x}")
}

fn resolved_local_caller_ura(caller_ura: Option<&str>) -> String {
    caller_ura
        .map(str::trim)
        .filter(|caller| !caller.is_empty())
        .map(str::to_string)
        .unwrap_or_else(|| LOCAL_SYSTEM_AGENT_URA.to_string())
}

fn signed_local_daemon_request(
    caller_ura: &str,
    envelope: ProtoEnvelope,
    function_name: &str,
    arguments: Vec<u8>,
) -> anyhow::Result<InvokeRequest> {
    let signer = LocalDaemonSigner::for_caller(caller_ura);
    envelope.signed_invoke_request(function_name, arguments, &signer)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The whole fidelity contract in one place: the claim the
    /// submitting device signs must verify against the canonical bytes
    /// the EXECUTING device rebuilds from the hub's dispatch frame
    /// (callee = route owner, subject = callee default, ability =
    /// public name, args = hub-re-serialised bytes).
    #[test]
    fn device_origin_claim_round_trips_executing_device_rebuild() {
        use ed25519_dalek::{Verifier as _, VerifyingKey};

        let caller = "easynet:///r/easynet.run/device/node-a";
        let ability_ura = "easynet:///r/easynet.run/ability/alice.bfilter.code_filter";
        let target = RemoteAbilityInvocationTarget::from_ability_ura(
            "easynet:///r/easynet.run/device/node-b",
            ability_ura,
        )
        .expect("remote ability target");
        let args_bytes =
            serde_json::to_vec(&serde_json::json!({"rows": "[]", "code": "return True"}))
                .expect("args bytes");

        let claim = device_origin_claim(caller, &target, &args_bytes)
            .expect("device caller produces a claim");
        assert_eq!(claim.caller_ura, caller);
        assert_eq!(claim.ability, "code_filter");
        assert_eq!(
            claim.descriptor_version,
            crate::runtime::ability::DEFAULT_ABILITY_DESCRIPTOR_VERSION
        );

        // Executing-device side: decode and rebuild exactly as
        // `LocalAxonSessionDispatcher` does (claim -> wire dispatch with
        // the frame's callee and the subject default).
        let origin =
            crate::services::invocation_transport::origin_caller::OriginCaller::from_claim(
                claim.clone(),
            )
            .expect("claim decodes");
        let route_callee = "easynet:///r/easynet.run/agent/alice.bfilter";
        let wire = origin
            .into_wire_dispatch(route_callee, route_callee, args_bytes.clone())
            .expect("origin caller wire dispatch");

        use base64::Engine as _;
        let pubkey: [u8; 32] = base64::engine::general_purpose::STANDARD
            .decode(&claim.signer_pubkey_b64)
            .expect("pubkey b64")
            .try_into()
            .expect("32 bytes");
        let verifying = VerifyingKey::from_bytes(&pubkey).expect("verifying key");
        let crate::runtime::axon_bridge::dispatch_shim::WireDispatchIngress::ExternalSigned(
            caller_signature,
        ) = &wire.ingress
        else {
            panic!("origin caller claim must rebuild an external signed dispatch");
        };
        let signature = ed25519_dalek::Signature::from_slice(&caller_signature.signature)
            .expect("signature shape");
        verifying
            .verify(&wire.envelope.canonical_bytes(), &signature)
            .expect(
                "rebuilt descriptor-bound canonical bytes must verify against the device claim",
            );

        // Tampered args must NOT verify (fail closed at admission).
        let mut tampered = args_bytes.clone();
        tampered[0] ^= 1;
        let origin2 =
            crate::services::invocation_transport::origin_caller::OriginCaller::from_claim(claim)
                .expect("claim decodes");
        let wire2 = origin2
            .into_wire_dispatch(route_callee, route_callee, tampered)
            .expect("origin caller wire dispatch");
        assert!(verifying
            .verify(&wire2.envelope.canonical_bytes(), &signature)
            .is_err());
    }

    /// Non-device callers (users, agents) produce no device claim —
    /// fidelity is additive, never fabricated.
    #[test]
    fn device_origin_claim_requires_device_caller() {
        let target = RemoteAbilityInvocationTarget::from_ability_ura(
            "easynet:///r/easynet.run/device/node-b",
            "easynet:///r/easynet.run/ability/alice.bfilter.code_filter",
        )
        .expect("remote ability target");
        assert!(
            device_origin_claim("easynet:///r/easynet.run/user/alice", &target, b"{}",).is_none()
        );
    }

    #[test]
    fn parse_node_ura_accepts_canonical_shape() {
        let parsed =
            parse_node_ura("easynet:///r/realm-b/device/laptop-bob").expect("canonical accepted");
        assert_eq!(parsed, "easynet:///r/realm-b/device/laptop-bob");
    }

    #[test]
    fn parse_node_ura_accepts_hub_ura_for_cross_hub_calls() {
        let hub = easynet_axon::ura::hub_ura("peer-realm");
        let parsed = parse_node_ura(&hub).expect("canonical hub URA accepted");
        assert_eq!(parsed, hub);
    }

    #[test]
    fn parse_node_ura_accepts_protocol_hub_identity() {
        let parsed =
            parse_node_ura("easynet:///r/peer-realm/hub").expect("hub identity is canonical");
        assert_eq!(parsed, "easynet:///r/peer-realm/hub");
    }

    #[test]
    fn parse_node_ura_rejects_hub_with_tail() {
        let err = parse_node_ura("easynet:///r/realm/hub/extra").expect_err("hub tail rejected");
        assert!(
            err.to_string()
                .contains("not a canonical Axon Device or Hub URA"),
            "hub identity with tail must not be accepted, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_trims_surrounding_whitespace() {
        let parsed =
            parse_node_ura("  easynet:///r/realm-b/device/n1  \n").expect("whitespace trimmed");
        assert_eq!(parsed, "easynet:///r/realm-b/device/n1");
    }

    #[test]
    fn parse_node_ura_rejects_agent_device_alias_shape() {
        let err = parse_node_ura("easynet:///r/realm-b/agent/n1")
            .expect_err("device alias must be rejected");
        assert!(format!("{err}").contains("agent tail must"));
    }

    #[test]
    fn parse_node_ura_rejects_https_url() {
        let err = parse_node_ura("https://hub.example/r/foo").expect_err("https rejected");
        assert!(
            format!("{err}").contains("not a canonical Axon Device or Hub URA"),
            "error message must cite the canonical-URA requirement, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_rejects_bare_hostname() {
        let err = parse_node_ura("hub.example.com").expect_err("bare hostname rejected");
        assert!(format!("{err}").contains("canonical"));
    }

    #[test]
    fn parse_node_ura_rejects_missing_realm() {
        let err = parse_node_ura("easynet:///r//device/n1").expect_err("empty realm rejected");
        assert!(
            format!("{err}").contains("missing <realm>"),
            "must surface a structural-mismatch error, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_rejects_missing_node_id() {
        let err =
            parse_node_ura("easynet:///r/realm-b/device/").expect_err("empty node id rejected");
        // The SDK ParseError::DeviceMissingTail formats as
        // "device URA requires <device-id> tail" (note: URA, not
        // URA — the SDK ontology calls these URAs everywhere).
        // Test pins that wording so a future rename surfaces here
        // instead of silently swallowing the error condition.
        assert!(
            format!("{err}").contains("device URA requires"),
            "expected SDK DeviceMissingTail wording, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_rejects_extra_path_segments() {
        let err = parse_node_ura("easynet:///r/realm-b/device/n1/ability/x")
            .expect_err("extra segments rejected");
        // The SDK ParseError::DeviceBadShape formats as
        // "device-id must be a single path segment". The test used
        // to assert "device-id must be bare" — an older copy that
        // drifted from the SDK; we pin the live wording here.
        assert!(
            format!("{err}").contains("device-id must be a single path segment"),
            "expected SDK DeviceBadShape wording, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_rejects_real_agent_profile_ura() {
        let err = parse_node_ura("easynet:///r/realm-b/agent/alice.claude")
            .expect_err("hosted agent must not be accepted");
        assert!(format!("{err}").contains("kind=agent"));
    }

    #[test]
    fn parse_node_ura_rejects_wrong_keyword() {
        // The role segment after the realm must be one of Axon's
        // canonical URA roles. A typo is rejected before the URA
        // reaches the daemon.
        let err =
            parse_node_ura("easynet:///r/realm-b/notarole/n1").expect_err("wrong keyword rejected");
        assert!(
            format!("{err}").contains("unknown URA role"),
            "expected SDK UnknownRole wording, got: {err}"
        );
    }

    #[test]
    fn parse_node_ura_failure_message_includes_discovery_hint() {
        // PR-N1 user-flow review catch: operators have no
        // zero-config way to discover a peer's canonical URA today
        // (PR-N3 territory). Until PR-N3 ships, the error message
        // tells them where to look — credentials.json, daemon-
        // config.toml's federated_peers table, /etc/easynet/realm-
        // trust.toml's hub entries, and `easynet ability list`
        // (local-realm).
        // Both rejection arms (non-easynet scheme + structural
        // mismatch) MUST cite the discovery hint so a typo'd
        // command surfaces the same operator-actionable next step.
        let err_scheme = parse_node_ura("not-an-easynet-ura").expect_err("rejected");
        let msg_scheme = format!("{err_scheme}");
        assert!(
            msg_scheme.contains("credentials.json"),
            "scheme-arm error must cite credentials.json discovery path; got: {msg_scheme}"
        );
        assert!(
            msg_scheme.contains("daemon-config.toml"),
            "scheme-arm error must cite daemon-config.toml discovery path; got: {msg_scheme}"
        );
        assert!(
            msg_scheme.contains("realm-trust.toml"),
            "scheme-arm error must cite realm-trust.toml discovery path; got: {msg_scheme}"
        );
        assert!(
            msg_scheme.contains("easynet ability list"),
            "scheme-arm error must cite easynet ability list; got: {msg_scheme}"
        );

        // Structural-failure: empty realm tail. Use a clearly
        // malformed input to exercise the structural-arm error
        // path without depending on any retired URA aliases.
        let err_struct = parse_node_ura("easynet:///r//device/n1").expect_err("rejected");
        let msg_struct = format!("{err_struct}");
        assert!(
            msg_struct.contains("credentials.json") && msg_struct.contains("daemon-config.toml"),
            "structural-arm error must cite the same discovery hint; got: {msg_struct}"
        );
    }

    #[test]
    fn remote_target_rejects_wrong_device_owner() {
        let err = RemoteAbilityInvocationTarget::from_ability_ura(
            "easynet:///r/acme/device/dev-1",
            "easynet:///r/acme/ability/device.other.fs.read",
        )
        .expect_err("owner mismatch must fail");
        let msg = err.to_string();
        assert!(
            msg.contains("owning device"),
            "owner mismatch must be explicit: {msg}"
        );
    }

    #[test]
    fn remote_target_accepts_matching_device_owner() {
        RemoteAbilityInvocationTarget::from_ability_ura(
            "easynet:///r/acme/device/dev-1",
            "easynet:///r/acme/ability/device.dev-1.fs.read",
        )
        .expect("matching device-owned ability URA is accepted");
    }

    #[test]
    fn remote_target_accepts_agent_owner_on_device_execution_target() {
        let target = RemoteAbilityInvocationTarget::from_ability_ura(
            "easynet:///r/acme/device/dev-1",
            "easynet:///r/acme/ability/alice.worker.report.generate",
        )
        .expect("agent-owned ability may execute on a device route");
        assert_eq!(
            target.execution_target_ura(),
            "easynet:///r/acme/device/dev-1"
        );
        assert_eq!(target.callee_ura, "easynet:///r/acme/agent/alice.worker");
        assert_eq!(target.public_ability, "report.generate");
    }

    #[test]
    fn remote_target_projects_device_selector_to_owner_ura() {
        assert_eq!(
            RemoteAbilityInvocationTarget::for_target_owned_selector(
                "easynet:///r/acme/device/dev-1",
                "fs.read",
            )
            .expect("device ability URA")
            .as_str(),
            "easynet:///r/acme/ability/device.dev-1.fs.read"
        );
    }

    #[test]
    fn remote_target_projects_device_meta_list_resources() {
        assert_eq!(
            RemoteAbilityInvocationTarget::for_target_owned_selector(
                "easynet:///r/acme/device/02507271-6034-40df-959c-f90bc930d676",
                "meta.list_resources",
            )
            .expect("device meta.list_resources ability URA")
            .as_str(),
            "easynet:///r/acme/ability/device.02507271-6034-40df-959c-f90bc930d676.meta.list_resources"
        );
    }

    #[test]
    fn remote_target_accepts_prebuilt_canonical_ura() {
        assert_eq!(
            RemoteAbilityInvocationTarget::from_ability_ura(
                "easynet:///r/acme/device/dev-1",
                "easynet:///r/acme/ability/device.dev-1.fs.read",
            )
            .expect("prebuilt ability URA")
            .as_str(),
            "easynet:///r/acme/ability/device.dev-1.fs.read"
        );
    }

    #[test]
    fn remote_target_rejects_wrong_owner() {
        let err = RemoteAbilityInvocationTarget::from_ability_ura(
            "easynet:///r/acme/device/dev-1",
            "easynet:///r/acme/ability/device.other.fs.read",
        )
        .expect_err("wrong owner must fail");
        assert!(
            err.to_string().contains("owning device"),
            "owner mismatch must be explicit: {err}"
        );
    }

    #[test]
    fn remote_target_projects_hub_selector_to_owner_ura() {
        assert_eq!(
            RemoteAbilityInvocationTarget::for_target_owned_selector(
                &easynet_axon::ura::hub_ura("acme"),
                "hub.federation.resolve",
            )
            .expect("hub ability URA")
            .as_str(),
            "easynet:///r/acme/ability/hub.federation.resolve"
        );
    }

    #[test]
    fn remote_target_projects_protocol_hub_identity() {
        assert_eq!(
            RemoteAbilityInvocationTarget::for_target_owned_selector(
                "easynet:///r/acme/hub",
                "hub.federation.resolve",
            )
            .expect("hub identity target is canonical")
            .as_str(),
            "easynet:///r/acme/ability/hub.federation.resolve"
        );
    }

    #[test]
    fn remote_target_rejects_hub_with_tail() {
        let err = RemoteAbilityInvocationTarget::for_target_owned_selector(
            "easynet:///r/acme/hub/extra",
            "hub.federation.resolve",
        )
        .expect_err("hub target with tail must be invalid");
        assert!(
            err.to_string().contains("invalid target URA"),
            "hub target with tail must fail through Axon parser, got: {err}"
        );
    }

    #[test]
    fn decode_forward_invoke_response_decodes_sdk_base64_result_bytes() {
        let envelope = easynet_axon::ForwardInvokeResponse {
            result_bytes: br#"{"content":"hello"}"#.to_vec(),
            correlation_call_id: "cli-call-1".to_string(),
        };
        let body = easynet_axon::pb::axon::v1::InvokeResponse {
            result: serde_json::to_vec(&envelope).expect("encode ForwardInvokeResponse"),
            result_content_type: "application/json".to_string(),
            state: easynet_axon::invocation::InvocationState::Completed.to_wire_i32(),
            ..Default::default()
        };

        let value = decode_forward_invoke_response_value(&body).expect("decode response");

        assert_eq!(value["content"], "hello");
    }

    #[test]
    fn decode_forward_invoke_response_no_longer_emits_delivery_accepted_shim() {
        let envelope = easynet_axon::ForwardInvokeResponse {
            result_bytes: Vec::new(),
            correlation_call_id: "cli-call-empty".to_string(),
        };
        let body = easynet_axon::pb::axon::v1::InvokeResponse {
            result: serde_json::to_vec(&envelope).expect("encode ForwardInvokeResponse"),
            result_content_type: "application/json".to_string(),
            state: easynet_axon::invocation::InvocationState::Completed.to_wire_i32(),
            ..Default::default()
        };

        let value = decode_forward_invoke_response_value(&body).expect("decode response");

        assert_eq!(
            value,
            Value::Null,
            "empty ability payload is a real empty result, not delivery=accepted"
        );
    }

    #[test]
    fn decode_forward_invoke_response_hex_encodes_non_json_payload() {
        let envelope = easynet_axon::ForwardInvokeResponse {
            result_bytes: vec![0xde, 0xad, 0xbe, 0xef],
            correlation_call_id: "cli-call-bin".to_string(),
        };
        let body = easynet_axon::pb::axon::v1::InvokeResponse {
            result: serde_json::to_vec(&envelope).expect("encode ForwardInvokeResponse"),
            result_content_type: "application/json".to_string(),
            state: easynet_axon::invocation::InvocationState::Completed.to_wire_i32(),
            ..Default::default()
        };

        let value = decode_forward_invoke_response_value(&body).expect("decode response");

        assert_eq!(value["result_bytes_len"], 4);
        assert_eq!(value["result_bytes_hex"], "deadbeef");
    }

    #[test]
    fn decode_forward_invoke_response_rejects_failed_in_band_state() {
        let body = easynet_axon::pb::axon::v1::InvokeResponse {
            state: easynet_axon::invocation::InvocationState::Failed.to_wire_i32(),
            error: Some(easynet_axon::pb::axon::v1::Error {
                code: "AXON_TARGET_OFFLINE".to_string(),
                message: "peer is unreachable".to_string(),
                ..Default::default()
            }),
            ..Default::default()
        };

        let err = decode_forward_invoke_response_value(&body)
            .expect_err("failed in-band state must not decode as success");
        let rendered = err.to_string();
        assert!(rendered.contains("state=INVOCATION_STATE_FAILED"));
        assert!(rendered.contains("AXON_TARGET_OFFLINE"));
        assert!(rendered.contains("peer is unreachable"));
    }
}
