#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "provider_routes/easynet-principal-lifecycle-routes.v1.json"
GO_OUTPUT = ROOT / "sdk/go/principal_routes_gen.go"
PY_OUTPUT = ROOT / "sdk/python/easynet_sdk/_principal_routes.py"
RUST_OUTPUT = ROOT / "src/cli/commands/groups/principal_routes_gen.rs"


def load_manifest() -> dict[str, Any]:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError("principal route manifest schema_version must be 1")
    if data.get("provider") != "easynet" or data.get("capability") != "principal_lifecycle":
        raise ValueError("principal route manifest identity mismatch")
    require_text(data.get("profile"), "principal route manifest profile")
    routes = data.get("routes")
    if not isinstance(routes, list) or not routes:
        raise ValueError("principal route manifest requires routes")
    seen_ids: set[str] = set()
    seen_abilities: set[str] = set()
    for route in routes:
        if not isinstance(route, dict):
            raise ValueError("principal route entry must be an object")
        required = {"id", "go_const", "python_const", "rust_const", "ability"}
        if set(route) != required:
            raise ValueError(f"principal route entry has invalid keys: {route!r}")
        route_id = require_text(route["id"], "route id")
        ability = require_text(route["ability"], "route ability")
        if route_id in seen_ids or ability in seen_abilities:
            raise ValueError(f"duplicate principal route: {route!r}")
        if not ability.startswith("principal.lifecycle."):
            raise ValueError(f"principal route ability is outside lifecycle namespace: {ability}")
        seen_ids.add(route_id)
        seen_abilities.add(ability)
        require_text(route["go_const"], "go const")
        require_text(route["python_const"], "python const")
        require_text(route["rust_const"], "rust const")
    return data


def require_text(value: object, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label} must be a non-empty string")
    return value


def manifest_sha() -> str:
    return hashlib.sha256(MANIFEST.read_bytes()).hexdigest()


def go_source(manifest: dict[str, Any], digest: str) -> str:
    constants = [
        ("principalLifecycleProfile", manifest["profile"]),
        ("principalLifecycleRouteManifestSHA256", digest),
    ]
    constants.extend((route["go_const"], route["ability"]) for route in manifest["routes"])
    name_width = max(len(name) for name, _ in constants)
    lines = [
        "// Code generated by provider_routes/generate_principal_routes.py; DO NOT EDIT.",
        "package easynet",
        "",
        "const (",
    ]
    for name, value in constants:
        lines.append(f'\t{name:<{name_width}} = "{value}"')
    lines.extend([")", ""])
    return "\n".join(lines)


def python_source(manifest: dict[str, Any], digest: str) -> str:
    lines = [
        "# Code generated by provider_routes/generate_principal_routes.py; DO NOT EDIT.",
        "",
        f'_PROFILE = "{manifest["profile"]}"',
        f'_PRINCIPAL_ROUTE_MANIFEST_SHA256 = "{digest}"',
    ]
    for route in manifest["routes"]:
        lines.append(f'{route["python_const"]} = "{route["ability"]}"')
    lines.append("")
    return "\n".join(lines)


def rust_source(manifest: dict[str, Any], digest: str) -> str:
    lines = [
        "// Code generated by provider_routes/generate_principal_routes.py; DO NOT EDIT.",
        "",
        rust_const("PRINCIPAL_LIFECYCLE_PROFILE", manifest["profile"]),
        rust_const("PRINCIPAL_ROUTE_MANIFEST_SHA256", digest),
    ]
    for route in manifest["routes"]:
        lines.append(rust_const(route["rust_const"], route["ability"]))
    lines.append("")
    return "\n".join(lines)


def rust_const(name: str, value: str) -> str:
    line = f'pub(crate) const {name}: &str = "{value}";'
    if len(line) <= 100:
        return line
    return f'pub(crate) const {name}: &str =\n    "{value}";'


def write_if_changed(path: Path, content: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return False
    if check:
        raise SystemExit(f"generated file is stale: {path.relative_to(ROOT)}")
    path.write_text(content, encoding="utf-8")
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    manifest = load_manifest()
    digest = manifest_sha()
    changed = [
        write_if_changed(GO_OUTPUT, go_source(manifest, digest), check=args.check),
        write_if_changed(PY_OUTPUT, python_source(manifest, digest), check=args.check),
        write_if_changed(RUST_OUTPUT, rust_source(manifest, digest), check=args.check),
    ]
    if not args.check:
        print(f"principal route bindings generated: {sum(changed)} file(s) updated")


if __name__ == "__main__":
    main()
