from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parents[1]


def load_manifest(
    manifest_path: Path,
    *,
    expected_provider: str,
    expected_capability: str,
    route_const_keys: set[str],
    route_label: str,
    ability_allowed: Callable[[str], bool],
) -> dict[str, Any]:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError(f"{route_label} route manifest schema_version must be 1")
    if (
        data.get("provider") != expected_provider
        or data.get("capability") != expected_capability
    ):
        raise ValueError(f"{route_label} route manifest identity mismatch")
    require_text(data.get("profile"), f"{route_label} route manifest profile")
    routes = data.get("routes")
    if not isinstance(routes, list) or not routes:
        raise ValueError(f"{route_label} route manifest requires routes")

    seen_ids: set[str] = set()
    seen_abilities: set[str] = set()
    required = {"id", "ability", *route_const_keys}
    for route in routes:
        if not isinstance(route, dict):
            raise ValueError(f"{route_label} route entry must be an object")
        if set(route) != required:
            raise ValueError(f"{route_label} route entry has invalid keys: {route!r}")
        route_id = require_text(route["id"], "route id")
        ability = require_text(route["ability"], "route ability")
        if route_id in seen_ids or ability in seen_abilities:
            raise ValueError(f"duplicate {route_label} route: {route!r}")
        if not ability_allowed(ability):
            raise ValueError(f"{route_label} route ability is outside namespace: {ability}")
        seen_ids.add(route_id)
        seen_abilities.add(ability)
        for key in sorted(route_const_keys):
            require_text(route[key], f"{key} const")
    return data


def require_text(value: object, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label} must be a non-empty string")
    return value


def manifest_sha(manifest_path: Path) -> str:
    return hashlib.sha256(manifest_path.read_bytes()).hexdigest()


def go_source(
    *,
    script_name: str,
    manifest: dict[str, Any],
    digest: str,
    profile_const: str,
    digest_const: str,
    route_const_key: str,
) -> str:
    constants = [
        (profile_const, manifest["profile"]),
        (digest_const, digest),
    ]
    constants.extend((route[route_const_key], route["ability"]) for route in manifest["routes"])
    name_width = max(len(name) for name, _ in constants)
    lines = [
        f"// Code generated by provider_routes/{script_name}; DO NOT EDIT.",
        "package easynet",
        "",
        "const (",
    ]
    for name, value in constants:
        lines.append(f'\t{name:<{name_width}} = "{value}"')
    lines.extend([")", ""])
    return "\n".join(lines)


def python_source(
    *,
    script_name: str,
    manifest: dict[str, Any],
    digest: str,
    digest_const: str,
    route_const_key: str,
) -> str:
    lines = [
        f"# Code generated by provider_routes/{script_name}; DO NOT EDIT.",
        "",
        f'_PROFILE = "{manifest["profile"]}"',
        f'{digest_const} = "{digest}"',
    ]
    for route in manifest["routes"]:
        lines.append(f'{route[route_const_key]} = "{route["ability"]}"')
    lines.append("")
    return "\n".join(lines)


def rust_source(
    *,
    script_name: str,
    manifest: dict[str, Any],
    digest: str,
    profile_const: str,
    digest_const: str,
    route_const_key: str,
) -> str:
    lines = [
        f"// Code generated by provider_routes/{script_name}; DO NOT EDIT.",
        "",
        rust_const(profile_const, manifest["profile"], cfg_test=True),
        rust_const(digest_const, digest, cfg_test=True),
    ]
    for route in manifest["routes"]:
        lines.append(rust_const(route[route_const_key], route["ability"]))
    lines.append("")
    return "\n".join(lines)


def rust_const(name: str, value: str, *, cfg_test: bool = False) -> str:
    line = f'pub(crate) const {name}: &str = "{value}";'
    prefix = "#[cfg(test)]\n" if cfg_test else ""
    if len(line) <= 100:
        return f"{prefix}{line}"
    return f'{prefix}pub(crate) const {name}: &str =\n    "{value}";'


def write_if_changed(path: Path, content: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return False
    if check:
        raise SystemExit(f"generated file is stale: {path.relative_to(ROOT)}")
    path.write_text(content, encoding="utf-8")
    return True
