// EasyNet CLI — canonical remote invocation adapter
// ===================================================
//
// File: src/daemon/invocation/routing/remote_invoke.rs
// Description: Projects CLI/A2A/EAL remote targets into a complete,
//              descriptor-bound `InvokeRequest`, signs that request with the
//              caller owner, and submits it to the local daemon's canonical
//              `Invocation::invoke` endpoint.
//
// Wire shape
// ----------
// 1. Caller passes `(ability_ura, args, node_ura)`. `node_ura` must
//    be a canonical Axon Device or Hub URA; non-canonical inputs
//    surface as a typed error before any IPC.
// 2. The helper dials the local daemon's UDS-bound gRPC
//    `Invocation` server (default `~/.easynet/daemon.sock`).
// 3. It sends the actual ability/function, opaque arguments, complete signed
//    envelope, descriptor binding, content envelope, metadata, and deadline
//    in one `InvokeRequest`. Routing may change transport hops but never
//    projects these fields into an inner wrapper payload.
//
// Feature gating
// --------------
// `axon-pb` feature gates the entire module. Production builds run
// with `axon-pb` on; minimal builds (no daemon transport) can drop
// the cross-hub bridge along with the rest of the gRPC stack.
//
// Author: Silan.Hu <silan.hu@u.nus.edu>
// Copyright (c) 2026 EasyNet. All rights reserved.

use std::time::Duration;

use anyhow::{anyhow, bail, Context};
use serde_json::{json, Value};

use crate::daemon::invocation::dispatch::forwarded_finalization::{
    ForwardedFinalizedInvocation, ForwardedInvocationBinding,
};
use crate::daemon::invocation::ProtoEnvelope;
use easynet_axon::pb::axon::v1::invocation_client::InvocationClient;
use easynet_axon::pb::axon::v1::{InvocationState as WireInvocationState, InvokeResponse};
use easynet_axon::ura::{parse_ura, URAKind};

/// Validate a `--node` argument as a canonical Axon Device or Hub URA.
/// Returns the URA string when it parses; surfaces a typed error
/// when it doesn't, with the exact wire-shape we expect quoted in
/// the message so the operator can fix the typo.
///
/// The grammar decision belongs to Axon. This helper only applies
/// the CLI policy distinction after parsing: `--node` may target a
/// Device or Hub URA, never a hosted Agent/User/Ability/Resource.
/// Hub targets must be generated by Axon's `hub_ura(realm)` builder,
/// whose clean protocol identity is `easynet:///r/<realm>/hub`.
pub fn parse_node_ura(node: &str) -> anyhow::Result<String> {
    let trimmed = node.trim();
    let parsed = parse_ura(trimmed).map_err(|err| {
        anyhow::anyhow!(
            "--node `{trimmed}` is not a canonical Axon Device or Hub URA: {err}. \
             A bare hostname or `https://...` URL is not accepted. \
             {URA_DISCOVERY_HINT}"
        )
    })?;

    match parsed.kind {
        URAKind::Device => Ok(trimmed.to_string()),
        URAKind::Hub => Ok(trimmed.to_string()),
        other => bail!(
            "--node `{trimmed}` is a canonical Axon URA, but not a Device or Hub target. \
             Got kind={other}. \
             {URA_DISCOVERY_HINT}"
        ),
    }
}

/// Operator-actionable hint appended to every `--node` parse failure.
/// Names the four places a real URA can come from today, ordered
/// most-helpful-first. Centralised so the wording stays byte-identical
/// across both `parse_node_ura` failure arms — operators can grep one
/// substring across logs.
///
/// **PR-N1 user-flow review catch**: PR-N1 ships the CLI
/// invocation surface (commit 8/N) but cross-hub URA discovery
/// from a remote machine without manual config is PR-N3
/// territory (cross-realm directory federation, not yet shipped).
/// Until PR-N3 lands, operators construct URAs by hand from the
/// sources below; the error message points at them.
const URA_DISCOVERY_HINT: &str = "Where to find a canonical URA today (until PR-N3 cross-realm \
     directory federation ships): \
     (1) `cat ~/.easynet/credentials.json` on the target machine — \
     concat `easynet:///r/<realm>/device/<node_id>` from the fields. \
     (2) `cat ~/.easynet/daemon-config.toml` and read the \
     `[daemon.federated_peers]` table — keys are realms the \
     local daemon already trusts. \
     (3) `cat /etc/easynet/realm-trust.toml` and read \
     `[[trusted_agent]]` blocks with `role = \"hub\"` — those \
     are the peer hubs the cross-hub dialer can reach. \
     (4) `easynet ability list` — local-realm only \
     today; cross-realm enumeration ships in PR-N3.";

/// Complete caller-side target for a canonical remote invocation.
///
/// This value object is the root fix for the execution-target/callee-owner
/// split. `execution_target_ura` is the node or hub the local daemon sends the
/// frame to. `callee_ura` is the Agent/Device/Hub identity that advertises the
/// AbilityDescriptor. They are equal for device-owned system abilities and
/// intentionally different for hosted-agent abilities executed on a device.
///
/// What this is not: it is not a route answer. The remote daemon/hub remains
/// responsible for proving that a hosted Agent is actually runnable at the
/// execution target. This object only prevents the CLI from corrupting the
/// signed Invocation tuple before the resolver gets a chance to decide.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct RemoteAbilityInvocationTarget {
    execution_target_ura: String,
    ability_ura: String,
    callee_ura: String,
    public_ability: String,
    default_subject_ura: String,
    descriptor_ref: String,
}

impl RemoteAbilityInvocationTarget {
    /// Project a target-owned system ability selector into a full remote
    /// invocation target with descriptor binding deferred to that target.
    ///
    /// Use this for command adapters whose product contract is "call this
    /// device/hub-owned system ability on `--node`". It is deliberately named
    /// target-owned so it is not reused for arbitrary Ability URAs.
    pub(crate) fn for_target_owned_selector(
        execution_target_ura: &str,
        selector: &str,
    ) -> anyhow::Result<Self> {
        validate_remote_target_ura(execution_target_ura)?;
        let public_ability =
            crate::core::ura::owner_local_ability_name(execution_target_ura, selector);
        let ability_ura =
            crate::core::ura::owner_ability_ura(execution_target_ura, &public_ability).ok_or_else(
                || anyhow!("derive ability URA for {execution_target_ura} {public_ability}"),
            )?;
        Self::from_ability_ura(execution_target_ura, &ability_ura)
    }

    /// Accept an already-canonical Ability URA and bind it to an execution
    /// target without rewriting the Ability owner.
    pub(crate) fn from_ability_ura(
        execution_target_ura: &str,
        ability_ura: &str,
    ) -> anyhow::Result<Self> {
        validate_remote_target_ura(execution_target_ura)?;
        let trimmed = ability_ura.trim();
        let selector = crate::core::ura::AbilitySelector::parse(trimmed)?;
        validate_remote_execution_target(execution_target_ura, &selector)?;
        let descriptor_ref =
            crate::daemon::axon_bridge::descriptor_ref::catalog_descriptor_ref_for_wire(
                selector.owner_ura(),
                selector.public_name(),
                crate::daemon::ability::CallMode::Rpc,
            )
            .map_err(|err| {
                anyhow!(
                    "ability URA `{trimmed}` is not descriptor-bound and no local system catalog \
                     descriptor can prove it: {err}. Pass an explicit descriptor-bound Ability ref."
                )
            })?;
        Ok(Self::from_validated_selector(
            execution_target_ura,
            trimmed,
            &selector,
            descriptor_ref,
        ))
    }

    /// Accept a descriptor-bound Ability ref and preserve the version for
    /// origin-caller proof generation.
    pub(crate) fn from_descriptor_ref(
        execution_target_ura: &str,
        descriptor_ref: &str,
    ) -> anyhow::Result<Self> {
        let canonical = easynet_axon::invocation::canonical_ability_descriptor_ref(descriptor_ref)
            .map_err(|err| anyhow!("invalid descriptor-bound Ability ref: {err}"))?;
        let ability_ura =
            crate::daemon::axon_bridge::descriptor_ref::ability_ura_from_descriptor_ref(&canonical)
                .map_err(|err| {
                    anyhow!("descriptor-bound Ability ref is missing ability URA: {err}")
                })?;
        validate_remote_target_ura(execution_target_ura)?;
        let selector = crate::core::ura::AbilitySelector::parse(&ability_ura)?;
        validate_remote_execution_target(execution_target_ura, &selector)?;
        Ok(Self::from_validated_selector(
            execution_target_ura,
            &ability_ura,
            &selector,
            canonical,
        ))
    }

    fn from_validated_selector(
        execution_target_ura: &str,
        ability_ura: &str,
        selector: &crate::core::ura::AbilitySelector,
        descriptor_ref: String,
    ) -> Self {
        Self {
            execution_target_ura: execution_target_ura.trim().to_string(),
            ability_ura: ability_ura.trim().to_string(),
            callee_ura: selector.owner_ura().to_string(),
            public_ability: selector.public_name().to_string(),
            default_subject_ura: default_subject_ura_for_selector(selector),
            descriptor_ref,
        }
    }

    /// Borrow the canonical URA for the transport helper.
    pub(crate) fn as_str(&self) -> &str {
        &self.ability_ura
    }

    /// Node or hub that receives the forwarding request.
    pub(crate) fn execution_target_ura(&self) -> &str {
        &self.execution_target_ura
    }

    pub(crate) fn descriptor_ref(&self) -> &str {
        &self.descriptor_ref
    }

    pub(crate) fn default_subject_ura(&self) -> &str {
        &self.default_subject_ura
    }
}

pub(crate) fn invoke_remote_target(
    target: &RemoteAbilityInvocationTarget,
    args: Value,
    caller_ura: Option<&str>,
) -> anyhow::Result<Value> {
    invoke_remote_target_with_timeout(target, None, args, caller_ura, &[], Duration::from_secs(30))
}

/// Forward a device-targeted call while preserving the caller's causal
/// lineage. Used by paths that are themselves dispatching an
/// already-placed invocation (e.g. the EAL device branch), so the
/// receipt DAG keeps real edges instead of re-rooting at the forward hop
/// (refactor SPEC §15.1 item 1, seven-tuple invariant). Originating CLI
/// commands keep calling [`invoke_remote_target`], which
/// passes no parents.
pub(crate) fn invoke_remote_target_with_causal_parents(
    target: &RemoteAbilityInvocationTarget,
    args: Value,
    caller_ura: Option<&str>,
    causal_parents: &[Value],
) -> anyhow::Result<Value> {
    invoke_remote_target_with_timeout(
        target,
        None,
        args,
        caller_ura,
        causal_parents,
        Duration::from_secs(30),
    )
}

pub(crate) fn invoke_remote_target_with_timeout(
    target: &RemoteAbilityInvocationTarget,
    subject_ura: Option<&str>,
    args: Value,
    caller_ura: Option<&str>,
    causal_parents: &[Value],
    timeout: Duration,
) -> anyhow::Result<Value> {
    let socket_path = crate::support::platform::local_daemon_grpc::resolve_socket_path();
    if !crate::support::platform::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let caller_ura = resolve_remote_caller_ura(caller_ura)?;
    let subject_ura = subject_ura
        .map(str::trim)
        .filter(|subject| !subject.is_empty())
        .unwrap_or_else(|| target.default_subject_ura())
        .to_string();
    crate::core::ura::parse_ura(&subject_ura)
        .map_err(|err| anyhow!("invalid remote invocation subject URA `{subject_ura}`: {err}"))?;
    let arguments = serde_json::to_vec(&args).context("serialise remote invocation arguments")?;
    let causal_context = causal_context_from_parents(causal_parents)?;
    let timeout_seconds = i32::try_from(timeout.as_secs().max(1)).unwrap_or(i32::MAX);

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for canonical remote invoke")?;

    runtime.block_on(async move {
        let signer = crate::daemon::identity::self_identity::RuntimeSigningIdentity::load_default(
            caller_ura.clone(),
        )
        .map_err(|err| {
            anyhow!(
                "remote invocation requires a caller signer for `{caller_ura}`; \
                 load or provision that identity in the local key service: {err}"
            )
        })?;
        let mut request =
            ProtoEnvelope::targeted(caller_ura.clone(), target.callee_ura.clone(), subject_ura)?
                .with_causal_context(causal_context)
                .signed_descriptor_ref_invoke_request_with_signer(
                    target.as_str(),
                    target.descriptor_ref(),
                    arguments,
                    &signer,
                )
                .await?;
        request.content_type = "application/json".to_string();
        request.content_envelope = Some(easynet_axon::pb::axon::v1::ContentEnvelope {
            content_type: "application/json".to_string(),
            encoding: "identity".to_string(),
            ..easynet_axon::pb::axon::v1::ContentEnvelope::default()
        });
        request.timeout_seconds = timeout_seconds;
        let response_binding =
            ForwardedInvocationBinding::from_request(&request).map_err(|status| {
                anyhow!(
                    "remote Invoke request is not receipt-verifiable (code={:?}): {}",
                    status.code(),
                    status.message(),
                )
            })?;

        let channel = crate::support::platform::local_daemon_grpc::connect_channel(
            socket_path.clone(),
            timeout,
            Duration::from_secs(10),
        )
        .await
        .context("connect to local daemon gRPC endpoint")?;

        let mut client = InvocationClient::new(channel);
        let response = client.invoke(request).await.map_err(|status| {
            anyhow!(
                "daemon rejected canonical remote invocation `{}` for target `{}` \
                 (code={:?}): {}",
                target.as_str(),
                target.execution_target_ura(),
                status.code(),
                status.message(),
            )
        })?;
        let body = response.into_inner();
        let finalized =
            verify_completed_remote_invoke_response("remote Invoke", &response_binding, body)?;
        decode_invoke_result_bytes(&finalized.output)
    })
}

fn resolve_remote_caller_ura(explicit: Option<&str>) -> anyhow::Result<String> {
    if let Some(caller) = explicit.map(str::trim).filter(|value| !value.is_empty()) {
        crate::core::ura::parse_ura(caller)
            .map_err(|err| anyhow!("remote caller URA `{caller}` is invalid: {err}"))?;
        return Ok(caller.to_string());
    }
    let local_daemon = crate::daemon::identity::local_invocation::local_daemon_ura();
    if crate::core::ura::parse_ura(&local_daemon).is_ok()
        && !is_unpaired_local_device_ura(&local_daemon)
    {
        return Ok(local_daemon);
    }
    let credentials = crate::daemon::persistence::config::load_credentials().map_err(|err| {
        anyhow!(
            "remote invocation requires an explicit caller identity and signer; \
             credentials could not provide one: {err}"
        )
    })?;
    let realm = credentials.realm.trim();
    let node_id = credentials.node_id.trim();
    if realm.is_empty() || node_id.is_empty() {
        bail!(
            "remote invocation requires an explicit caller identity and signer; \
             credentials.json is missing realm or node_id"
        );
    }
    Ok(crate::core::ura::device_ura(realm, node_id))
}

fn is_unpaired_local_device_ura(ura: &str) -> bool {
    ura == crate::core::ura::device_ura(
        crate::daemon::identity::local_invocation::UNPAIRED_LOCAL_REALM,
        crate::daemon::identity::local_invocation::UNPAIRED_LOCAL_DEVICE_ID,
    )
}

fn causal_context_from_parents(
    causal_parents: &[Value],
) -> anyhow::Result<easynet_axon::pb::axon::v1::CausalContext> {
    use easynet_axon::pb::axon::v1::{
        causal_context, CausalContext, Empty, ReceiptList, ReceiptRef,
    };

    let mut refs = Vec::with_capacity(causal_parents.len());
    for (index, parent) in causal_parents.iter().enumerate() {
        let receipt_ura = parent
            .get("receipt_ura")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .ok_or_else(|| anyhow!("causal parent #{index} is missing receipt_ura"))?;
        let hash_hex = parent
            .get("receipt_hash")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .ok_or_else(|| anyhow!("causal parent #{index} is missing receipt_hash"))?;
        let receipt_hash = hex::decode(hash_hex)
            .with_context(|| format!("decode causal parent #{index} receipt_hash as hex"))?;
        if receipt_hash.len() != 32 {
            bail!(
                "causal parent #{index} receipt_hash must decode to 32 bytes, got {}",
                receipt_hash.len()
            );
        }
        refs.push(ReceiptRef {
            receipt_hash,
            receipt_ura: receipt_ura.to_string(),
        });
    }
    let form = match refs.len() {
        0 => causal_context::Form::None(Empty {}),
        1 => causal_context::Form::Scalar(refs.remove(0)),
        _ => causal_context::Form::List(ReceiptList { prior: refs }),
    };
    Ok(CausalContext { form: Some(form) })
}

pub(crate) fn ensure_completed_invoke_response(
    surface: &str,
    body: &InvokeResponse,
) -> anyhow::Result<()> {
    let completed = easynet_axon::invocation::InvocationState::Completed.to_wire_i32();
    if body.state == completed {
        return Ok(());
    }

    let state = WireInvocationState::try_from(body.state)
        .map(|state| state.as_str_name().to_string())
        .unwrap_or_else(|_| format!("UNKNOWN_STATE_{}", body.state));
    let error = body.error.as_ref();
    let (code, message) = error
        .map(|error| {
            (
                error.code.trim().to_string(),
                error.message.trim().to_string(),
            )
        })
        .unwrap_or_else(|| {
            (
                "INVOKE_NOT_COMPLETED".to_string(),
                "InvokeResponse did not carry a structured error".to_string(),
            )
        });
    bail!(
        "{surface} did not complete: state={state} code={} message={}",
        if code.is_empty() {
            "INVOKE_NOT_COMPLETED"
        } else {
            code.as_str()
        },
        if message.is_empty() {
            "InvokeResponse did not carry an error message"
        } else {
            message.as_str()
        },
    )
}

fn verify_completed_remote_invoke_response(
    surface: &str,
    binding: &ForwardedInvocationBinding,
    body: InvokeResponse,
) -> anyhow::Result<ForwardedFinalizedInvocation> {
    let resolver =
        crate::support::platform::local_daemon_grpc::LocalKeyServiceReceiptResolver::new();
    let finalized = ForwardedFinalizedInvocation::verify_response(binding, body, &resolver)
        .map_err(|status| {
            anyhow!(
                "{surface} receipt finalization failed (code={:?}): {}",
                status.code(),
                status.message(),
            )
        })?;
    if finalized.terminal_state == easynet_axon::invocation::InvocationState::Completed {
        return Ok(finalized);
    }

    let (code, message) = finalized
        .failure
        .as_ref()
        .map(|error| {
            (
                error.code.trim().to_string(),
                error.message.trim().to_string(),
            )
        })
        .unwrap_or_else(|| {
            (
                "INVOKE_NOT_COMPLETED".to_string(),
                "verified terminal receipt did not carry a structured failure".to_string(),
            )
        });
    bail!(
        "{surface} did not complete: state={} code={} message={}",
        finalized.terminal_state.as_str(),
        if code.is_empty() {
            "INVOKE_NOT_COMPLETED"
        } else {
            code.as_str()
        },
        if message.is_empty() {
            "verified terminal receipt did not carry an error message"
        } else {
            message.as_str()
        },
    )
}

fn decode_invoke_result_bytes(result_bytes: &[u8]) -> anyhow::Result<Value> {
    if result_bytes.is_empty() {
        return Ok(Value::Null);
    }
    match serde_json::from_slice::<Value>(result_bytes) {
        Ok(v) => Ok(v),
        Err(_) => Ok(serde_json::json!({
            "result_bytes_len": result_bytes.len(),
            "result_bytes_hex": result_bytes
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect::<String>(),
        })),
    }
}

fn validate_remote_execution_target(
    execution_target_ura: &str,
    selector: &crate::core::ura::AbilitySelector,
) -> anyhow::Result<()> {
    let target = parse_ura(execution_target_ura)
        .map_err(|err| anyhow!("invalid target URA `{execution_target_ura}`: {err}"))?;
    let owner = parse_ura(selector.owner_ura()).map_err(|err| {
        anyhow!(
            "invalid ability owner URA `{}`: {err}",
            selector.owner_ura()
        )
    })?;
    if owner.realm != target.realm {
        bail!(
            "ability URA `{}` belongs to realm `{}`, but execution target `{}` belongs to realm `{}`",
            selector.ability_ura(),
            owner.realm,
            execution_target_ura,
            target.realm
        );
    }

    match (target.kind, selector.owner_kind()) {
        (URAKind::Device, "agent") => Ok(()),
        (URAKind::Device, "device") => {
            if selector.owner_ura() == execution_target_ura.trim() {
                Ok(())
            } else {
                bail!(
                    "device-owned ability URA `{}` must execute on its owning device `{}`, not `{}`",
                    selector.ability_ura(),
                    selector.owner_ura(),
                    execution_target_ura
                );
            }
        }
        (URAKind::Hub, "hub") => {
            if selector.owner_ura() == execution_target_ura.trim() {
                Ok(())
            } else {
                bail!(
                    "hub-owned ability URA `{}` must execute on its owning hub `{}`, not `{}`",
                    selector.ability_ura(),
                    selector.owner_ura(),
                    execution_target_ura
                );
            }
        }
        (URAKind::Hub, "agent") => Ok(()),
        (URAKind::Device, "hub") => bail!(
            "hub-owned ability URA `{}` requires a Hub execution target, not device `{}`",
            selector.ability_ura(),
            execution_target_ura
        ),
        (URAKind::Hub, "device") => bail!(
            "device-owned ability URA `{}` requires its owning Device execution target `{}`, not hub `{}`",
            selector.ability_ura(),
            selector.owner_ura(),
            execution_target_ura
        ),
        (target_kind, owner_kind) => bail!(
            "ability URA `{}` cannot execute on target `{}`: unsupported owner/target pair owner_kind={} target_kind={}",
            selector.ability_ura(),
            execution_target_ura,
            owner_kind,
            target_kind
        ),
    }
}

fn default_subject_ura_for_selector(selector: &crate::core::ura::AbilitySelector) -> String {
    if selector.owner_kind() == "hub" {
        selector.ability_ura().to_string()
    } else {
        selector.owner_ura().to_string()
    }
}

fn validate_remote_target_ura(target_ura: &str) -> anyhow::Result<()> {
    let parsed = parse_ura(target_ura)
        .map_err(|err| anyhow::anyhow!("invalid target URA `{target_ura}`: {err}"))?;
    match parsed.kind {
        URAKind::Device => Ok(()),
        URAKind::Hub => Ok(()),
        other => bail!("target URA `{target_ura}` must identify a Device or Hub, got kind={other}"),
    }
}

/// Cross-realm directory query against the local daemon's
/// `federation.discover` ability. Returns the parsed
/// `entries: [DirectoryEntry]` array verbatim. The single
/// dial path (UDS gRPC InvocationClient → daemon's
/// `dispatch_federation_discover`) is shared with
/// `easynet federation discover`'s own subcommand — having
/// one helper means `device list` / `auth devices` / future
/// fan-out callers cannot drift on caller URA / envelope
/// shape.
///
/// Args:
///   * `agent_ura_filter` — optional URA filter passed verbatim
///     to the daemon. `None` returns the full federated
///     directory; `Some(ura)` returns at most one entry (lex
///     tie-break on peer realm).
/// Returns the `entries` array as a `Vec<Value>` (each element
/// is a `DirectoryEntry`-shaped JSON object).
pub fn invoke_federation_discover(agent_ura_filter: Option<&str>) -> anyhow::Result<Vec<Value>> {
    invoke_federation_discover_filtered(agent_ura_filter, None)
}

/// Same daemon-backed discovery path as `invoke_federation_discover`,
/// with the optional PR-N4 user-binding privacy filter exposed for
/// the operator CLI. Keeping this in the transport service avoids a
/// second facade-owned gRPC request builder that can drift from the
/// signed daemon IPC contract.
pub fn invoke_federation_discover_filtered(
    agent_ura_filter: Option<&str>,
    local_user_id_filter: Option<&str>,
) -> anyhow::Result<Vec<Value>> {
    let socket_path = crate::support::platform::local_daemon_grpc::resolve_socket_path();
    if !crate::support::platform::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let mut req_args = json!({});
    if let Some(ura) = agent_ura_filter {
        req_args["agent_ura"] = Value::String(ura.to_string());
    }
    if let Some(user) = local_user_id_filter {
        req_args["local_user_id"] = Value::String(user.to_string());
    }
    let arg_bytes = serde_json::to_vec(&req_args).context("encode discover args")?;

    let local_daemon_ura = crate::daemon::identity::local_invocation::local_daemon_ura();
    let subject_ura = federation_discover_subject_ura(&local_daemon_ura)?;
    let request = ProtoEnvelope::targeted(
        local_daemon_ura.as_str(),
        local_daemon_ura.as_str(),
        subject_ura.as_str(),
    )?
    .invoke_request("federation.discover", arg_bytes)?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation.discover")?;

    let response: easynet_axon::pb::axon::v1::InvokeResponse = {
        runtime.block_on(async move {
            let channel = crate::support::platform::local_daemon_grpc::connect_channel(
                socket_path.clone(),
                Duration::from_secs(10),
                Duration::from_secs(5),
            )
            .await
            .context("connect to local daemon gRPC endpoint")?;
            let mut client = InvocationClient::new(channel);
            let resp = client.invoke(request).await.map_err(|status| {
                anyhow!(
                    "daemon rejected federation.discover: code={:?} message={}",
                    status.code(),
                    status.message()
                )
            })?;
            Ok::<_, anyhow::Error>(resp.into_inner())
        })?
    };

    ensure_completed_invoke_response("federation.discover", &response)?;

    let body: Value =
        serde_json::from_slice(&response.result).context("decode discover response body")?;
    Ok(body
        .get("entries")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default())
}

fn federation_discover_subject_ura(callee_ura: &str) -> anyhow::Result<String> {
    let parsed = crate::core::ura::parse_ura(callee_ura)?;
    if parsed.kind == crate::core::ura::URAKind::Hub {
        return crate::core::ura::owner_ability_ura(callee_ura, "federation.discover").ok_or_else(
            || anyhow!("cannot derive federation.discover subject for hub callee `{callee_ura}`"),
        );
    }
    Ok(callee_ura.to_string())
}

/// `federation.revoke` against the local daemon's gRPC
/// InvocationServer. Removes the named Agent's directory entry on
/// the hub. CLI lifecycle surfaces (`easynet device remove`,
/// `easynet device reset --force`) call this helper instead of
/// relying on local-only `node.remove` acknowledgements.
///
/// Args:
///   * `agent_ura` — canonical URA of the Agent to revoke (typically
///     a device URA `easynet:///r/<realm>/device/<id>`).
///   * `reason` — operator-supplied label, written through to the
///     receipt for audit. `"deregister"` / `"reset"` are common.
/// Returns `Ok(())` on a successful ack from the daemon. Best-effort
/// by contract on the hub side, but this helper still surfaces
/// transport / parse errors so callers can log them honestly.
pub fn invoke_federation_revoke(agent_ura: &str, reason: &str) -> anyhow::Result<()> {
    let socket_path = crate::support::platform::local_daemon_grpc::resolve_socket_path();
    if !crate::support::platform::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let req_args = json!({
        "agent_ura": agent_ura,
        "reason": reason,
    });
    let arg_bytes = serde_json::to_vec(&req_args).context("encode revoke args")?;

    let local_daemon_ura = crate::daemon::identity::local_invocation::local_daemon_ura();
    let request = ProtoEnvelope::targeted(
        local_daemon_ura.as_str(),
        local_daemon_ura.as_str(),
        agent_ura,
    )?
    .invoke_request("federation.revoke", arg_bytes)?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation.revoke")?;

    runtime.block_on(async move {
        let channel = crate::support::platform::local_daemon_grpc::connect_channel(
            socket_path.clone(),
            Duration::from_secs(10),
            Duration::from_secs(5),
        )
        .await
        .context("connect to local daemon gRPC endpoint")?;
        let mut client = InvocationClient::new(channel);
        let response = client.invoke(request).await.map_err(|status| {
            anyhow!(
                "daemon rejected federation.revoke: code={:?} message={}",
                status.code(),
                status.message()
            )
        })?;
        ensure_completed_invoke_response("federation.revoke", &response.into_inner())?;
        Ok::<_, anyhow::Error>(())
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use easynet_axon::pb::axon::v1::causal_context::Form;

    #[test]
    fn parse_node_ura_accepts_protocol_hub_identity() {
        assert!(parse_node_ura("easynet:///r/realm/device/node-a").is_ok());
        assert!(parse_node_ura("easynet:///r/realm/hub").is_ok());
        assert!(parse_node_ura("https://hub.example").is_err());
    }

    #[test]
    fn parse_node_ura_rejects_hub_with_tail() {
        assert!(parse_node_ura("easynet:///r/realm/hub/extra").is_err());
    }

    #[test]
    fn plain_remote_system_ability_is_bound_to_catalog_descriptor() {
        let target = RemoteAbilityInvocationTarget::from_ability_ura(
            "easynet:///r/realm/device/node-a",
            "easynet:///r/realm/ability/device.node-a.fs.read",
        )
        .expect("target");
        let expected = crate::daemon::axon_bridge::descriptor_ref::catalog_descriptor_ref_for_wire(
            "easynet:///r/realm/device/node-a",
            "fs.read",
            crate::daemon::ability::CallMode::Rpc,
        )
        .expect("descriptor");
        assert_eq!(target.descriptor_ref(), expected);
    }

    #[test]
    fn explicit_descriptor_version_is_preserved() {
        let descriptor = "easynet:///r/realm/ability/device.node-a.echo@2.4.0#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!invoke";
        let target = RemoteAbilityInvocationTarget::from_descriptor_ref(
            "easynet:///r/realm/device/node-a",
            descriptor,
        )
        .expect("target");
        assert_eq!(target.descriptor_ref(), descriptor);
    }

    #[test]
    fn causal_parents_become_typed_receipt_list() {
        let parents = vec![
            serde_json::json!({
                "receipt_ura": "easynet:///r/realm/resource/agent.alice.worker/invocation/inv-one/receipt",
                "receipt_hash": "11".repeat(32),
            }),
            serde_json::json!({
                "receipt_ura": "easynet:///r/realm/resource/agent.alice.worker/invocation/inv-two/receipt",
                "receipt_hash": "22".repeat(32),
            }),
        ];
        let context = causal_context_from_parents(&parents).expect("typed context");
        let Some(Form::List(list)) = context.form else {
            panic!("expected causal list");
        };
        assert_eq!(list.prior.len(), 2);
        assert_eq!(list.prior[0].receipt_hash, vec![0x11; 32]);
    }

    #[test]
    fn remote_caller_defaults_to_discovered_hub_daemon_identity_without_credentials() {
        let _home = crate::cli::commands::test_support::HomeGuard::new();
        let path = crate::daemon::control::discovery::default_path();
        crate::daemon::control::discovery::write(
            &path,
            &crate::daemon::control::discovery::ControlDiscovery {
                socket_path: None,
                pipe_name: None,
                invocation_endpoint: None,
                daemon_identity: Some(crate::daemon::control::discovery::DaemonIdentity {
                    mode: "hub".to_string(),
                    realm: "localhost".to_string(),
                    node_id: None,
                }),
                pid: std::process::id(),
                daemon_version: "test".to_string(),
                supported_ipc_versions: crate::daemon::control::discovery::IpcVersionRange::single(
                    crate::daemon::control::discovery::IPC_VERSION_V1,
                ),
                capability_flags: Vec::new(),
                pages_port: None,
            },
        )
        .expect("write hub discovery");

        assert_eq!(
            resolve_remote_caller_ura(None).expect("hub caller"),
            crate::core::ura::hub_ura("localhost")
        );
    }

    #[test]
    fn federation_discover_subject_uses_hub_ability_subject_and_device_self_subject() {
        let hub = crate::core::ura::hub_ura("acme");
        assert_eq!(
            federation_discover_subject_ura(&hub).expect("hub subject"),
            crate::core::ura::owner_ability_ura(&hub, "federation.discover")
                .expect("hub ability subject")
        );

        let device = crate::core::ura::device_ura("acme", "device-a");
        assert_eq!(
            federation_discover_subject_ura(&device).expect("device subject"),
            device
        );
    }
}
