// EasyNet CLI — canonical remote invocation adapter
// ===================================================
//
// File: src/daemon/invocation/routing/remote_invoke.rs
// Description: Projects CLI/A2A/EAL remote targets into a complete,
//              descriptor-bound `InvokeRequest`, signs that request with the
//              caller owner, and submits it to the local daemon's canonical
//              `Invocation::invoke` endpoint.
//
// Wire shape
// ----------
// 1. Caller passes `(ability_ura, args, node_ura)`. `node_ura` must
//    be a canonical Axon Device or Hub URA; non-canonical inputs
//    surface as a typed error before any IPC.
// 2. The helper dials the local daemon's UDS-bound gRPC
//    `Invocation` server (default `~/.easynet/daemon.sock`).
// 3. It sends the actual ability/function, opaque arguments, complete signed
//    envelope, descriptor binding, content envelope, metadata, and deadline
//    in one `InvokeRequest`. Routing may change transport hops but never
//    projects these fields into an inner wrapper payload.
//
// Feature gating
// --------------
// `axon-pb` feature gates the entire module. Production builds run
// with `axon-pb` on; minimal builds (no daemon transport) can drop
// the cross-hub bridge along with the rest of the gRPC stack.
//
// Author: Silan.Hu <silan.hu@u.nus.edu>
// Copyright (c) 2026 EasyNet. All rights reserved.

use std::sync::Arc;
use std::time::Duration;

use anyhow::{anyhow, bail, Context};
use serde_json::{json, Value};

use crate::core::ura::{parse_ura, URAKind};
use crate::daemon::invocation::dispatch::forwarded_finalization::{
    ForwardedFinalizedInvocation, ForwardedInvocationBinding,
};
use crate::daemon::invocation::routing::target::InvocationCausalContext;
use crate::daemon::invocation::{
    InvocationDerivationPolicy, ProtoEnvelope, RootInvocationDerivationIssuer,
};
use axon_sdk::invocation::CausalContext;
use axon_sdk::pb::axon::v1::invocation_client::InvocationClient;
use axon_sdk::pb::axon::v1::{InvocationState as WireInvocationState, InvokeResponse};

/// Validate a `--node` argument as a canonical Axon Device or Hub URA.
/// Returns the URA string when it parses; surfaces a typed error
/// when it doesn't, with the exact wire-shape we expect quoted in
/// the message so the operator can fix the typo.
///
/// The grammar decision belongs to Axon. This helper only applies
/// the CLI policy distinction after parsing: `--node` may target a
/// Device or Hub URA, never a hosted Agent/User/Ability/Resource.
/// Hub targets must be generated by the CLI `hub_ura(realm)` facade,
/// whose canonical protocol identity is `easynet:///r/<realm>/authority`.
pub fn parse_node_ura(node: &str) -> anyhow::Result<String> {
    let trimmed = node.trim();
    let parsed = parse_ura(trimmed).map_err(|err| {
        anyhow::anyhow!(
            "--node `{trimmed}` is not a canonical Axon Device or Hub URA: {err}. \
             A bare hostname or `https://...` URL is not accepted. \
             {URA_DISCOVERY_HINT}"
        )
    })?;

    match parsed.kind {
        URAKind::Device => Ok(trimmed.to_string()),
        URAKind::Authority => Ok(trimmed.to_string()),
        other => bail!(
            "--node `{trimmed}` is a canonical Axon URA, but not a Device or Hub target. \
             Got kind={other}. \
             {URA_DISCOVERY_HINT}"
        ),
    }
}

/// Operator-actionable hint appended to every `--node` parse failure.
/// Names the four places a real URA can come from today, ordered
/// most-helpful-first. Centralised so the wording stays byte-identical
/// across both `parse_node_ura` failure arms — operators can grep one
/// substring across logs.
///
/// **PR-N1 user-flow review catch**: PR-N1 ships the CLI
/// invocation surface (commit 8/N) but cross-hub URA discovery
/// from a remote machine without manual config is PR-N3
/// territory (cross-realm directory federation, not yet shipped).
/// Until PR-N3 lands, operators construct URAs by hand from the
/// sources below; the error message points at them.
const URA_DISCOVERY_HINT: &str = "Where to find a canonical URA today (until PR-N3 cross-realm \
     directory federation ships): \
     (1) `cat ~/.easynet/credentials.json` on the target machine — \
     concat `easynet:///r/<realm>/device/<node_id>` from the fields. \
     (2) `cat ~/.easynet/daemon-config.toml` and read the \
     `[daemon.federated_peers]` table — keys are realms the \
     local daemon already trusts. \
     (3) `cat /etc/easynet/realm-trust.toml` and read \
     `[[trusted_agent]]` blocks with `role = \"hub\"` — those \
     are the peer hubs the cross-hub dialer can reach. \
     (4) `easynet ability list` — local-realm only \
     today; cross-realm enumeration ships in PR-N3.";

/// Complete caller-side target for a canonical remote invocation.
///
/// This value object is the root fix for the execution-target/callee-owner
/// split. `execution_target_ura` is the node or hub the local daemon sends the
/// frame to. `callee_ura` is the Agent/Device/Hub identity that advertises the
/// AbilityDescriptor. They are equal for device-owned system abilities and
/// intentionally different for hosted-agent abilities executed on a device.
///
/// What this is not: it is not a route answer. The remote daemon/authority remains
/// responsible for proving that a hosted Agent is actually runnable at the
/// execution target. This object only prevents the CLI from corrupting the
/// signed Invocation tuple before the resolver gets a chance to decide.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct RemoteAbilityInvocationTarget {
    execution_target_ura: String,
    ability_ura: String,
    callee_ura: String,
    public_ability: String,
    descriptor_ref: String,
}

impl RemoteAbilityInvocationTarget {
    /// Project a target-owned system ability selector into a full remote
    /// invocation target with descriptor binding deferred to that target.
    ///
    /// Use this for command adapters whose product contract is "call this
    /// device/authority-owned system ability on `--node`". It is deliberately named
    /// target-owned so it is not reused for arbitrary Ability URAs.
    pub(crate) fn for_target_owned_selector(
        execution_target_ura: &str,
        selector: &str,
    ) -> anyhow::Result<Self> {
        validate_remote_target_ura(execution_target_ura)?;
        let public_ability =
            crate::core::ura::owner_local_ability_name(execution_target_ura, selector);
        let ability_ura =
            crate::core::ura::owner_ability_ura(execution_target_ura, &public_ability).ok_or_else(
                || anyhow!("derive ability URA for {execution_target_ura} {public_ability}"),
            )?;
        Self::from_ability_ura(execution_target_ura, &ability_ura)
    }

    /// Accept an already-canonical Ability URA and bind it to an execution
    /// target without rewriting the Ability owner.
    pub(crate) fn from_ability_ura(
        execution_target_ura: &str,
        ability_ura: &str,
    ) -> anyhow::Result<Self> {
        validate_remote_target_ura(execution_target_ura)?;
        let trimmed = ability_ura.trim();
        let selector = crate::core::ura::AbilitySelector::parse(trimmed)?;
        validate_remote_execution_target(execution_target_ura, &selector)?;
        let descriptor_ref =
            crate::daemon::axon_bridge::descriptor_ref::catalog_descriptor_ref_for_wire(
                selector.owner_ura(),
                selector.public_name(),
                crate::daemon::ability::CallMode::Rpc,
            )
            .map_err(|err| {
                anyhow!(
                    "ability URA `{trimmed}` is not descriptor-bound and no local system catalog \
                     descriptor can prove it: {err}. Pass an explicit descriptor-bound Ability ref."
                )
            })?;
        Ok(Self::from_validated_selector(
            execution_target_ura,
            trimmed,
            &selector,
            descriptor_ref,
        ))
    }

    /// Accept a descriptor-bound Ability ref and preserve the version for
    /// origin-caller proof generation.
    pub(crate) fn from_descriptor_ref(
        execution_target_ura: &str,
        descriptor_ref: &str,
    ) -> anyhow::Result<Self> {
        let canonical = axon_sdk::invocation::canonical_ability_descriptor_ref(descriptor_ref)
            .map_err(|err| anyhow!("invalid descriptor-bound Ability ref: {err}"))?;
        let ability_ura =
            crate::daemon::axon_bridge::descriptor_ref::ability_ura_from_descriptor_ref(&canonical)
                .map_err(|err| {
                    anyhow!("descriptor-bound Ability ref is missing ability URA: {err}")
                })?;
        validate_remote_target_ura(execution_target_ura)?;
        let selector = crate::core::ura::AbilitySelector::parse(&ability_ura)?;
        validate_remote_execution_target(execution_target_ura, &selector)?;
        Ok(Self::from_validated_selector(
            execution_target_ura,
            &ability_ura,
            &selector,
            canonical,
        ))
    }

    fn from_validated_selector(
        execution_target_ura: &str,
        ability_ura: &str,
        selector: &crate::core::ura::AbilitySelector,
        descriptor_ref: String,
    ) -> Self {
        Self {
            execution_target_ura: execution_target_ura.trim().to_string(),
            ability_ura: ability_ura.trim().to_string(),
            callee_ura: selector.owner_ura().to_string(),
            public_ability: selector.public_name().to_string(),
            descriptor_ref,
        }
    }

    /// Borrow the canonical URA for the transport helper.
    pub(crate) fn as_str(&self) -> &str {
        &self.ability_ura
    }

    /// Node or hub that receives the forwarding request.
    pub(crate) fn execution_target_ura(&self) -> &str {
        &self.execution_target_ura
    }

    pub(crate) fn descriptor_ref(&self) -> &str {
        &self.descriptor_ref
    }

    pub(crate) fn callee_ura(&self) -> &str {
        &self.callee_ura
    }
}

/// Complete caller-owned facts for one descriptor-bound remote invocation.
///
/// The selected target supplies only the descriptor-bound `ability` and
/// `callee`. Every remaining semantic field is mandatory here so the transport
/// cannot recover identities, invent causal placement, or mint freshness on
/// behalf of a public/product caller.
pub(crate) struct RemoteInvocationRequest<'a> {
    target: &'a RemoteAbilityInvocationTarget,
    caller_ura: String,
    subject_ura: String,
    invocation_nonce: [u8; 16],
    causal_context: CausalContext,
    args: Value,
    timeout: Duration,
}

/// Named subject derivation for a remote invocation tuple.
///
/// Public compatibility may still offer ergonomic subject omission, but the
/// selected subject must be materialized under one of these labels before
/// dispatch so RF-8 cannot regress to silent callee/descriptor substitution.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RemoteInvocationSubject {
    Explicit(String),
    TargetOwnedSystem(String),
}

impl RemoteInvocationSubject {
    fn resolve(&self) -> anyhow::Result<String> {
        let (value, field) = match self {
            Self::Explicit(value) => (value, "explicit subject"),
            Self::TargetOwnedSystem(value) => (value, "target-owned system subject"),
        };
        checked_remote_invocation_ura(value.clone(), field)
    }

    #[cfg(test)]
    fn policy_name(&self) -> &'static str {
        match self {
            Self::Explicit(_) => "Explicit",
            Self::TargetOwnedSystem(_) => "TargetOwnedSystem",
        }
    }
}

/// Explicit nonce selected before remote transport dispatch.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RemoteInvocationNonce {
    Explicit([u8; 16]),
}

impl RemoteInvocationNonce {
    fn derive(self) -> [u8; 16] {
        match self {
            Self::Explicit(nonce) => nonce,
        }
    }
}

/// Inspectable seven-field tuple plan for remote descriptor-bound dispatch.
///
/// This object is CLI policy, not Axon canonical wire state. It makes the
/// subject, nonce, and causal derivation policy explicit before lowering into
/// `RemoteInvocationRequest`, which then enters the existing descriptor-bound
/// runtime path.
pub(crate) struct RemoteInvocationTuplePlan<'a> {
    target: &'a RemoteAbilityInvocationTarget,
    caller_ura: String,
    subject: RemoteInvocationSubject,
    nonce: RemoteInvocationNonce,
    causal_context: InvocationCausalContext,
    args: Value,
    timeout: Duration,
}

pub(crate) fn declared_root_causal_context() -> CausalContext {
    CausalContext::None
}

impl<'a> RemoteInvocationTuplePlan<'a> {
    pub(crate) fn public_explicit(
        target: &'a RemoteAbilityInvocationTarget,
        caller_ura: impl Into<String>,
        subject_ura: impl Into<String>,
        invocation_nonce: [u8; 16],
        causal_context: CausalContext,
        args: Value,
        timeout: Duration,
    ) -> anyhow::Result<Self> {
        Self::new(
            target,
            caller_ura,
            RemoteInvocationSubject::Explicit(subject_ura.into()),
            RemoteInvocationNonce::Explicit(invocation_nonce),
            InvocationCausalContext::explicit(causal_context),
            args,
            timeout,
        )
    }

    fn with_explicit_nonce(
        target: &'a RemoteAbilityInvocationTarget,
        caller_ura: impl Into<String>,
        subject: RemoteInvocationSubject,
        invocation_nonce: [u8; 16],
        causal_context: CausalContext,
        args: Value,
        timeout: Duration,
    ) -> anyhow::Result<Self> {
        Self::new(
            target,
            caller_ura,
            subject,
            RemoteInvocationNonce::Explicit(invocation_nonce),
            InvocationCausalContext::explicit(causal_context),
            args,
            timeout,
        )
    }

    fn system_root_with_explicit_nonce(
        target: &'a RemoteAbilityInvocationTarget,
        caller_ura: impl Into<String>,
        subject: RemoteInvocationSubject,
        invocation_nonce: [u8; 16],
        args: Value,
        timeout: Duration,
    ) -> anyhow::Result<Self> {
        Self::new(
            target,
            caller_ura,
            subject,
            RemoteInvocationNonce::Explicit(invocation_nonce),
            InvocationCausalContext::daemon_system_root(),
            args,
            timeout,
        )
    }

    fn new(
        target: &'a RemoteAbilityInvocationTarget,
        caller_ura: impl Into<String>,
        subject: RemoteInvocationSubject,
        nonce: RemoteInvocationNonce,
        causal_context: InvocationCausalContext,
        args: Value,
        timeout: Duration,
    ) -> anyhow::Result<Self> {
        let caller_ura = checked_remote_invocation_ura(caller_ura.into(), "caller")?;
        if timeout.is_zero() {
            bail!("remote invocation timeout must be greater than zero");
        }
        subject.resolve()?;
        Ok(Self {
            target,
            caller_ura,
            subject,
            nonce,
            causal_context,
            args,
            timeout,
        })
    }

    pub(crate) fn into_request(self) -> anyhow::Result<RemoteInvocationRequest<'a>> {
        RemoteInvocationRequest::new(
            self.target,
            self.caller_ura,
            self.subject.resolve()?,
            self.nonce.derive(),
            self.causal_context.as_axon(),
            self.args,
            self.timeout,
        )
    }
}

/// Issuer for daemon-owned remote root calls.
///
/// System callers select caller, subject, target, and timeout; only this issuer
/// mints the fresh nonce used for the named daemon-system root policy.
pub(crate) struct RemoteSystemInvocationIssuer;

impl RemoteSystemInvocationIssuer {
    pub(crate) fn root_plan<'a>(
        target: &'a RemoteAbilityInvocationTarget,
        caller_ura: impl Into<String>,
        subject: RemoteInvocationSubject,
        args: Value,
        timeout: Duration,
    ) -> anyhow::Result<RemoteInvocationTuplePlan<'a>> {
        RemoteInvocationTuplePlan::system_root_with_explicit_nonce(
            target,
            caller_ura,
            subject,
            axon_sdk::invocation::fresh_nonce(),
            args,
            timeout,
        )
    }
}

/// Issuer for child/continuation remote calls spawned from admitted runtime
/// context. The parent causal context is explicit; freshness is centralized
/// here rather than minted by product bridge code.
pub(crate) struct RemoteChildInvocationIssuer;

impl RemoteChildInvocationIssuer {
    pub(crate) fn child_plan<'a>(
        target: &'a RemoteAbilityInvocationTarget,
        caller_ura: impl Into<String>,
        subject: RemoteInvocationSubject,
        causal_context: CausalContext,
        args: Value,
        timeout: Duration,
    ) -> anyhow::Result<RemoteInvocationTuplePlan<'a>> {
        RemoteInvocationTuplePlan::with_explicit_nonce(
            target,
            caller_ura,
            subject,
            axon_sdk::invocation::fresh_nonce(),
            causal_context,
            args,
            timeout,
        )
    }
}

impl<'a> RemoteInvocationRequest<'a> {
    fn new(
        target: &'a RemoteAbilityInvocationTarget,
        caller_ura: impl Into<String>,
        subject_ura: impl Into<String>,
        invocation_nonce: [u8; 16],
        causal_context: CausalContext,
        args: Value,
        timeout: Duration,
    ) -> anyhow::Result<Self> {
        let caller_ura = checked_remote_invocation_ura(caller_ura.into(), "caller")?;
        let subject_ura = checked_remote_invocation_ura(subject_ura.into(), "subject")?;
        if invocation_nonce == [0; 16] {
            bail!("remote invocation nonce must not be all-zero");
        }
        if timeout.is_zero() {
            bail!("remote invocation timeout must be greater than zero");
        }
        Ok(Self {
            target,
            caller_ura,
            subject_ura,
            invocation_nonce,
            causal_context,
            args,
            timeout,
        })
    }
}

pub(crate) fn invoke_remote_target(request: RemoteInvocationRequest<'_>) -> anyhow::Result<Value> {
    let RemoteInvocationRequest {
        target,
        caller_ura,
        subject_ura,
        invocation_nonce,
        causal_context,
        args,
        timeout,
    } = request;
    let socket_path = crate::support::platform::local_daemon_grpc::resolve_socket_path();
    if !crate::support::platform::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let arguments = serde_json::to_vec(&args).context("serialise remote invocation arguments")?;
    let timeout_seconds = i32::try_from(timeout.as_secs().max(1)).unwrap_or(i32::MAX);

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for canonical remote invoke")?;

    runtime.block_on(async move {
        let signer = crate::daemon::identity::self_identity::RuntimeSigningIdentity::load_default(
            caller_ura.clone(),
        )
        .map_err(|err| {
            anyhow!(
                "remote invocation requires a caller signer for `{caller_ura}`; \
                 load or provision that identity in the local key service: {err}"
            )
        })?;
        let mut request = ProtoEnvelope::from_target(
            caller_ura.clone(),
            target.callee_ura.clone(),
            subject_ura,
            InvocationDerivationPolicy::Explicit {
                invocation_nonce,
                causal_context,
            },
        )?
        .signed_descriptor_ref_invoke_request_with_signer(
            target.as_str(),
            target.descriptor_ref(),
            arguments,
            &signer,
        )
        .await?;
        request.content_type = "application/json".to_string();
        request.content_envelope = Some(axon_sdk::pb::axon::v1::ContentEnvelope {
            content_type: "application/json".to_string(),
            encoding: "identity".to_string(),
            ..axon_sdk::pb::axon::v1::ContentEnvelope::default()
        });
        request.timeout_seconds = timeout_seconds;
        let response_binding =
            ForwardedInvocationBinding::from_request(&request).map_err(|status| {
                anyhow!(
                    "remote Invoke request is not receipt-verifiable (code={:?}): {}",
                    status.code(),
                    status.message(),
                )
            })?;

        let channel = crate::support::platform::local_daemon_grpc::connect_channel(
            socket_path.clone(),
            timeout,
            Duration::from_secs(10),
        )
        .await
        .context("connect to local daemon gRPC endpoint")?;

        let mut client = InvocationClient::new(channel);
        let response = client.invoke(request).await.map_err(|status| {
            anyhow!(
                "daemon rejected canonical remote invocation `{}` for target `{}` \
                 (code={:?}): {}",
                target.as_str(),
                target.execution_target_ura(),
                status.code(),
                status.message(),
            )
        })?;
        let body = response.into_inner();
        let finalized =
            verify_completed_remote_invoke_response("remote Invoke", &response_binding, body)?;
        decode_invoke_result_bytes(&finalized.output)
    })
}

fn checked_remote_invocation_ura(value: String, field: &str) -> anyhow::Result<String> {
    let value = value.trim();
    if value.is_empty() {
        bail!("remote invocation {field} URA must not be empty");
    }
    crate::core::ura::parse_ura(value)
        .map_err(|err| anyhow!("remote invocation {field} URA `{value}` is invalid: {err}"))?;
    Ok(value.to_string())
}

pub(crate) fn ensure_completed_invoke_response(
    surface: &str,
    body: &InvokeResponse,
) -> anyhow::Result<()> {
    let completed = axon_sdk::invocation::InvocationState::Completed.to_wire_i32();
    if body.state == completed {
        return Ok(());
    }

    let state = WireInvocationState::try_from(body.state)
        .map(|state| state.as_str_name().to_string())
        .unwrap_or_else(|_| format!("UNKNOWN_STATE_{}", body.state));
    let error = body.error.as_ref();
    let (code, message) = error
        .map(|error| {
            (
                error.code.trim().to_string(),
                error.message.trim().to_string(),
            )
        })
        .unwrap_or_else(|| {
            (
                "INVOKE_NOT_COMPLETED".to_string(),
                "InvokeResponse did not carry a structured error".to_string(),
            )
        });
    bail!(
        "{surface} did not complete: state={state} code={} message={}",
        if code.is_empty() {
            "INVOKE_NOT_COMPLETED"
        } else {
            code.as_str()
        },
        if message.is_empty() {
            "InvokeResponse did not carry an error message"
        } else {
            message.as_str()
        },
    )
}

fn verify_completed_remote_invoke_response(
    surface: &str,
    binding: &ForwardedInvocationBinding,
    body: InvokeResponse,
) -> anyhow::Result<ForwardedFinalizedInvocation> {
    let resolver = remote_receipt_key_resolver()?;
    let finalized = ForwardedFinalizedInvocation::verify_response(binding, body, &resolver)
        .map_err(|status| {
            anyhow!(
                "{surface} receipt finalization failed (code={:?}): {}",
                status.code(),
                status.message(),
            )
        })?;
    if finalized.terminal_state == axon_sdk::invocation::InvocationState::Completed {
        return Ok(finalized);
    }

    let (code, message) = finalized
        .failure
        .as_ref()
        .map(|error| {
            (
                error.code.trim().to_string(),
                error.message.trim().to_string(),
            )
        })
        .unwrap_or_else(|| {
            (
                "INVOKE_NOT_COMPLETED".to_string(),
                "verified terminal receipt did not carry a structured failure".to_string(),
            )
        });
    bail!(
        "{surface} did not complete: state={} code={} message={}",
        finalized.terminal_state.as_str(),
        if code.is_empty() {
            "INVOKE_NOT_COMPLETED"
        } else {
            code.as_str()
        },
        if message.is_empty() {
            "verified terminal receipt did not carry an error message"
        } else {
            message.as_str()
        },
    )
}

type RemoteReceiptKeyResolver = crate::daemon::trust::key_resolver::RealmTrustAnchorKeyResolver;

fn remote_receipt_key_resolver() -> anyhow::Result<RemoteReceiptKeyResolver> {
    let trust_path = crate::daemon::trust::anchor::trust_anchor_path_from_env_or_default();
    let trust_context = format!(
        "load realm trust anchor for remote receipt verification: {}",
        trust_path.display()
    );
    let trust_anchor = crate::daemon::trust::anchor::RealmTrustAnchor::load_or_empty(&trust_path)
        .with_context(|| trust_context)?;
    Ok(
        crate::daemon::trust::key_resolver::RealmTrustAnchorKeyResolver::new(
            crate::daemon::trust::cell::SharedTrustAnchor::new(Arc::new(trust_anchor)),
        ),
    )
}

fn decode_invoke_result_bytes(result_bytes: &[u8]) -> anyhow::Result<Value> {
    if result_bytes.is_empty() {
        return Ok(Value::Null);
    }
    match serde_json::from_slice::<Value>(result_bytes) {
        Ok(v) => Ok(v),
        Err(_) => Ok(serde_json::json!({
            "result_bytes_len": result_bytes.len(),
            "result_bytes_hex": result_bytes
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect::<String>(),
        })),
    }
}

fn validate_remote_execution_target(
    execution_target_ura: &str,
    selector: &crate::core::ura::AbilitySelector,
) -> anyhow::Result<()> {
    let target = parse_ura(execution_target_ura)
        .map_err(|err| anyhow!("invalid target URA `{execution_target_ura}`: {err}"))?;
    let owner = parse_ura(selector.owner_ura()).map_err(|err| {
        anyhow!(
            "invalid ability owner URA `{}`: {err}",
            selector.owner_ura()
        )
    })?;
    if owner.realm != target.realm {
        bail!(
            "ability URA `{}` belongs to realm `{}`, but execution target `{}` belongs to realm `{}`",
            selector.ability_ura(),
            owner.realm,
            execution_target_ura,
            target.realm
        );
    }

    match (target.kind, selector.owner_kind()) {
        (URAKind::Device, "agent") => Ok(()),
        (URAKind::Device, "device") => {
            if selector.owner_ura() == execution_target_ura.trim() {
                Ok(())
            } else {
                bail!(
                    "device-owned ability URA `{}` must execute on its owning device `{}`, not `{}`",
                    selector.ability_ura(),
                    selector.owner_ura(),
                    execution_target_ura
                );
            }
        }
        (URAKind::Authority, "hub") => {
            if selector.owner_ura() == execution_target_ura.trim() {
                Ok(())
            } else {
                bail!(
                    "hub-owned ability URA `{}` must execute on its owning hub `{}`, not `{}`",
                    selector.ability_ura(),
                    selector.owner_ura(),
                    execution_target_ura
                );
            }
        }
        (URAKind::Authority, "agent") => Ok(()),
        (URAKind::Device, "hub") => bail!(
            "hub-owned ability URA `{}` requires a Hub execution target, not device `{}`",
            selector.ability_ura(),
            execution_target_ura
        ),
        (URAKind::Authority, "device") => bail!(
            "device-owned ability URA `{}` requires its owning Device execution target `{}`, not hub `{}`",
            selector.ability_ura(),
            selector.owner_ura(),
            execution_target_ura
        ),
        (target_kind, owner_kind) => bail!(
            "ability URA `{}` cannot execute on target `{}`: unsupported owner/target pair owner_kind={} target_kind={}",
            selector.ability_ura(),
            execution_target_ura,
            owner_kind,
            target_kind
        ),
    }
}

fn validate_remote_target_ura(target_ura: &str) -> anyhow::Result<()> {
    let parsed = parse_ura(target_ura)
        .map_err(|err| anyhow::anyhow!("invalid target URA `{target_ura}`: {err}"))?;
    match parsed.kind {
        URAKind::Device => Ok(()),
        URAKind::Authority => Ok(()),
        other => bail!("target URA `{target_ura}` must identify a Device or Hub, got kind={other}"),
    }
}

/// Cross-realm directory query against the local daemon's
/// `federation.discover` ability. Returns the parsed
/// `entries: [DirectoryEntry]` array verbatim. The single
/// dial path (UDS gRPC InvocationClient → daemon's
/// `dispatch_federation_discover`) is shared with
/// `easynet federation discover`'s own subcommand — having
/// one helper means `device list` / `auth devices` / future
/// fan-out callers cannot drift on caller URA / envelope
/// shape.
///
/// Args:
///   * `agent_ura_filter` — optional URA filter passed verbatim
///     to the daemon. `None` returns the full federated
///     directory; `Some(ura)` returns at most one entry (lex
///     tie-break on peer realm).
/// Returns the `entries` array as a `Vec<Value>` (each element
/// is a `DirectoryEntry`-shaped JSON object).
pub fn invoke_federation_discover(agent_ura_filter: Option<&str>) -> anyhow::Result<Vec<Value>> {
    invoke_federation_discover_filtered(agent_ura_filter, None)
}

/// Same daemon-backed discovery path as `invoke_federation_discover`,
/// with the optional PR-N4 user-binding privacy filter exposed for
/// the operator CLI. Keeping this in the transport service avoids a
/// second facade-owned gRPC request builder that can drift from the
/// signed daemon IPC contract.
pub fn invoke_federation_discover_filtered(
    agent_ura_filter: Option<&str>,
    local_user_id_filter: Option<&str>,
) -> anyhow::Result<Vec<Value>> {
    let socket_path = crate::support::platform::local_daemon_grpc::resolve_socket_path();
    if !crate::support::platform::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let mut req_args = json!({});
    if let Some(ura) = agent_ura_filter {
        req_args["agent_ura"] = Value::String(ura.to_string());
    }
    if let Some(user) = local_user_id_filter {
        req_args["local_user_id"] = Value::String(user.to_string());
    }
    let arg_bytes = serde_json::to_vec(&req_args).context("encode discover args")?;

    let local_daemon_ura = crate::daemon::identity::local_invocation::local_daemon_ura();
    let subject_ura = federation_discover_subject_ura(&local_daemon_ura)?;
    let request = ProtoEnvelope::from_target(
        local_daemon_ura.as_str(),
        local_daemon_ura.as_str(),
        subject_ura.as_str(),
        RootInvocationDerivationIssuer::fresh_root(),
    )?
    .invoke_request("federation.discover", arg_bytes)?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation.discover")?;

    let response: axon_sdk::pb::axon::v1::InvokeResponse = {
        runtime.block_on(async move {
            let channel = crate::support::platform::local_daemon_grpc::connect_channel(
                socket_path.clone(),
                Duration::from_secs(10),
                Duration::from_secs(5),
            )
            .await
            .context("connect to local daemon gRPC endpoint")?;
            let mut client = InvocationClient::new(channel);
            let resp = client.invoke(request).await.map_err(|status| {
                anyhow!(
                    "daemon rejected federation.discover: code={:?} message={}",
                    status.code(),
                    status.message()
                )
            })?;
            Ok::<_, anyhow::Error>(resp.into_inner())
        })?
    };

    ensure_completed_invoke_response("federation.discover", &response)?;

    let body: Value =
        serde_json::from_slice(&response.result).context("decode discover response body")?;
    Ok(body
        .get("entries")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default())
}

fn federation_discover_subject_ura(callee_ura: &str) -> anyhow::Result<String> {
    let parsed = crate::core::ura::parse_ura(callee_ura)?;
    if parsed.kind == crate::core::ura::URAKind::Authority {
        return crate::core::ura::owner_ability_ura(callee_ura, "federation.discover").ok_or_else(
            || anyhow!("cannot derive federation.discover subject for hub callee `{callee_ura}`"),
        );
    }
    Ok(callee_ura.to_string())
}

/// `federation.revoke` against the local daemon's gRPC
/// InvocationServer. Removes the named Agent's directory entry on
/// the hub. CLI lifecycle surfaces (`easynet device remove`,
/// `easynet device reset --force`) call this helper instead of
/// relying on local-only `node.remove` acknowledgements.
///
/// Args:
///   * `agent_ura` — canonical URA of the Agent to revoke (typically
///     a device URA `easynet:///r/<realm>/device/<id>`).
///   * `reason` — operator-supplied label, written through to the
///     receipt for audit. `"deregister"` / `"reset"` are common.
/// Returns `Ok(())` on a successful ack from the daemon. Best-effort
/// by contract on the hub side, but this helper still surfaces
/// transport / parse errors so callers can log them honestly.
pub fn invoke_federation_revoke(agent_ura: &str, reason: &str) -> anyhow::Result<()> {
    let socket_path = crate::support::platform::local_daemon_grpc::resolve_socket_path();
    if !crate::support::platform::local_daemon_grpc::probe_accepting(&socket_path) {
        bail!(
            "daemon not running (local gRPC listener unreachable at {}). \
             Start it with `easynet runtime start`.",
            socket_path.display()
        );
    }

    let req_args = json!({
        "agent_ura": agent_ura,
        "reason": reason,
    });
    let arg_bytes = serde_json::to_vec(&req_args).context("encode revoke args")?;

    let local_daemon_ura = crate::daemon::identity::local_invocation::local_daemon_ura();
    let request = ProtoEnvelope::from_target(
        local_daemon_ura.as_str(),
        local_daemon_ura.as_str(),
        agent_ura,
        RootInvocationDerivationIssuer::fresh_root(),
    )?
    .invoke_request("federation.revoke", arg_bytes)?;

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("build tokio runtime for federation.revoke")?;

    runtime.block_on(async move {
        let channel = crate::support::platform::local_daemon_grpc::connect_channel(
            socket_path.clone(),
            Duration::from_secs(10),
            Duration::from_secs(5),
        )
        .await
        .context("connect to local daemon gRPC endpoint")?;
        let mut client = InvocationClient::new(channel);
        let response = client.invoke(request).await.map_err(|status| {
            anyhow!(
                "daemon rejected federation.revoke: code={:?} message={}",
                status.code(),
                status.message()
            )
        })?;
        ensure_completed_invoke_response("federation.revoke", &response.into_inner())?;
        Ok::<_, anyhow::Error>(())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_node_ura_accepts_protocol_hub_identity() {
        assert!(parse_node_ura("easynet:///r/realm/device/node-a").is_ok());
        assert!(parse_node_ura("easynet:///r/realm/authority").is_ok());
        assert!(parse_node_ura("https://authority.example").is_err());
    }

    #[test]
    fn parse_node_ura_rejects_hub_with_tail() {
        assert!(parse_node_ura("easynet:///r/realm/authority/extra").is_err());
    }

    #[test]
    fn plain_remote_system_ability_is_bound_to_catalog_descriptor() {
        let target = RemoteAbilityInvocationTarget::from_ability_ura(
            "easynet:///r/realm/device/node-a",
            "easynet:///r/realm/ability/device.node-a.fs.read",
        )
        .expect("target");
        let expected = crate::daemon::axon_bridge::descriptor_ref::catalog_descriptor_ref_for_wire(
            "easynet:///r/realm/device/node-a",
            "fs.read",
            crate::daemon::ability::CallMode::Rpc,
        )
        .expect("descriptor");
        assert_eq!(target.descriptor_ref(), expected);
    }

    #[test]
    fn explicit_descriptor_version_is_preserved() {
        let descriptor = "easynet:///r/realm/ability/device.node-a.echo@2.4.0#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!invoke";
        let target = RemoteAbilityInvocationTarget::from_descriptor_ref(
            "easynet:///r/realm/device/node-a",
            descriptor,
        )
        .expect("target");
        assert_eq!(target.descriptor_ref(), descriptor);
    }

    #[test]
    fn remote_request_preserves_explicit_tuple_facts() {
        let descriptor = "easynet:///r/realm/ability/device.node-a.echo@2.4.0#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!invoke";
        let target = RemoteAbilityInvocationTarget::from_descriptor_ref(
            "easynet:///r/realm/device/node-a",
            descriptor,
        )
        .expect("target");
        let request = RemoteInvocationRequest::new(
            &target,
            "easynet:///r/realm/device/caller",
            "easynet:///r/realm/resource/device.node-a/probe/alive",
            [0x42; 16],
            CausalContext::None,
            json!({"probe": true}),
            Duration::from_secs(7),
        )
        .expect("complete request");

        assert_eq!(request.caller_ura, "easynet:///r/realm/device/caller");
        assert_eq!(
            request.subject_ura,
            "easynet:///r/realm/resource/device.node-a/probe/alive"
        );
        assert_eq!(request.invocation_nonce, [0x42; 16]);
        assert_eq!(request.causal_context, CausalContext::None);
        assert_eq!(request.timeout, Duration::from_secs(7));
    }

    #[test]
    fn public_tuple_plan_preserves_explicit_tuple_facts() {
        let descriptor = "easynet:///r/realm/ability/device.node-a.echo@2.4.0#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!invoke";
        let target = RemoteAbilityInvocationTarget::from_descriptor_ref(
            "easynet:///r/realm/device/node-a",
            descriptor,
        )
        .expect("target");
        let causal_context = CausalContext::None;
        let plan = RemoteInvocationTuplePlan::public_explicit(
            &target,
            "easynet:///r/realm/device/caller",
            "easynet:///r/realm/resource/user.alice/invoke/echo",
            [0x41; 16],
            causal_context.clone(),
            json!({"probe": true}),
            Duration::from_secs(7),
        )
        .expect("tuple plan");

        assert_eq!(plan.subject.policy_name(), "Explicit");
        assert_eq!(plan.nonce, RemoteInvocationNonce::Explicit([0x41; 16]));
        assert_eq!(
            plan.causal_context,
            InvocationCausalContext::explicit(causal_context)
        );

        let request = plan.into_request().expect("request");
        assert_eq!(request.caller_ura, "easynet:///r/realm/device/caller");
        assert_eq!(
            request.subject_ura,
            "easynet:///r/realm/resource/user.alice/invoke/echo"
        );
        assert_eq!(request.invocation_nonce, [0x41; 16]);
        assert_eq!(request.causal_context, CausalContext::None);
    }

    #[test]
    fn public_tuple_plan_preserves_explicit_causal_context() {
        let descriptor = "easynet:///r/realm/ability/device.node-a.echo@2.4.0#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!invoke";
        let target = RemoteAbilityInvocationTarget::from_descriptor_ref(
            "easynet:///r/realm/device/node-a",
            descriptor,
        )
        .expect("target");
        let causal_context = CausalContext::Merkle {
            root: [0x71; 32],
            proof_ura: "easynet:///r/realm/resource/user.alice/proof/causal".to_string(),
        };
        let request = RemoteInvocationTuplePlan::public_explicit(
            &target,
            "easynet:///r/realm/device/caller",
            "easynet:///r/realm/resource/user.alice/task/child",
            [0x51; 16],
            causal_context.clone(),
            Value::Null,
            Duration::from_secs(7),
        )
        .expect("tuple plan")
        .into_request()
        .expect("request");

        assert_eq!(request.causal_context, causal_context);
    }

    #[test]
    fn remote_system_issuer_names_system_root_derivation() {
        let target = RemoteAbilityInvocationTarget::for_target_owned_selector(
            "easynet:///r/realm/authority",
            "federation.resolve",
        )
        .expect("target");
        let plan = RemoteSystemInvocationIssuer::root_plan(
            &target,
            "easynet:///r/realm/device/caller",
            RemoteInvocationSubject::TargetOwnedSystem(target.as_str().to_string()),
            Value::Null,
            Duration::from_secs(30),
        )
        .expect("tuple plan");

        assert_eq!(plan.subject.policy_name(), "TargetOwnedSystem");
        assert_eq!(
            plan.causal_context,
            InvocationCausalContext::daemon_system_root()
        );
        assert_ne!(plan.nonce.derive(), [0; 16]);

        let request = plan.into_request().expect("request");
        assert_eq!(request.subject_ura, target.as_str());
        assert_ne!(request.invocation_nonce, [0; 16]);
        assert_eq!(request.causal_context, CausalContext::None);
    }

    #[test]
    fn tuple_plan_rejects_hidden_invalid_defaults() {
        let descriptor = "easynet:///r/realm/ability/device.node-a.echo@2.4.0#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!invoke";
        let target = RemoteAbilityInvocationTarget::from_descriptor_ref(
            "easynet:///r/realm/device/node-a",
            descriptor,
        )
        .expect("target");

        let bad_subject = RemoteInvocationTuplePlan::public_explicit(
            &target,
            "easynet:///r/realm/device/caller",
            "",
            [0x52; 16],
            CausalContext::None,
            Value::Null,
            Duration::from_secs(7),
        );
        assert!(bad_subject.is_err());

        let zero_timeout = RemoteInvocationTuplePlan::public_explicit(
            &target,
            "easynet:///r/realm/device/caller",
            target.callee_ura().to_string(),
            [0x53; 16],
            CausalContext::None,
            Value::Null,
            Duration::ZERO,
        );
        assert!(zero_timeout.is_err());
    }

    #[test]
    fn remote_request_rejects_incomplete_tuple_facts() {
        let descriptor = "easynet:///r/realm/ability/device.node-a.echo@2.4.0#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!invoke";
        let target = RemoteAbilityInvocationTarget::from_descriptor_ref(
            "easynet:///r/realm/device/node-a",
            descriptor,
        )
        .expect("target");

        let missing_caller = RemoteInvocationRequest::new(
            &target,
            "",
            target.callee_ura(),
            [0x11; 16],
            CausalContext::None,
            Value::Null,
            Duration::from_secs(1),
        );
        assert!(missing_caller.is_err());

        let zero_nonce = RemoteInvocationRequest::new(
            &target,
            "easynet:///r/realm/device/caller",
            target.callee_ura(),
            [0; 16],
            CausalContext::None,
            Value::Null,
            Duration::from_secs(1),
        );
        assert!(zero_nonce.is_err());
    }

    #[test]
    fn remote_receipt_key_resolver_rejects_malformed_trust_anchor() {
        let _home = crate::cli::commands::test_support::HomeGuard::new();
        let trust_path = std::env::temp_dir().join(format!(
            "easynet-remote-receipt-trust-{}.toml",
            std::process::id()
        ));
        std::fs::write(&trust_path, "trusted_agents = [").expect("write malformed trust anchor");

        let previous = std::env::var_os("EASYNET_REALM_TRUST_PATH");
        std::env::set_var("EASYNET_REALM_TRUST_PATH", &trust_path);
        let result = remote_receipt_key_resolver();
        match previous {
            Some(value) => std::env::set_var("EASYNET_REALM_TRUST_PATH", value),
            None => std::env::remove_var("EASYNET_REALM_TRUST_PATH"),
        }
        let _ = std::fs::remove_file(&trust_path);

        let error = match result {
            Ok(_) => panic!("malformed trust anchor must reject receipt verification"),
            Err(error) => error,
        };
        assert!(
            error
                .to_string()
                .contains("load realm trust anchor for remote receipt verification"),
            "diagnostic should identify the remote receipt trust source: {error:#}"
        );
    }

    #[test]
    fn federation_discover_subject_uses_hub_ability_subject_and_device_self_subject() {
        let hub = crate::core::ura::hub_ura("acme");
        assert_eq!(
            federation_discover_subject_ura(&hub).expect("hub subject"),
            crate::core::ura::owner_ability_ura(&hub, "federation.discover")
                .expect("hub ability subject")
        );

        let device = crate::core::ura::device_ura("acme", "device-a");
        assert_eq!(
            federation_discover_subject_ura(&device).expect("device subject"),
            device
        );
    }
}
