// Code generated by tools/scripts/generate-runtime-governance-routes.py. DO NOT EDIT.

import Foundation

enum RuntimeGovernanceRoutesGen {
    private static let routes: [(ability: String, provider: String)] = [
        ("meta.list_abilities", RuntimeDescriptorRefRequest.abilityDescriptorProvider),
        ("meta.list_resources", RuntimeDescriptorRefRequest.abilityDescriptorProvider),
        ("invocation.history.list", RuntimeDescriptorRefRequest.receiptHistoryProvider),
        ("invocation.history.get", RuntimeDescriptorRefRequest.receiptHistoryProvider),
        ("invocation.history.path", RuntimeDescriptorRefRequest.receiptHistoryProvider),
        ("invocation.record.get", RuntimeDescriptorRefRequest.receiptHistoryProvider),
        ("invocation.trace.get", RuntimeDescriptorRefRequest.receiptHistoryProvider),
    ]

    static func canonicalAbility(_ value: String) -> String? {
        let clean = value.trimmingCharacters(in: .whitespacesAndNewlines)
        return routes.first { route in
            clean == route.ability || clean.hasSuffix(".\(route.ability)")
        }?.ability
    }

    static func descriptorProvider(_ value: String) -> String {
        let clean = value.trimmingCharacters(in: .whitespacesAndNewlines)
        return routes.first { route in
            clean == route.ability || clean.hasSuffix(".\(route.ability)")
        }?.provider ?? ""
    }
}
