"""Product-neutral canonical runtime SDK.

The top-level package is a lazy export surface. Provider helper modules such as
``easynet_sdk.providers.runtime.plugin_exec`` must remain importable in minimal
plugin runtimes without forcing every core runtime dependency to load first.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    'AbilityURA',
    'AbilityCallRequest',
    'AbilityChildContext',
    'AbilityDescriptorClient',
    'AbilityDescriptorGetRequest',
    'AbilityDescriptorHints',
    'AbilityDescriptorListRequest',
    'AbilityDescriptorPage',
    'AbilityDescriptorProjection',
    'AbilityDescriptorProvider',
    'AbilityDescriptorRef',
    'AbilityInvocationClient',
    'RuntimeAbilityPackageManifest',
    'AbilityRef',
    'AbilityTargetRequest',
    'AccessControlAbilityCallTrace',
    'AccessControlAdmissionExplainRequest',
    'AccessControlAdmissionExplainResult',
    'AccessControlAuthorityProof',
    'AccessControlCheckRequest',
    'AccessControlCheckResult',
    'AccessControlClient',
    'AccessControlEffect',
    'AccessControlGrant',
    'AccessControlGrantRequest',
    'AccessControlGrantResult',
    'AccessControlGrantState',
    'AccessControlListRequest',
    'AccessControlListResult',
    'AccessControlPermissionRequest',
    'AccessControlPermissionRequestCreateRequest',
    'AccessControlPermissionRequestListRequest',
    'AccessControlPermissionRequestListResult',
    'AccessControlPermissionRequestResolutionResult',
    'AccessControlPermissionRequestResolveRequest',
    'AccessControlPolicyDecision',
    'AccessControlPrincipalKind',
    'AccessControlProvider',
    'AccessControlRevokeRequest',
    'AccessControlSignatureDecision',
    'AddressingClient',
    'AddressingProjection',
    'AddressingTransport',
    'ActingPrincipalRef',
    'AttachOptions',
    'AuthorizationProvider',
    'AuthorityArtifact',
    'AuthorityClient',
    'AuthorityMetadata',
    'AuthoritySignature',
    'AuthoritySignatureProvider',
    'AuthoritySigningMaterial',
    'AuthorityTransport',
    'authority_ura',
    'AuthorizationGrant',
    'AuthorizedInvocation',
    'AuthorizedRuntimeSession',
    'AxonAddressingTransport',
    'BidiChannel',
    'BidiFrame',
    'BidiOutcome',
    'BidiSession',
    'BidiSessionAdapter',
    'BidiState',
    'BidiStreamDescriptor',
    'BidiTerminalFrame',
    'BidiTransport',
    'BindPrincipalKeyRequest',
    'CanonicalAuthorityTransport',
    'CanonicalSigner',
    'CallerIdentityRef',
    'ChainCheckResult',
    'ChangePrincipalStateRequest',
    'Client',
    'ClockIdempotencySource',
    'ConfigureRecoveryRequest',
    'ConnectOptions',
    'ConnectionState',
    'CreatePrincipalRequest',
    'DEFAULT_DIRECTORY_PAGE_LIMIT',
    'DEFAULT_MANAGED_SIGNING_PAGE_SIZE',
    'DEFAULT_RECEIPT_PAGE_LIMIT',
    'DEFAULT_RUNTIME_EVENT_PAGE_LIMIT',
    'DELEGATION_METADATA_KEY',
    'DelegationProof',
    'DelegationRequest',
    'DescriptorProvider',
    'DescriptorResolution',
    'DescriptorResolutionRequest',
    'DescriptorResolutionState',
    'DiagnosticCheck',
    'DiagnosticsReport',
    'DirectoryClient',
    'DirectoryCursor',
    'DirectoryEvent',
    'DirectoryEventEnvelope',
    'DirectoryListRequest',
    'DirectoryPage',
    'DirectoryProvider',
    'DirectoryRecord',
    'DirectoryResolution',
    'DirectoryResolveKind',
    'DirectoryResolveRequest',
    'DirectorySubscribeRequest',
    'DirectorySubscription',
    'DirectorySubscriptionState',
    'DiscoveryTransport',
    'Endpoints',
    'EnrollmentCapability',
    'ErrorClass',
    'ErrorCode',
    'FeatureSet',
    'FrameStream',
    'HealthClient',
    'HealthTransport',
    'IdentityProvider',
    'InvocationBuilder',
    'InvocationCancel',
    'InvocationCausalLink',
    'InvocationDraft',
    'InvocationFailure',
    'InvocationHandle',
    'InvocationHandleEvent',
    'InvocationLedgerRecord',
    'InvocationLifecycleState',
    'InvocationObjectAdapter',
    'InvocationReceipt',
    'InvocationReceiptAnchor',
    'InvocationReceiptChainSummary',
    'InvocationResult',
    'InvocationResultAdapter',
    'InvocationSignature',
    'InvocationIntent',
    'InvocationTraceEdge',
    'InvocationTraceGraph',
    'InvocationWireProjector',
    'IssueEnrollmentRequest',
    'IssueGrantRequest',
    'MAX_BIDI_BUFFERED_FRAMES',
    'MAX_DIRECTORY_PAGE_LIMIT',
    'MAX_MANAGED_SIGNING_AUTO_ITEMS',
    'MAX_MANAGED_SIGNING_AUTO_PAGES',
    'MAX_MANAGED_SIGNING_PAGE_SIZE',
    'MAX_RECEIPT_PAGE_LIMIT',
    'MAX_RUNTIME_EVENT_PAGE_LIMIT',
    'MAX_STREAM_BUFFERED_EVENTS',
    'ManagedSigner',
    'ManagedSigningClient',
    'ManagedSigningCreateRequest',
    'ManagedSigningKey',
    'ManagedSigningKeyFilter',
    'ManagedSigningKeyPage',
    'ManagedSigningPeer',
    'ManagedSigningPeerPage',
    'ManagedSigningPeerRegistration',
    'ManagedSigningStatus',
    'NativeRuntimeHandle',
    'PrepareOptions',
    'PreparedInvocation',
    'PreparedInvocationState',
    'PrincipalRef',
    'PrincipalClient',
    'PrincipalCommand',
    'PrincipalLifecycle',
    'PrincipalProofKind',
    'PrincipalProofRef',
    'PrincipalSnapshot',
    'PrincipalState',
    'PublicKeyBinding',
    'PublicKeyBindingState',
    'ReceiptClient',
    'ReceiptFilter',
    'ReceiptGetRequest',
    'ReceiptGetResult',
    'ReceiptHistoryAuthorityScopeProvider',
    'ReceiptHistoryPage',
    'ReceiptLedgerSource',
    'ReceiptListRequest',
    'ReceiptLookup',
    'ReceiptProvider',
    'ReceiptReference',
    'ReceiptTraceRequest',
    'ReceiptTraceResult',
    'RecoverPrincipalRequest',
    'RecoveryPolicy',
    'ResolvedAbilityTarget',
    'RetryHint',
    'RevokeEnrollmentRequest',
    'RevokeGrantRequest',
    'RevokePrincipalKeyRequest',
    'RotatePrincipalKeyRequest',
    'RuntimeAbilityClient',
    'RuntimeAbilityDescriptorProvider',
    'HostStreamExec',
    'RuntimeAccessControlProvider',
    'RuntimeAdminAbilityClient',
    'RuntimeAdminClient',
    'RuntimeAdminCommand',
    'RuntimeCallContext',
    'RuntimeClient',
    'RuntimeClientDescriptorProvider',
    'RuntimeClientSessionRuntimeProvider',
    'RuntimeConnection',
    'RuntimeConnector',
    'RuntimeEndpoint',
    'RuntimeError',
    'RuntimeEvent',
    'RuntimeEventClient',
    'RuntimeEventCursor',
    'RuntimeEventPage',
    'RuntimeEventProvider',
    'RuntimeEventReadRequest',
    'RuntimeEventStreamState',
    'RuntimeHandleEventProvider',
    'RuntimeHandle',
    'RuntimeHealth',
    'RuntimeHost',
    'RuntimeHostDiscoverOptions',
    'RuntimeHostDiscoverRequest',
    'RuntimeHostHandle',
    'RuntimeHostStartRequest',
    'RuntimeBidiChannel',
    'RuntimeFrameStream',
    'RuntimeInvocationTransport',
    'RuntimeInvocationAuthority',
    'RuntimeControlDiscovery',
    'RuntimeControlIdentityProjection',
    'RuntimeIdentityProjection',
    'RuntimeIpcVersionRange',
    'RuntimeLifecycle',
    'RuntimeLifecycleState',
    'RuntimeLifecycleTransport',
    'RuntimePrincipalProvider',
    'RuntimeProvider',
    'RuntimeReadiness',
    'RuntimeRecoveryEvent',
    'RuntimeRecoveryReport',
    'RuntimeRecoveryRequest',
    'RuntimeRecoveryTransport',
    'RuntimeReceipt',
    'RuntimeReceiptAgentBinding',
    'RuntimeReceiptAuthorityProof',
    'RuntimeReceiptEntityRef',
    'RuntimeReceiptFailure',
    'RuntimeReceiptProvider',
    'RuntimeReceiptRef',
    'RuntimeReceiptSignature',
    'RuntimeReceiptSubjectBinding',
    'RuntimeReceiptUsage',
    'RuntimeSession',
    'RuntimeSessionState',
    'RuntimeSessionListRequest',
    'RuntimeSessionPage',
    'RuntimeStatus',
    'RuntimeTransport',
    'RuntimeTargetRef',
    'SDKError',
    'SESSION_AUTHORITY_METADATA_KEY',
    'SdkEnvironment',
    'SessionAuthority',
    'SessionAuthorityRequest',
    'SignatureProvider',
    'SignedInvocation',
    'Signer',
    'SignerHandle',
    'SignerPolicy',
    'SignerProvider',
    'SigningMaterial',
    'SignedInvocationState',
    'StaticCallerIdentityProvider',
    'StopOptions',
    'StreamCancel',
    'StreamEvent',
    'StreamHandle',
    'StreamState',
    'StreamTerminalEvent',
    'StreamTransport',
    'StreamValue',
    'StreamValueAdapter',
    'SubjectRef',
    'SubmittedInvocation',
    'SystemClockIdempotencySource',
    'TerminalReceipt',
    'UnaryDispatchPool',
    'UnaryInvocationTransport',
    'VerifiedReceipt',
    'Version',
    'agent_ura',
    'attach_runtime_host',
    'canonical_ability_descriptor_ref',
    'canonical_failure_code',
    'canonical_terminal_state_code',
    'connect_runtime_local',
    'default_environment',
    'device_ability_ura',
    'device_agent_ura',
    'device_ura',
    'discover_runtime_host',
    'error_class_for_code',
    'grant_actions',
    'is_code',
    'new_canonical_authority_client',
    'new_invocation_nonce_base64',
    'normalize_error_code',
    'owner_ability_ura',
    'owner_ura_for_ability',
    'parse_ability_descriptor_ref',
    'parse_ura',
    'profile_error_details',
    'profile_source_ref',
    'project_ability_descriptor',
    'project_descriptor_ref',
    'read_runtime_control_discovery',
    'read_runtime_identity_projection',
    'receipt_read_call_context',
    'resource_ura',
    'retryable_for_hint',
    'runtime_credentials_path',
    'runtime_state_read_subject_ura',
    'runtime_identity_projection_from_json',
    'runtime_state_root',
    'signer_handle_provenance_error',
    'start_runtime_host',
    'user_ura',
    'validate_authority_metadata',
]

_EXPORT_MODULES: dict[str, tuple[str, str]] = {
    'AbilityCallRequest': ('.ability_invocation', 'AbilityCallRequest'),
    'AbilityChildContext': ('.ability_invocation', 'AbilityChildContext'),
    'AbilityDescriptorClient': ('.ability_descriptor', 'AbilityDescriptorClient'),
    'AbilityDescriptorGetRequest': ('.ability_descriptor', 'AbilityDescriptorGetRequest'),
    'AbilityDescriptorHints': ('.ability_descriptor', 'AbilityDescriptorHints'),
    'AbilityDescriptorListRequest': ('.ability_descriptor', 'AbilityDescriptorListRequest'),
    'AbilityDescriptorPage': ('.ability_descriptor', 'AbilityDescriptorPage'),
    'AbilityDescriptorProjection': ('.ability_descriptor', 'AbilityDescriptorProjection'),
    'AbilityDescriptorProvider': ('.ability_descriptor', 'AbilityDescriptorProvider'),
    'AbilityDescriptorRef': ('.ability_descriptor', 'AbilityDescriptorRef'),
    'AbilityInvocationClient': ('.ability_invocation', 'AbilityInvocationClient'),
    'AbilityRef': ('.authorized_runtime_session', 'AbilityRef'),
    'AbilityTargetRequest': ('.ability_invocation', 'AbilityTargetRequest'),
    'AbilityURA': ('.axon_addressing', 'AbilityURA'),
    'AccessControlAbilityCallTrace': ('.access_control', 'AccessControlAbilityCallTrace'),
    'AccessControlAdmissionExplainRequest': ('.access_control', 'AccessControlAdmissionExplainRequest'),
    'AccessControlAdmissionExplainResult': ('.access_control', 'AccessControlAdmissionExplainResult'),
    'AccessControlAuthorityProof': ('.access_control', 'AccessControlAuthorityProof'),
    'AccessControlCheckRequest': ('.access_control', 'AccessControlCheckRequest'),
    'AccessControlCheckResult': ('.access_control', 'AccessControlCheckResult'),
    'AccessControlClient': ('.access_control', 'AccessControlClient'),
    'AccessControlEffect': ('.access_control', 'AccessControlEffect'),
    'AccessControlGrant': ('.access_control', 'AccessControlGrant'),
    'AccessControlGrantRequest': ('.access_control', 'AccessControlGrantRequest'),
    'AccessControlGrantResult': ('.access_control', 'AccessControlGrantResult'),
    'AccessControlGrantState': ('.access_control', 'AccessControlGrantState'),
    'AccessControlListRequest': ('.access_control', 'AccessControlListRequest'),
    'AccessControlListResult': ('.access_control', 'AccessControlListResult'),
    'AccessControlPermissionRequest': ('.access_control', 'AccessControlPermissionRequest'),
    'AccessControlPermissionRequestCreateRequest': ('.access_control', 'AccessControlPermissionRequestCreateRequest'),
    'AccessControlPermissionRequestListRequest': ('.access_control', 'AccessControlPermissionRequestListRequest'),
    'AccessControlPermissionRequestListResult': ('.access_control', 'AccessControlPermissionRequestListResult'),
    'AccessControlPermissionRequestResolutionResult': ('.access_control', 'AccessControlPermissionRequestResolutionResult'),
    'AccessControlPermissionRequestResolveRequest': ('.access_control', 'AccessControlPermissionRequestResolveRequest'),
    'AccessControlPolicyDecision': ('.access_control', 'AccessControlPolicyDecision'),
    'AccessControlPrincipalKind': ('.access_control', 'AccessControlPrincipalKind'),
    'AccessControlProvider': ('.access_control', 'AccessControlProvider'),
    'AccessControlRevokeRequest': ('.access_control', 'AccessControlRevokeRequest'),
    'AccessControlSignatureDecision': ('.access_control', 'AccessControlSignatureDecision'),
    'ActingPrincipalRef': ('.authorized_runtime_session', 'ActingPrincipalRef'),
    'AddressingClient': ('.axon_addressing', 'AddressingClient'),
    'AddressingProjection': ('.axon_addressing', 'AddressingProjection'),
    'AddressingTransport': ('.axon_addressing', 'AddressingTransport'),
    'AttachOptions': ('.runtime_lifecycle', 'AttachOptions'),
    'AuthorityArtifact': ('.authorized_runtime_session', 'AuthorityArtifact'),
    'AuthorityClient': ('.authority', 'AuthorityClient'),
    'AuthorityMetadata': ('.authority', 'AuthorityMetadata'),
    'AuthoritySignature': ('.authority', 'AuthoritySignature'),
    'AuthoritySignatureProvider': ('.authority', 'AuthoritySignatureProvider'),
    'AuthoritySigningMaterial': ('.authority', 'AuthoritySigningMaterial'),
    'AuthorityTransport': ('.authority', 'AuthorityTransport'),
    'AuthorizationGrant': ('.principal', 'AuthorizationGrant'),
    'AuthorizationProvider': ('.authorized_runtime_session', 'AuthorizationProvider'),
    'AuthorizedInvocation': ('.authorized_runtime_session', 'AuthorizedInvocation'),
    'AuthorizedRuntimeSession': ('.authorized_runtime_session', 'AuthorizedRuntimeSession'),
    'AxonAddressingTransport': ('.axon_addressing', 'AxonAddressingTransport'),
    'BidiChannel': ('.transport', 'BidiChannel'),
    'BidiFrame': ('.bidi', 'BidiFrame'),
    'BidiOutcome': ('.bidi', 'BidiOutcome'),
    'BidiSession': ('.bidi', 'BidiSession'),
    'BidiSessionAdapter': ('.transport', 'BidiSessionAdapter'),
    'BidiState': ('.bidi', 'BidiState'),
    'BidiStreamDescriptor': ('.bidi', 'BidiStreamDescriptor'),
    'BidiTerminalFrame': ('.bidi', 'BidiTerminalFrame'),
    'BidiTransport': ('.bidi', 'BidiTransport'),
    'BindPrincipalKeyRequest': ('.principal', 'BindPrincipalKeyRequest'),
    'CallerIdentityRef': ('.authorized_runtime_session', 'CallerIdentityRef'),
    'CanonicalAuthorityTransport': ('.authority', 'CanonicalAuthorityTransport'),
    'CanonicalSigner': ('.authority', 'CanonicalSigner'),
    'ChainCheckResult': ('.receipt', 'ChainCheckResult'),
    'ChangePrincipalStateRequest': ('.principal', 'ChangePrincipalStateRequest'),
    'Client': ('.client', 'Client'),
    'ClockIdempotencySource': ('.authorized_runtime_session', 'ClockIdempotencySource'),
    'ConfigureRecoveryRequest': ('.principal', 'ConfigureRecoveryRequest'),
    'ConnectOptions': ('.connection', 'ConnectOptions'),
    'ConnectionState': ('.connection', 'ConnectionState'),
    'CreatePrincipalRequest': ('.principal', 'CreatePrincipalRequest'),
    'DEFAULT_DIRECTORY_PAGE_LIMIT': ('.directory', 'DEFAULT_DIRECTORY_PAGE_LIMIT'),
    'DEFAULT_MANAGED_SIGNING_PAGE_SIZE': ('.managed_signing', 'DEFAULT_MANAGED_SIGNING_PAGE_SIZE'),
    'DEFAULT_RECEIPT_PAGE_LIMIT': ('.receipt', 'DEFAULT_RECEIPT_PAGE_LIMIT'),
    'DEFAULT_RUNTIME_EVENT_PAGE_LIMIT': ('.runtime_events', 'DEFAULT_RUNTIME_EVENT_PAGE_LIMIT'),
    'DELEGATION_METADATA_KEY': ('.authority', 'DELEGATION_METADATA_KEY'),
    'DelegationProof': ('.authority', 'DelegationProof'),
    'DelegationRequest': ('.authority', 'DelegationRequest'),
    'DescriptorProvider': ('.authorized_runtime_session', 'DescriptorProvider'),
    'DescriptorResolution': ('.authorized_runtime_session', 'DescriptorResolution'),
    'DescriptorResolutionRequest': ('.authorized_runtime_session', 'DescriptorResolutionRequest'),
    'DescriptorResolutionState': ('.authorized_runtime_session', 'DescriptorResolutionState'),
    'DiagnosticCheck': ('.health', 'DiagnosticCheck'),
    'DiagnosticsReport': ('.health', 'DiagnosticsReport'),
    'DirectoryClient': ('.directory', 'DirectoryClient'),
    'DirectoryCursor': ('.directory', 'DirectoryCursor'),
    'DirectoryEvent': ('.directory', 'DirectoryEvent'),
    'DirectoryEventEnvelope': ('.directory', 'DirectoryEventEnvelope'),
    'DirectoryListRequest': ('.directory', 'DirectoryListRequest'),
    'DirectoryPage': ('.directory', 'DirectoryPage'),
    'DirectoryProvider': ('.directory', 'DirectoryProvider'),
    'DirectoryRecord': ('.directory', 'DirectoryRecord'),
    'DirectoryResolution': ('.directory', 'DirectoryResolution'),
    'DirectoryResolveKind': ('.directory', 'DirectoryResolveKind'),
    'DirectoryResolveRequest': ('.directory', 'DirectoryResolveRequest'),
    'DirectorySubscribeRequest': ('.directory', 'DirectorySubscribeRequest'),
    'DirectorySubscription': ('.directory', 'DirectorySubscription'),
    'DirectorySubscriptionState': ('.directory', 'DirectorySubscriptionState'),
    'DiscoveryTransport': ('.client', 'DiscoveryTransport'),
    'Endpoints': ('.runtime_lifecycle', 'Endpoints'),
    'EnrollmentCapability': ('.principal', 'EnrollmentCapability'),
    'ErrorClass': ('.errors', 'ErrorClass'),
    'ErrorCode': ('.errors', 'ErrorCode'),
    'FeatureSet': ('.client', 'FeatureSet'),
    'FrameStream': ('.transport', 'FrameStream'),
    'HealthClient': ('.health', 'HealthClient'),
    'HealthTransport': ('.health', 'HealthTransport'),
    'HostStreamExec': ('.ability_package', 'HostStreamExec'),
    'IdentityProvider': ('.authorized_runtime_session', 'IdentityProvider'),
    'InvocationBuilder': ('.invocation', 'InvocationBuilder'),
    'InvocationCancel': ('.runtime', 'InvocationCancel'),
    'InvocationCausalLink': ('.receipt', 'InvocationCausalLink'),
    'InvocationDraft': ('.invocation', 'InvocationDraft'),
    'InvocationFailure': ('.runtime', 'InvocationFailure'),
    'InvocationHandle': ('.runtime', 'InvocationHandle'),
    'InvocationHandleEvent': ('.runtime', 'InvocationHandleEvent'),
    'InvocationIntent': ('.authorized_runtime_session', 'InvocationIntent'),
    'InvocationLedgerRecord': ('.receipt', 'InvocationLedgerRecord'),
    'InvocationLifecycleState': ('.invocation_state', 'InvocationLifecycleState'),
    'InvocationObjectAdapter': ('.ability_invocation', 'InvocationObjectAdapter'),
    'InvocationReceipt': ('.receipt', 'InvocationReceipt'),
    'InvocationReceiptAnchor': ('.receipt', 'InvocationReceiptAnchor'),
    'InvocationReceiptChainSummary': ('.receipt', 'InvocationReceiptChainSummary'),
    'InvocationResult': ('.runtime', 'InvocationResult'),
    'InvocationResultAdapter': ('.transport', 'InvocationResultAdapter'),
    'InvocationSignature': ('.invocation', 'InvocationSignature'),
    'InvocationTraceEdge': ('.receipt', 'InvocationTraceEdge'),
    'InvocationTraceGraph': ('.receipt', 'InvocationTraceGraph'),
    'InvocationWireProjector': ('.ability_invocation', 'InvocationWireProjector'),
    'IssueEnrollmentRequest': ('.principal', 'IssueEnrollmentRequest'),
    'IssueGrantRequest': ('.principal', 'IssueGrantRequest'),
    'MAX_BIDI_BUFFERED_FRAMES': ('.bidi', 'MAX_BIDI_BUFFERED_FRAMES'),
    'MAX_DIRECTORY_PAGE_LIMIT': ('.directory', 'MAX_DIRECTORY_PAGE_LIMIT'),
    'MAX_MANAGED_SIGNING_AUTO_ITEMS': ('.managed_signing', 'MAX_MANAGED_SIGNING_AUTO_ITEMS'),
    'MAX_MANAGED_SIGNING_AUTO_PAGES': ('.managed_signing', 'MAX_MANAGED_SIGNING_AUTO_PAGES'),
    'MAX_MANAGED_SIGNING_PAGE_SIZE': ('.managed_signing', 'MAX_MANAGED_SIGNING_PAGE_SIZE'),
    'MAX_RECEIPT_PAGE_LIMIT': ('.receipt', 'MAX_RECEIPT_PAGE_LIMIT'),
    'MAX_RUNTIME_EVENT_PAGE_LIMIT': ('.runtime_events', 'MAX_RUNTIME_EVENT_PAGE_LIMIT'),
    'MAX_STREAM_BUFFERED_EVENTS': ('.stream', 'MAX_STREAM_BUFFERED_EVENTS'),
    'ManagedSigner': ('.managed_signing', 'ManagedSigner'),
    'ManagedSigningClient': ('.managed_signing', 'ManagedSigningClient'),
    'ManagedSigningCreateRequest': ('.managed_signing', 'ManagedSigningCreateRequest'),
    'ManagedSigningKey': ('.managed_signing', 'ManagedSigningKey'),
    'ManagedSigningKeyFilter': ('.managed_signing', 'ManagedSigningKeyFilter'),
    'ManagedSigningKeyPage': ('.managed_signing', 'ManagedSigningKeyPage'),
    'ManagedSigningPeer': ('.managed_signing', 'ManagedSigningPeer'),
    'ManagedSigningPeerPage': ('.managed_signing', 'ManagedSigningPeerPage'),
    'ManagedSigningPeerRegistration': ('.managed_signing', 'ManagedSigningPeerRegistration'),
    'ManagedSigningStatus': ('.managed_signing', 'ManagedSigningStatus'),
    'NativeRuntimeHandle': ('.environment', 'NativeRuntimeHandle'),
    'PrepareOptions': ('.runtime', 'PrepareOptions'),
    'PreparedInvocation': ('.signing', 'PreparedInvocation'),
    'PreparedInvocationState': ('.authorized_runtime_session', 'PreparedInvocationState'),
    'PrincipalClient': ('.principal', 'PrincipalClient'),
    'PrincipalCommand': ('.principal', 'PrincipalCommand'),
    'PrincipalLifecycle': ('.principal', 'PrincipalLifecycle'),
    'PrincipalProofKind': ('.principal', 'PrincipalProofKind'),
    'PrincipalProofRef': ('.principal', 'PrincipalProofRef'),
    'PrincipalRef': ('.authorized_runtime_session', 'PrincipalRef'),
    'PrincipalSnapshot': ('.principal', 'PrincipalSnapshot'),
    'PrincipalState': ('.principal', 'PrincipalState'),
    'PublicKeyBinding': ('.principal', 'PublicKeyBinding'),
    'PublicKeyBindingState': ('.principal', 'PublicKeyBindingState'),
    'ReceiptClient': ('.receipt', 'ReceiptClient'),
    'ReceiptFilter': ('.receipt', 'ReceiptFilter'),
    'ReceiptGetRequest': ('.receipt', 'ReceiptGetRequest'),
    'ReceiptGetResult': ('.receipt', 'ReceiptGetResult'),
    'ReceiptHistoryAuthorityScopeProvider': ('.receipt', 'ReceiptHistoryAuthorityScopeProvider'),
    'ReceiptHistoryPage': ('.receipt', 'ReceiptHistoryPage'),
    'ReceiptLedgerSource': ('.receipt', 'ReceiptLedgerSource'),
    'ReceiptListRequest': ('.receipt', 'ReceiptListRequest'),
    'ReceiptLookup': ('.receipt', 'ReceiptLookup'),
    'ReceiptProvider': ('.receipt', 'ReceiptProvider'),
    'ReceiptReference': ('.receipt', 'ReceiptReference'),
    'ReceiptTraceRequest': ('.receipt', 'ReceiptTraceRequest'),
    'ReceiptTraceResult': ('.receipt', 'ReceiptTraceResult'),
    'RecoverPrincipalRequest': ('.principal', 'RecoverPrincipalRequest'),
    'RecoveryPolicy': ('.principal', 'RecoveryPolicy'),
    'ResolvedAbilityTarget': ('.ability_invocation', 'ResolvedAbilityTarget'),
    'RetryHint': ('.errors', 'RetryHint'),
    'RevokeEnrollmentRequest': ('.principal', 'RevokeEnrollmentRequest'),
    'RevokeGrantRequest': ('.principal', 'RevokeGrantRequest'),
    'RevokePrincipalKeyRequest': ('.principal', 'RevokePrincipalKeyRequest'),
    'RotatePrincipalKeyRequest': ('.principal', 'RotatePrincipalKeyRequest'),
    'RuntimeAbilityClient': ('.runtime_ability', 'RuntimeAbilityClient'),
    'RuntimeAbilityDescriptorProvider': ('.ability_descriptor', 'RuntimeAbilityDescriptorProvider'),
    'RuntimeAbilityPackageManifest': ('.ability_package', 'RuntimeAbilityPackageManifest'),
    'RuntimeAccessControlProvider': ('.access_control', 'RuntimeAccessControlProvider'),
    'RuntimeAdminAbilityClient': ('.runtime_admin', 'RuntimeAdminAbilityClient'),
    'RuntimeAdminClient': ('.runtime_admin', 'RuntimeAdminClient'),
    'RuntimeAdminCommand': ('.runtime_admin', 'RuntimeAdminCommand'),
    'RuntimeBidiChannel': ('.transport', 'RuntimeBidiChannel'),
    'RuntimeCallContext': ('.runtime_ability', 'RuntimeCallContext'),
    'RuntimeClient': ('.runtime', 'RuntimeClient'),
    'RuntimeClientDescriptorProvider': ('.authorized_runtime_session', 'RuntimeClientDescriptorProvider'),
    'RuntimeClientSessionRuntimeProvider': ('.authorized_runtime_session', 'RuntimeClientSessionRuntimeProvider'),
    'RuntimeConnection': ('.connection', 'RuntimeConnection'),
    'RuntimeConnector': ('.connection', 'RuntimeConnector'),
    'RuntimeControlDiscovery': ('.runtime_environment', 'RuntimeControlDiscovery'),
    'RuntimeControlIdentityProjection': ('.runtime_environment', 'RuntimeControlIdentityProjection'),
    'RuntimeEndpoint': ('.connection', 'RuntimeEndpoint'),
    'RuntimeError': ('.errors', 'RuntimeError'),
    'RuntimeEvent': ('.runtime_events', 'RuntimeEvent'),
    'RuntimeEventClient': ('.runtime_events', 'RuntimeEventClient'),
    'RuntimeEventCursor': ('.runtime_events', 'RuntimeEventCursor'),
    'RuntimeEventPage': ('.runtime_events', 'RuntimeEventPage'),
    'RuntimeEventProvider': ('.runtime_events', 'RuntimeEventProvider'),
    'RuntimeEventReadRequest': ('.runtime_events', 'RuntimeEventReadRequest'),
    'RuntimeEventStreamState': ('.runtime_events', 'RuntimeEventStreamState'),
    'RuntimeFrameStream': ('.transport', 'RuntimeFrameStream'),
    'RuntimeHandle': ('.runtime_lifecycle', 'RuntimeHandle'),
    'RuntimeHandleEventProvider': ('.runtime_events', 'RuntimeHandleEventProvider'),
    'RuntimeHealth': ('.health', 'RuntimeHealth'),
    'RuntimeHost': ('.runtime_lifecycle', 'RuntimeHost'),
    'RuntimeHostDiscoverOptions': ('.runtime_lifecycle', 'RuntimeHostDiscoverOptions'),
    'RuntimeHostDiscoverRequest': ('.runtime_lifecycle', 'RuntimeHostDiscoverRequest'),
    'RuntimeHostHandle': ('.runtime_lifecycle', 'RuntimeHostHandle'),
    'RuntimeHostStartRequest': ('.runtime_lifecycle', 'RuntimeHostStartRequest'),
    'RuntimeIdentityProjection': ('.runtime_environment', 'RuntimeIdentityProjection'),
    'RuntimeInvocationAuthority': ('.runtime_ability', 'RuntimeInvocationAuthority'),
    'RuntimeInvocationTransport': ('.transport', 'RuntimeInvocationTransport'),
    'RuntimeIpcVersionRange': ('.runtime_environment', 'RuntimeIpcVersionRange'),
    'RuntimeLifecycle': ('.runtime_lifecycle', 'RuntimeLifecycle'),
    'RuntimeLifecycleState': ('.runtime_lifecycle', 'RuntimeLifecycleState'),
    'RuntimeLifecycleTransport': ('.runtime_lifecycle', 'RuntimeLifecycleTransport'),
    'RuntimePrincipalProvider': ('.principal', 'RuntimePrincipalProvider'),
    'RuntimeProvider': ('.authorized_runtime_session', 'RuntimeProvider'),
    'RuntimeReadiness': ('.runtime_admin', 'RuntimeReadiness'),
    'RuntimeReceipt': ('.runtime', 'RuntimeReceipt'),
    'RuntimeReceiptAgentBinding': ('.runtime', 'RuntimeReceiptAgentBinding'),
    'RuntimeReceiptAuthorityProof': ('.runtime', 'RuntimeReceiptAuthorityProof'),
    'RuntimeReceiptEntityRef': ('.runtime', 'RuntimeReceiptEntityRef'),
    'RuntimeReceiptFailure': ('.runtime', 'RuntimeReceiptFailure'),
    'RuntimeReceiptProvider': ('.receipt', 'RuntimeReceiptProvider'),
    'RuntimeReceiptRef': ('.runtime', 'RuntimeReceiptRef'),
    'RuntimeReceiptSignature': ('.runtime', 'RuntimeReceiptSignature'),
    'RuntimeReceiptSubjectBinding': ('.runtime', 'RuntimeReceiptSubjectBinding'),
    'RuntimeReceiptUsage': ('.runtime', 'RuntimeReceiptUsage'),
    'RuntimeRecoveryEvent': ('.runtime', 'RuntimeRecoveryEvent'),
    'RuntimeRecoveryReport': ('.runtime', 'RuntimeRecoveryReport'),
    'RuntimeRecoveryRequest': ('.runtime', 'RuntimeRecoveryRequest'),
    'RuntimeRecoveryTransport': ('.runtime', 'RuntimeRecoveryTransport'),
    'RuntimeSession': ('.runtime_admin', 'RuntimeSession'),
    'RuntimeSessionListRequest': ('.runtime_admin', 'RuntimeSessionListRequest'),
    'RuntimeSessionPage': ('.runtime_admin', 'RuntimeSessionPage'),
    'RuntimeSessionState': ('.authorized_runtime_session', 'RuntimeSessionState'),
    'RuntimeStatus': ('.runtime_lifecycle', 'RuntimeStatus'),
    'RuntimeTargetRef': ('.authorized_runtime_session', 'RuntimeTargetRef'),
    'RuntimeTransport': ('.runtime', 'RuntimeTransport'),
    'SDKError': ('.errors', 'SDKError'),
    'SESSION_AUTHORITY_METADATA_KEY': ('.authority', 'SESSION_AUTHORITY_METADATA_KEY'),
    'SdkEnvironment': ('.environment', 'SdkEnvironment'),
    'SessionAuthority': ('.authority', 'SessionAuthority'),
    'SessionAuthorityRequest': ('.authority', 'SessionAuthorityRequest'),
    'SignatureProvider': ('.signing', 'SignatureProvider'),
    'SignedInvocation': ('.signing', 'SignedInvocation'),
    'SignedInvocationState': ('.authorized_runtime_session', 'SignedInvocationState'),
    'Signer': ('.signing', 'Signer'),
    'SignerHandle': ('.signer_handle', 'SignerHandle'),
    'SignerPolicy': ('.signing', 'SignerPolicy'),
    'SignerProvider': ('.authorized_runtime_session', 'SignerProvider'),
    'SigningMaterial': ('.signing', 'SigningMaterial'),
    'StaticCallerIdentityProvider': ('.authorized_runtime_session', 'StaticCallerIdentityProvider'),
    'StopOptions': ('.runtime_lifecycle', 'StopOptions'),
    'StreamCancel': ('.stream', 'StreamCancel'),
    'StreamEvent': ('.stream', 'StreamEvent'),
    'StreamHandle': ('.stream', 'StreamHandle'),
    'StreamState': ('.stream', 'StreamState'),
    'StreamTerminalEvent': ('.stream', 'StreamTerminalEvent'),
    'StreamTransport': ('.stream', 'StreamTransport'),
    'StreamValue': ('.transport', 'StreamValue'),
    'StreamValueAdapter': ('.transport', 'StreamValueAdapter'),
    'SubjectRef': ('.authorized_runtime_session', 'SubjectRef'),
    'SubmittedInvocation': ('.authorized_runtime_session', 'SubmittedInvocation'),
    'SystemClockIdempotencySource': ('.authorized_runtime_session', 'SystemClockIdempotencySource'),
    'TerminalReceipt': ('.authorized_runtime_session', 'TerminalReceipt'),
    'UnaryDispatchPool': ('.transport', 'UnaryDispatchPool'),
    'UnaryInvocationTransport': ('.transport', 'UnaryInvocationTransport'),
    'VerifiedReceipt': ('.receipt', 'VerifiedReceipt'),
    'Version': ('.client', 'Version'),
    'agent_ura': ('.axon_addressing', 'agent_ura'),
    'attach_runtime_host': ('.runtime_lifecycle', 'attach_runtime_host'),
    'authority_ura': ('.axon_addressing', 'authority_ura'),
    'canonical_ability_descriptor_ref': ('.axon_addressing', 'canonical_ability_descriptor_ref'),
    'canonical_failure_code': ('.errors', 'canonical_failure_code'),
    'canonical_terminal_state_code': ('.errors', 'canonical_terminal_state_code'),
    'connect_runtime_local': ('.runtime_lifecycle', 'connect_runtime_local'),
    'default_environment': ('.environment', 'default_environment'),
    'device_ability_ura': ('.axon_addressing', 'device_ability_ura'),
    'device_agent_ura': ('.axon_addressing', 'device_agent_ura'),
    'device_ura': ('.axon_addressing', 'device_ura'),
    'discover_runtime_host': ('.runtime_lifecycle', 'discover_runtime_host'),
    'error_class_for_code': ('.errors', 'error_class_for_code'),
    'grant_actions': ('.principal', 'grant_actions'),
    'is_code': ('.errors', 'is_code'),
    'new_canonical_authority_client': ('.authority', 'new_canonical_authority_client'),
    'new_invocation_nonce_base64': ('.invocation', 'new_invocation_nonce_base64'),
    'normalize_error_code': ('.errors', 'normalize_error_code'),
    'owner_ability_ura': ('.axon_addressing', 'owner_ability_ura'),
    'owner_ura_for_ability': ('.axon_addressing', 'owner_ura_for_ability'),
    'parse_ability_descriptor_ref': ('.ability_descriptor', 'parse_ability_descriptor_ref'),
    'parse_ura': ('.axon_addressing', 'parse_ura'),
    'profile_error_details': ('.errors', 'profile_error_details'),
    'profile_source_ref': ('.errors', 'profile_source_ref'),
    'project_ability_descriptor': ('.ability_descriptor', 'project_ability_descriptor'),
    'project_descriptor_ref': ('.axon_addressing', 'project_descriptor_ref'),
    'read_runtime_control_discovery': ('.runtime_environment', 'read_runtime_control_discovery'),
    'read_runtime_identity_projection': ('.runtime_environment', 'read_runtime_identity_projection'),
    'receipt_read_call_context': ('.receipt', 'receipt_read_call_context'),
    'resource_ura': ('.axon_addressing', 'resource_ura'),
    'retryable_for_hint': ('.errors', 'retryable_for_hint'),
    'runtime_credentials_path': ('.runtime_environment', 'runtime_credentials_path'),
    'runtime_identity_projection_from_json': ('.runtime_environment', 'runtime_identity_projection_from_json'),
    'runtime_state_read_subject_ura': ('._runtime_subjects', 'runtime_state_read_subject_ura'),
    'runtime_state_root': ('.runtime_environment', 'runtime_state_root'),
    'signer_handle_provenance_error': ('.signer_handle', 'signer_handle_provenance_error'),
    'start_runtime_host': ('.runtime_lifecycle', 'start_runtime_host'),
    'user_ura': ('.axon_addressing', 'user_ura'),
    'validate_authority_metadata': ('.authority', 'validate_authority_metadata'),
}


def __getattr__(name: str) -> Any:
    target = _EXPORT_MODULES.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = target
    value = getattr(import_module(module_name, __name__), attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
