# Code generated by provider_routes/generate_access_control_routes.py; DO NOT EDIT.

_PROFILE = "access_control"
_ACCESS_CONTROL_ROUTE_MANIFEST_SHA256 = "382074b1171e40afc508fe852948f9043b20503b51d9383b9523490f3c68b14e"
_ABILITY_GRANT = "authority.binding.grant"
_ABILITY_REVOKE = "authority.binding.revoke"
_ABILITY_LIST = "authority.binding.list"
_ABILITY_CHECK = "authority.binding.check"
_ABILITY_POLICY_REQUEST_CREATE = "policy.request.create"
_ABILITY_POLICY_REQUEST_RESOLVE = "policy.request.resolve"
_ABILITY_POLICY_REQUEST_LIST = "policy.request.list"
_ABILITY_ADMISSION_EXPLAIN = "admission.explain"
