# Code generated by provider_routes/generate_runtime_admin_routes.py; DO NOT EDIT.

_PROFILE = "runtime_admin"
_RUNTIME_ADMIN_ROUTE_MANIFEST_SHA256 = "71c67fa97b2645662acfbc511de0219c3d0e92112ecf0485e8bb336952e0a937"
_RUNTIME_ADMIN_SESSION_LIST_ABILITY = "session.list"
_RUNTIME_ADMIN_DEVICE_REVOKE_ABILITY = "federation.revoke"
