# Code generated by provider_routes/generate_runtime_admin_routes.py; DO NOT EDIT.

_PROFILE = "runtime_admin"
_RUNTIME_ADMIN_ROUTE_MANIFEST_SHA256 = "7ebcf5c31052f8a37e2a5d4f98943db90c7506a4795195ab6f1aaa2ce90c21cf"
_RUNTIME_ADMIN_SESSION_LIST_ABILITY = "session.list"
