# Code generated by provider_routes/generate_runtime_admin_routes.py; DO NOT EDIT.

_PROFILE = "runtime_admin"
_RUNTIME_ADMIN_ROUTE_MANIFEST_SHA256 = "193ba5b5a28180af5d5d936930e880f7d40153963f85c6d0425c54febb214d6a"
_RUNTIME_ADMIN_SESSION_LIST_ABILITY = "session.list"
