//! Admission, caller validation, quota, and trust gates for daemon Invocation.

#[cfg(feature = "axon-pb")]
pub mod admission_facade;
pub(crate) mod authority_metadata;
pub mod authority_proof;
#[cfg(feature = "axon-pb")]
pub(crate) mod bootstrap_authority;
pub mod child_invocation_builder;
pub mod decision;
#[cfg(feature = "axon-pb")]
pub(crate) mod device_caller;
#[cfg(feature = "axon-pb")]
pub mod device_trust_sync;
#[cfg(feature = "axon-pb")]
pub mod federated_key_resolver;
pub mod grant_matcher;
#[cfg(feature = "axon-pb")]
pub(crate) mod hosted_agent_delegation;
#[cfg(feature = "axon-pb")]
pub(crate) mod hosted_agent_publication;
#[cfg(feature = "axon-pb")]
pub(crate) mod identity_write_gate;
#[cfg(feature = "axon-pb")]
pub mod list_user_pubkeys;
#[cfg(feature = "axon-pb")]
pub(crate) mod owner_projection_publication;
pub mod owner_resolution;
#[cfg(feature = "axon-pb")]
pub(crate) mod peer_envelope_signer;
pub mod policy_engine;
#[cfg(feature = "axon-pb")]
pub mod policy_gate;
#[cfg(feature = "axon-pb")]
pub(crate) mod principal_lifecycle;
#[cfg(feature = "axon-pb")]
pub(crate) mod quota_meter;
#[cfg(feature = "axon-pb")]
pub mod register_device_pubkey;
#[cfg(feature = "axon-pb")]
pub mod revoke_user_pubkey;
#[cfg(feature = "axon-pb")]
pub(crate) mod runtime_trust;
#[cfg(feature = "axon-pb")]
pub(crate) mod runtime_trust_invalidator;
#[cfg(feature = "axon-pb")]
pub(crate) mod target_gate;
pub mod trace_projection;
#[cfg(feature = "axon-pb")]
pub mod usage_quota;
