// EasyNet library crate root
// ==========================
//
// File: src/lib.rs
// Description: Library crate surface for `easynet_cli`.
//
// v10.5 R1: PR-DAEMON splits the historical binary-only crate into
// three targets sharing one library:
//
//   [lib]     easynet_cli (cdylib + rlib + staticlib) — this file
//   [[bin]]   easynet         — thin CLI wrapper in src/bin/easynet.rs
//   [[bin]]   easynet-daemon  — long-running daemon in src/bin/easynet-daemon.rs
//
// The lib carries all the business modules (core / eal / facade /
// persistence / registry / runtime / support) plus a forthcoming
// `ffi` module that exposes a C ABI for non-Rust clients loading
// `libeasynet_cli.{so,dylib,dll,a}`.
//
// Why a crate-type cdylib when we also have rlib + staticlib
// ----------------------------------------------------------
// - `rlib` keeps Rust-to-Rust internal linking available (bins in
//   this workspace consume the library as a regular Rust crate).
// - `cdylib` produces a shared library loadable from C FFI callers
//   (Go cgo, Python cffi, Swift C interop, Node N-API, Java JNI).
// - `staticlib` produces an `.a` archive for platforms that prefer
//   static linking (notably iOS).
//
// Not adding `dylib` because that carries Rust-specific symbol
// mangling; the goal here is a stable C ABI, not Rust ABI.
//
// Author: Silan Hu <silan.hu@u.nus.edu>
// Copyright (c) 2026 EasyNet. All rights reserved.

// Crate-level lint policy — matches src/bin/easynet.rs for consistency.
#![allow(
    clippy::needless_pass_by_value,
    clippy::struct_excessive_bools,
    clippy::doc_markdown,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::module_name_repetitions
)]

pub mod core;
pub mod eal;
pub mod facade;
pub mod ffi;
pub mod persistence;
pub mod registry;
pub mod runtime;
pub mod services;
pub mod support;
pub mod ura;

/// Generated tonic + prost types for axon's `axon.v1.*` protos.
///
/// Populated by `build.rs` when the `axon-pb` feature is enabled
/// (RFC-003 PR-1, see `pr-drafts/PR-0-spec-daemon-invocation-server.md
/// §2`). The proto declares `package axon.v1;`, so the tonic-emitted
/// file lands at `axon.v1.rs` and is included here.
///
/// Callers reach the server-side `Invocation` trait via
/// `easynet_cli::pb::axon::v1::invocation_server::Invocation`. Off
/// by default so developers without `protoc` on PATH still build
/// the CLI.
///
/// Out of scope for the commit that adds this entry: the actual
/// `DaemonInvocationService` implementation. This module exists
/// only to make the trait importable; the impl lands in a
/// follow-up commit on the same `rfc-001-impl` branch.
#[cfg(feature = "axon-pb")]
pub mod pb {
    pub mod axon {
        pub mod v1 {
            // Generated by prost/tonic from the canonical Axon proto set.
            // Local lint policy applies at the conversion/service boundary,
            // not inside regenerated wire structs.
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            tonic::include_proto!("axon.v1");
        }
    }
}
