// EasyNet CLI — plugin descriptor projection
// ==========================================
//
// File: src/daemon/plugins/descriptor.rs
// Description: Project package-index metadata into ability descriptors.

use serde_json::Value;

use crate::daemon::ability::descriptors::AbilityHints;
use crate::daemon::plugins::errors::PluginHostError;
use crate::daemon::plugins::errors::Result;
use crate::daemon::plugins::index::PluginPackageIndex;
use crate::daemon::plugins::manifest::CallMode;

/// Descriptor-generation metadata for one plugin-owned ability.
#[derive(Debug, Clone)]
pub struct PluginAbilityMetadata {
    pub name: String,
    pub description: String,
    pub input_schema: Value,
    pub output_schema: Option<Value>,
    pub hints: AbilityHints,
    pub admission_action: crate::daemon::ability::descriptors::AdmissionAction,
}

/// Descriptor projector over package index state.
pub struct PluginDescriptorProjector;

impl PluginDescriptorProjector {
    /// Project every plugin ability descriptor that can be generated by this
    /// binary. This ignores env, platform, and runtime load status.
    pub fn project(index: &PluginPackageIndex) -> Result<Vec<PluginAbilityMetadata>> {
        let mut out = Vec::new();
        for package in index.packages() {
            for descriptor in package.ability_descriptors() {
                let ability = package
                    .manifest()
                    .ability(descriptor.name())
                    .ok_or_else(|| PluginHostError::DescriptorProjectionFailed {
                        ability: descriptor.name().to_string(),
                        reason: "ability descriptor has no matching manifest metadata".to_string(),
                    })?;
                out.push(PluginAbilityMetadata {
                    name: descriptor.name().to_string(),
                    description: descriptor.description().to_string(),
                    input_schema: descriptor.input_schema().clone(),
                    output_schema: descriptor.output_schema().cloned(),
                    hints: hints_for_call_mode(ability.call_mode()),
                    admission_action: descriptor.admission_action(),
                });
            }
        }
        out.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(out)
    }
}

fn hints_for_call_mode(call_mode: CallMode) -> AbilityHints {
    match call_mode {
        CallMode::Rpc => AbilityHints::default(),
        CallMode::Stream => AbilityHints {
            streaming_only: true,
            ..AbilityHints::default()
        },
        CallMode::Bidi => AbilityHints {
            bidi_only: true,
            ..AbilityHints::default()
        },
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::*;
    use crate::daemon::plugins::package::tests::write_test_package;
    use crate::daemon::plugins::package::PluginPackage;

    #[test]
    fn plugin_host_descriptor_projector_uses_installed_ability_toml() {
        let root = tempfile::tempdir().expect("root");
        write_test_package(root.path(), "0.1.0");
        let package = Arc::new(PluginPackage::from_installed(root.path(), None).expect("package"));
        let index = PluginPackageIndex::from_packages(vec![package]).expect("index");

        let descriptors = PluginDescriptorProjector::project(&index).expect("descriptors");
        let descriptor = descriptors
            .iter()
            .find(|descriptor| descriptor.name == "test.echo")
            .expect("installed plugin descriptor");

        assert_eq!(descriptor.description, "test descriptor for test.echo");
        assert_eq!(descriptor.input_schema["type"], "object");
        assert_eq!(descriptor.hints, AbilityHints::default());
        assert!(descriptor.output_schema.is_none());
    }

    #[test]
    #[cfg(feature = "remote-desktop")]
    fn plugin_host_descriptor_projector_preserves_manifest_call_modes() {
        let index = crate::daemon::plugins::PluginPackageIndex::builtin()
            .expect("builtin plugin index loads");
        let descriptors = PluginDescriptorProjector::project(&index).expect("descriptors");
        let watch_events = descriptors
            .iter()
            .find(|descriptor| descriptor.name == "remote_desktop.watch_events")
            .expect("remote desktop watch_events descriptor");
        let attach = descriptors
            .iter()
            .find(|descriptor| descriptor.name == "remote_desktop.attach")
            .expect("remote desktop attach descriptor");

        assert!(
            watch_events.hints.streaming_only,
            "InvokeStream plugin abilities must advertise streaming_only"
        );
        assert!(
            attach.hints.bidi_only,
            "InvokeBidi plugin abilities must advertise bidi_only"
        );
    }
}
