// Code generated by provider_routes/generate_access_control_routes.py; DO NOT EDIT.

#[cfg(test)]
pub(crate) const ACCESS_CONTROL_PROFILE: &str = "access_control";
#[cfg(test)]
pub(crate) const ACCESS_CONTROL_ROUTE_MANIFEST_SHA256: &str =
    "677ac1516587c846cbdc12e74b1d35b880e260e291fcf7570859f4b220922e1a";
pub(crate) const AUTHORITY_BINDING_GRANT: &str = "authority.binding.grant";
pub(crate) const AUTHORITY_BINDING_REVOKE: &str = "authority.binding.revoke";
pub(crate) const AUTHORITY_BINDING_LIST: &str = "authority.binding.list";
pub(crate) const AUTHORITY_BINDING_CHECK: &str = "authority.binding.check";
pub(crate) const POLICY_REQUEST_CREATE: &str = "policy.request.create";
pub(crate) const POLICY_REQUEST_RESOLVE: &str = "policy.request.resolve";
pub(crate) const POLICY_REQUEST_LIST: &str = "policy.request.list";
pub(crate) const ADMISSION_EXPLAIN: &str = "admission.explain";
