// Code generated by provider_routes/generate_principal_routes.py; DO NOT EDIT.

#[cfg(test)]
pub(crate) const PRINCIPAL_LIFECYCLE_PROFILE: &str = "principal_lifecycle";
#[cfg(test)]
pub(crate) const PRINCIPAL_ROUTE_MANIFEST_SHA256: &str =
    "268a2e372ca9fa106c868a0b4c2561d334fd72dc62f8844b5a8add627de52038";
pub(crate) const ABILITY_PRINCIPAL_CREATE: &str = "principal.lifecycle.create";
pub(crate) const ABILITY_PRINCIPAL_BIND_FIRST_KEY: &str = "principal.lifecycle.bind_first_key";
pub(crate) const ABILITY_PRINCIPAL_ADD_KEY: &str = "principal.lifecycle.add_key";
pub(crate) const ABILITY_PRINCIPAL_ROTATE_KEY: &str = "principal.lifecycle.rotate_key";
pub(crate) const ABILITY_PRINCIPAL_REVOKE_KEY: &str = "principal.lifecycle.revoke_key";
pub(crate) const ABILITY_PRINCIPAL_CONFIGURE_RECOVERY: &str =
    "principal.lifecycle.configure_recovery";
pub(crate) const ABILITY_PRINCIPAL_RECOVER: &str = "principal.lifecycle.recover";
pub(crate) const ABILITY_PRINCIPAL_SUSPEND: &str = "principal.lifecycle.suspend";
pub(crate) const ABILITY_PRINCIPAL_REACTIVATE: &str = "principal.lifecycle.reactivate";
pub(crate) const ABILITY_PRINCIPAL_DELETE: &str = "principal.lifecycle.delete";
pub(crate) const ABILITY_PRINCIPAL_ISSUE_ENROLLMENT: &str = "principal.lifecycle.issue_enrollment";
pub(crate) const ABILITY_PRINCIPAL_REVOKE_ENROLLMENT: &str =
    "principal.lifecycle.revoke_enrollment";
pub(crate) const ABILITY_PRINCIPAL_ISSUE_GRANT: &str = "principal.lifecycle.issue_grant";
pub(crate) const ABILITY_PRINCIPAL_REVOKE_GRANT: &str = "principal.lifecycle.revoke_grant";
pub(crate) const ABILITY_PRINCIPAL_GET: &str = "principal.lifecycle.get";
