// Code generated by provider_routes/generate_receipt_routes.py; DO NOT EDIT.

#[cfg(test)]
pub(crate) const RECEIPT_PROFILE: &str = "receipt";
#[cfg(test)]
pub(crate) const RECEIPT_ROUTE_MANIFEST_SHA256: &str =
    "0f692814e211b24c224f741686470220354360263921553d1fe045df2304c178";
pub(crate) const INVOCATION_HISTORY_LIST: &str = "invocation.history.list";
pub(crate) const INVOCATION_HISTORY_GET: &str = "invocation.history.get";
pub(crate) const INVOCATION_TRACE_GET: &str = "invocation.trace.get";
