// @generated by tools/scripts/generate-runtime-governance-routes.py

pub(crate) const ABILITY_DESCRIPTOR_PROVIDER: &str = "ability_descriptor";
pub(crate) const RECEIPT_HISTORY_PROVIDER: &str = "receipt_history";

pub(crate) const ABILITY_DESCRIPTOR_ABILITIES: &[&str] =
    &["meta.list_abilities", "meta.list_resources"];

pub(crate) const RECEIPT_HISTORY_ABILITIES: &[&str] = &[
    "invocation.history.list",
    "invocation.history.get",
    "invocation.history.path",
    "invocation.record.get",
    "invocation.trace.get",
];

pub(crate) fn canonical_governance_ability(value: &str) -> Option<&'static str> {
    let value = value.trim();
    ABILITY_DESCRIPTOR_ABILITIES
        .iter()
        .chain(RECEIPT_HISTORY_ABILITIES)
        .copied()
        .find(|ability| value == *ability || value.ends_with(&format!(".{ability}")))
}

pub(crate) fn descriptor_provider(value: &str) -> Option<&'static str> {
    let ability = canonical_governance_ability(value)?;
    if ABILITY_DESCRIPTOR_ABILITIES.contains(&ability) {
        Some(ABILITY_DESCRIPTOR_PROVIDER)
    } else {
        Some(RECEIPT_HISTORY_PROVIDER)
    }
}
