// Code generated by provider_routes/generate_runtime_admin_routes.py; DO NOT EDIT.

#[cfg(test)]
pub(crate) const RUNTIME_ADMIN_PROFILE: &str = "runtime_admin";
#[cfg(test)]
pub(crate) const RUNTIME_ADMIN_ROUTE_MANIFEST_SHA256: &str =
    "193ba5b5a28180af5d5d936930e880f7d40153963f85c6d0425c54febb214d6a";
pub(crate) const SESSION_LIST: &str = "session.list";
pub(crate) const FEDERATION_REVOKE: &str = "federation.revoke";
