// Code generated by provider_routes/generate_runtime_admin_routes.py; DO NOT EDIT.

#[cfg(test)]
pub(crate) const RUNTIME_ADMIN_PROFILE: &str = "runtime_admin";
#[cfg(test)]
pub(crate) const RUNTIME_ADMIN_ROUTE_MANIFEST_SHA256: &str =
    "7ebcf5c31052f8a37e2a5d4f98943db90c7506a4795195ab6f1aaa2ce90c21cf";
pub(crate) const SESSION_LIST: &str = "session.list";
pub(crate) const FEDERATION_REVOKE: &str = "federation.revoke";
