<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\easynet.ico</ApplicationIcon>
    <AssemblyName>EasyNetTray</AssemblyName>
    <RootNamespace>EasyNetTray</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\easynet.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
